ably/docs

- content/realtime/presence.textile
https://github.com/ably/ably-js/issues/26
> Replaced 'subscribe' with 'on'

- content/assets/javascripts/application.js
- content/client-lib-development-guide/documentation-formatting-guide.textile
- content/client-lib-development-guide/features.textile
- content/client-lib-development-guide/websocket.textile
- content/general/authentication.textile
- content/realtime/authentication.textile
- content/realtime/presence.textile
- content/rest-api/index.textile
- content/rest/authentication.textile
To be merged in once new token changes are pushed to production
> New token auth

- content/client-lib-development-guide/features.textile
> Realtime edits

- README.md
- content/assets/stylesheets/documentation.scss
> Move "Jump to" nav into right margin

- content/client-lib-development-guide/features.textile
@tcard I have imported your IDL, and then gone through it to double check the definitions.  I found a few small issues and fixed them plus added consistent ordering for classes which is embeds, constructors, attributes, methods, all in alphabetical order.  You can see just these changes at https://github.com/ably/docs/compare/5d31555...api-idl. If you agree with my changes, you will most likely need to roll these changes to your iOS API work.
cc @paddybyers 
BTW. A screenshot of how it looks is below:
> Client library API IDL

- content/client-lib-development-guide/encryption.textile
- content/client-lib-development-guide/features.textile
- content/client-lib-development-guide/protocol.textile
- content/client-lib-development-guide/websocket.textile
- content/general/authentication.textile
- content/realtime/channels-messages.textile
- content/realtime/connection.textile
- content/realtime/encryption.textile
- content/realtime/usage.textile
- content/rest/encryption.textile
- content/rest/usage.textile
- content/types/_channel_event.textile
- content/types/_channel_state.textile
- content/types/_cipher_params.textile
- docs.gemspec
Fixed https://github.com/ably/wiki/issues/68
> Standardise on initialize

- content/client-lib-development-guide/features.textile
https://github.com/ably/ably-ios/pull/359#discussion_r57985905
> RSL1g1b: Ably does assign clientId in messages

- content/client-lib-development-guide/features.textile
See https://github.com/ably/ably-js/issues/284
> Clarify that presence map is cleared on detach

- Gemfile
- Gemfile.lock
- Rules
- content/adaptors/pubnub.md
- content/adaptors/pusher.md
- content/code/adaptors/pubnub-pub-sub.code
- content/code/adaptors/pusher-pub-sub.code
- data/jsbins.yaml
- lib/ably_freshdesk_post_compile.rb
- lib/ably_markdown_code_for_freshdesk.rb
@SimonWoolf I made some updates to the translator docs in your repo, but then thought that it would be better to be in here and we can more easily link to code examples etc.
The only issue is the Pusher demo does not work.  Can you take a look?  Any feedback appreciated too.
FYI. The MD files are compiled to HTML files in the `output` folder so we can use that HTML in Freshdesk
> Protocol adaptors

- Dockerfile
- README.md
- docker-run
- docker/entry_point.sh
This  make it much easier for devs to work with this repo on any platform
Fixes https://github.com/ably/docs/issues/150
> Add Docker support

- content/realtime/usage.textile
- content/rest/usage.textile
- content/root/quick-start-guide.textile
- content/tutorials/history.textile
- content/tutorials/publish-subscribe.textile
ably/ably-ios#510
Search for:
*  `pod 'AblyRealtime'`
* `AblyRealtime.h`
* `import AblyRealtime`
> iOS: AblyRealtime to Ably

- content/client-lib-development-guide/features.textile
> Add Message.fromEncoded and Message.fromEncodedArray specs

- content/general/webhooks.textile
@paddybyers @SimonWoolf please review, this is the documentation for WebHook Message support + details on binary support.
> Webhook docs update

- content/tutorials/token-authentication.textile
@mattheworiordan I'm creating a PR for Java server-side tutorials
> tutorial: Java Token Authentication

- content/client-lib-development-guide/features.textile
@tcard @SimonWoolf please review
> Final 0.9 idl fixes

- app/assets/javascripts/application.js
- app/assets/stylesheets/global.scss
- content/realtime/connection.textile
- content/realtime/encryption.textile
- content/realtime/history.textile
- content/realtime/presence.textile
- content/realtime/statistics.textile
- content/realtime/usage.textile
- content/rest/usage.textile
- layouts/_head.html.erb
Fixes https://github.com/ably/docs/issues/219 and https://github.com/ably/docs/issues/228.
cc @SimonWoolf
> Various improvements

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/226
@paddybyers @tcard @SimonWoolf you happy for me to proceed?
> spec: Fix listener issue in RTL7c

- content/realtime/authentication.textile
- content/rest/authentication.textile
Fixes https://github.com/ably/ably-java/issues/186
@paddybyers @SimonWoolf this introduces the incompatibility in Java 0.8 into the docs, we'll need to revert when we support 0.9 in Java
> docs: Java #authorize arity correction for 0.8

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/245
> Clarify wording on sending capabilities or TTL in a tokenRequest

- content/general/authentication.textile
- content/general/versions/v0.8/authentication.textile
Per https://github.com/ably/website/pull/950#issuecomment-276525763
> Add para on capability wildcards; other auth tweaks

- content/client-lib-development-guide/protocol.textile
- content/general/versions/v0.8/webhooks.textile
- content/general/webhooks.textile
- content/realtime/channels-messages.textile
- content/realtime/presence.textile
- content/rest/channels-messages.textile
- content/rest/presence.textile
- content/shared/_message_from_encoded.textile
- content/shared/_presence_from_encoded.textile
- content/types/_presence_message.textile
Fixes https://github.com/ably/docs/issues/270
> Update webhook documentation

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/274
> Http Request and Retry Timeout fix

- content/client-lib-development-guide/features.textile
See discussion https://ably-real-time.slack.com/archives/C030APSH3/p1503940782000117
> Add spec item for transportParams overriding default params

- content/tutorials/react-native-presence-publish-subscribe.textile
Tutorial on how to use react-native with ably. This tutorial covers presence, publish and subscribe functions
> ably-react-native-presence-publish-subscribe

- app.json
Added https://github.com/heroku/heroku-buildpack-static to buildpacks
> Added extra buildpack

- content/root/quick-start-guide.textile
See https://github.com/ably/docs/issues/379
> fix for c sharp quick start

- content/types/_client_options.textile
For issues #311 and #277. Adds information on environment and fallback hosts to the ClientOptions type.
> Added environment, fallbackHostsUseDefault and fallbackHosts

- content/general/authentication.textile
For https://github.com/ably/website/issues/1504
> Clarified that JWT times are in seconds

- content/general/statistics.textile
Fixes  https://github.com/ably/docs/issues/440
> Update stats example with latest

- content/general/firehose.textile
- content/general/functions.textile
- content/general/queues.textile
- content/general/smart-notifications.textile
- content/general/statistics.textile
- content/general/webhooks.textile
- content/realtime/channels-messages.textile
- content/realtime/encryption.textile
- content/realtime/index.textile
- content/realtime/push/admin.textile
- content/rest-api/index.textile
- content/rest-api/token-request-spec.textile
- content/rest/channels-messages.textile
- content/rest/encryption.textile
- content/rest/index.textile
- content/rest/types.textile
- content/rest/usage.textile
Part of https://github.com/ably/website/pull/1601, specifically https://github.com/ably/website/pull/1601#pullrequestreview-142478855.
> Added links to all titles

- content/root/best-practice-guide.textile
- content/root/best-practices-guide.textile
Initial idea referred from https://github.com/ably/docs/issues/396
> best practices guide added

- content/tutorials/web-rtc-data-channels.textile
- content/tutorials/web-rtc-file-transfer.textile
- content/tutorials/web-rtc-screen-sharing.textile
- content/tutorials/web-rtc-video-calling.textile
> added ably logo

- content/general/queues.textile
(per https://github.com/ably/realtime/pull/1309 -- I think I meant to do this last October and forgot about it)
> Update queue documentation to match standardised reactor envelope

- content/core-features/pubsub.textile
- content/realtime/usage.textile
- content/root/how-ably-works.textile
Part of request in https://github.com/ably/website/pull/1750#issuecomment-420175011. Once merged, will update https://github.com/ably/website/pull/1854 accordingly.
> Made use of non-tech channels page in less technical documentation

- content/client-lib-development-guide/features.textile
You OK to merge and we can then raise issues in all libs to update?
> Don’t enable idempotency in 1.1 by default, wait until 1.2

- content/client-lib-development-guide/features.textile
> Add requirements for push types

- content/realtime/presence.textile
Please reivew freddo urgently.
> Fixed the ordering of dropdown topics in realtime/presence

- content/realtime/connection.textile
Changed key to position 4 in line with the page.
> Updated error in jump nav

- content/code/rest/batch-publish.code
- content/rest-api/beta.textile
- content/rest-api/index.textile
- content/rest/channels.textile
- data/jsbins.yaml
- lib/ably_jsbin_publisher.rb
For #553 
JSbin includes using REST API directly from console and using Request method in JS. Most content taken from @paddybyers 's gist, https://gist.github.com/paddybyers/932cb484362713f52bfa762611b0b865#background.
> Added basic docs for batch publishing + jsbin

- content/types/_client_options.textile
See also https://github.com/ably/ably-java/pull/461.
> Add link to java README in relation to the static nature of the logger

- content/general/versions/v1.0/webhooks.textile
- content/general/webhooks.textile
We've had a few requests to update this. The new service seems legitimate and works the same way from what I can see, but if either of you can see anything concerning regarding it let me know and we can use a different bin service instead.
> Updated requestb.in to requestbin

- content/general/push/_push_intro.textile
- content/general/push/activate-subscribe.textile
- content/general/push/admin.textile
- content/general/push/publish.textile
- content/types/_device_details.textile
> Push polish

- content/general/push/publish.textile
Regarding https://github.com/ably/ably-cocoa/issues/837, I found a wrong ObjC code snippet.
> New iOS Push revision

- content/shared/_presence_states.textile
> C# presence state text fix

- content/realtime/messages.textile
- content/rest/messages.textile
> Added extras to messages TOC

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/661
> RTN11d: clarify that should reset msgSerial to 0 on reconnect

- content/compare/pusher-vs-pubnub.textile
- content/compare/realtime-vs-push.textile
- content/realtime/usage.textile
- content/rest/usage.textile
> Corrected multiple ably links to use www.

- Rules
- app/assets/javascripts/application.js
- content/code/sse/eventstream.code
- content/code/sse/sse.code
- content/sse/index.textile
- content/streaming-api/index.textile
- data/jsbins.yaml
- layouts/_nav.html.erb
- lib/documentation_languages.rb
Initial rough-and-ready version of SSE / HTTP streaming api documentation.
> Add http streaming api documentation

- content/client-lib-development-guide/features.textile
See https://github.com/ably/docs/issues/671
> Spec: add requirements for Auth.currentTokenDetails

- content/rest/channels.textile
- content/rest/encryption.textile
- content/rest/history.textile
- content/rest/presence.textile
- content/rest/statistics.textile
- content/rest/usage.textile
From `&ast;` to `<notextile>*</notextile>`
> Change how asterisk for Go is specified

- content/code/rest/batch-presence.code
- content/realtime/presence.textile
- content/rest-api/beta.textile
- content/rest/presence.textile
- data/jsbins.yaml
Adds beta documentation for using the batch presence functionality which is being introduced.
> Added batch presence documentation

- content/tutorials/live-bitcoin-pricing.textile
The first commit is just for typos/grammar issues I saw, the second is for Kendo UI content. Feel free to take/leave what you will!
> Ably kendo ui update

- content/code/realtime/rewind.code
- content/realtime/channels.textile
- content/realtime/history.textile
- data/jsbins.yaml
Adds rewind details to `/realtime/history` and `/realtime/channels`.
> Rewind docs

- content/code/realtime/rewind.code
- content/realtime/channels.textile
- data/jsbins.yaml
> Fixed code samples for rewind

- content/general/push/admin.textile
- content/realtime/push.textile
- content/rest/push.textile
> Remove get method for PushChannelSubscription

- content/code/adapters/pubnub-pub-sub.code
- content/code/adapters/pusher-pub-sub.code
- content/code/api-streamer/tfl.code
- content/code/quick-start-guide/send-message.code
- content/code/reactor/webhook-hmac-sha-256.code
- content/code/realtime/channel-states.code
- content/code/realtime/connection-states.code
- content/code/realtime/rewind.code
- content/code/rest/batch-presence.code
- content/code/rest/batch-publish.code
- data/jsbins.yaml
Per discussion in Slack, changed refs to our version of jQuery.
> Changed jsbin jquery refs to ably endpoint

- content/general/push/publish.textile
- content/rest/push.textile
- content/types/_device_details.textile
- content/types/_paginated_result.textile
- content/types/_push_admin.textile
- Hash to Array for types
- Fixed a missing bracket in code example
- Enabled PHP as lang in rest/push docs
> Various adjustements to PHP push docs

- content/mqtt/index.textile
> Fixed broken visual MQTT sample code

- content/concepts/webhooks.textile
I updated the content for the webhooks piece - please just review for any errors.
I've updated the necessary things (i.e. the webhooks card on the concepts page, helper) on the website repo too - that will show once I push my pricing copy changes.
> Updates webhook concept piece

- config/config.rb
- lib/jsbins.rb
**What**
Namespace the config.
**Why**
To allow various config classes to co-exist while avoiding name collisions.
> Namespace the config

- content/code/realtime/connection-recover.code
- content/realtime/connection.textile
- data/jsbins.yaml
fixes #621 Adds it to the existing connection recovery with no filters code sample. Potential to add more explicit reference to it elsewhere.
> fixes #621 - Adds jsbin example for connection recovery in browser

- content/concepts/websub.textile
Removing extra heading tag and bump index
> [WEB-64] Feature/web 64 four concept articles

- content/realtime/channels.textile
- content/realtime/usage.textile
- content/rest/channels.textile
- content/rest/usage.textile
fixes #724 . If happy with this I can implement the same for REST
> Adds 'Channels' documentation to realtime 'Channel' page

- content/tutorials/reactor-event-ifttt.textile
Updating author metadata for the ifttt tutorial
> ifttt tutorial: author metadata to ably team

- content/mqtt/index.textile
newlines in a codeblock were breaking the styling of the codeblock. I've deleted the newlines but we should look into why newlines aren't working in codeblocks
> removed newlines from codeblock that were breaking codeblock formatting

- content/core-features/channels.textile
- content/core-features/pubsub.textile
* Ref: https://ably.atlassian.net/browse/FEA-49
> change status.ably.io to status.ably.com

- content/tutorials/trainapp-fitbit.textile
A tutorial to create a fitbit app using the Tube schedule Hub stream
> Fitbit tutorial

- config/tutorials/README.md
- content/tutorials/_multiplayer-vr-web.textile
- content/tutorials/_realtime-voting-angular.textile
- content/tutorials/channel-enumeration-rest.textile
- content/tutorials/channel-lifecycle-events.textile
- content/tutorials/channel-occupancy-events.textile
- content/tutorials/channel-rewind.textile
- content/tutorials/encryption.textile
- content/tutorials/jwt-authentication.textile
- content/tutorials/live-bitcoin-pricing.textile
- content/tutorials/mqtt-snake.textile
- content/tutorials/presence.textile
- content/tutorials/pubnub-adapter.textile
- content/tutorials/pusher-adapter.textile
- content/tutorials/queue-amqp-neutrino-profanity.textile
- content/tutorials/queue-amqp-wolfram-alpha.textile
- content/tutorials/queue-stomp-neutrino-profanity.textile
- content/tutorials/webhook-chuck-norris.textile
Add missing // in author links
> Fix broken link to the default author

- content/sse/index.textile
> SSE docs - added lastevent info

- data/compare.yaml
Updated mentions of deltas in the comparisons with competitors.
> [WEB-409] Add / update mentions of "deltas" on Ably website

- content/partials/types/_channel_options.textile
> Fixed formatting for channel_options

- content/realtime/channels/channel-parameters/rewind.textile
fixes #903 . Let me know if you're happy with language.
> Corrected details in rewind documentation on persistence

- config/tutorials/README.md
Cleaning up the loose ends with a detailed explanation of the recent changes to the textile metadata, and related usage recommendations.
> [WEB-256] Updated tutorials metadata reference

- content/realtime/channels.textile
- content/realtime/connection.textile
- content/realtime/history.textile
- content/realtime/versions/v0.8/channels.textile
- content/realtime/versions/v0.8/connection.textile
- content/realtime/versions/v0.8/history.textile
- content/realtime/versions/v0.8/messages.textile
- content/realtime/versions/v1.0/channels.textile
- content/realtime/versions/v1.0/connection.textile
- content/realtime/versions/v1.0/history.textile
- content/realtime/versions/v1.1/channels.textile
- content/realtime/versions/v1.1/connection.textile
- content/realtime/versions/v1.1/history.textile
- content/root/quick-start-guide.textile
Addressing https://ably.atlassian.net/browse/WEB-430
> [WEB-430] Replace broken obj-c code samples

- data/compare.yaml
Remoces legacy mentions of "coming soon" and "by march 2020" in the comparison yaml doc.
Please check all is bueno.
> Corrections and clarifications in comparisons

- content/realtime/channels/channel-parameters/deltas.textile
> of to if in deltas documentation

- content/general/versions/v1.0/webhooks.textile
> Broken link in Webhooks documentation

- content/core-features/authentication.textile
- content/core-features/versions/v0.8/authentication.textile
- content/core-features/versions/v1.0/authentication.textile
This is part of the website PR, and consists mostly of textile changes to articles with incorrect metadata in the YAML front matter.
> [WEB-282] fix metadata for authentication

- content/root/quick-start-guide.textile
Added missing language and 'jump to' frontmatter to the quickstart guide
> Added frontmatter

- content/tutorials/channel-enumeration-rest.textile
Fixes bad variable names and adds let/ const in place of var
> updated code standards for channel enum tutorial

- content/realtime/channel-metadata.textile
Prompted by https://app.intercom.com/a/apps/ua39m1ld/inbox/inbox/all/conversations/38483300002276
> Update description of log metachannel

- README.md
- writing-style-guide.md
Adds initial version of the writing style guide for developer docs.
> Add Writing Style Guide

- content/tutorials/realtime-cryptocurrency-app-flutter.textile
- Added redirects from 4 URLs of the tutorial that Google Analytic shows. (is the format of the URL ok? We don't need to include https://www.ably.io/? 
- Optimized the ALT attribute of the Data flow image
- Added a new image to showcase Syncfusion charts.
Let me know if it's all good
> Added redirects, updated alt image, and added a new image.

- content/general/events.textile
- content/general/queues.textile
- content/general/versions/v1.0/queues.textile
- content/general/versions/v1.1/queues.textile
- content/partials/tutorials/_create-reactor-rule-event.textile
- content/tutorials/queue-amqp-neutrino-profanity.textile
- content/tutorials/queue-amqp-wolfram-alpha.textile
- content/tutorials/queue-stomp-neutrino-profanity.textile
- content/tutorials/reactor-event-aws.textile
- content/tutorials/reactor-event-azure.textile
- content/tutorials/reactor-event-google.textile
- content/tutorials/reactor-event-zapier.textile
- content/tutorials/webhook-chuck-norris.textile
Renames Reactor tab to Integrations tab as per DOC-255.
> DOC-255: Rename Reactor tab to Integrations tab

- content/realtime/index.textile
- content/realtime/versions/v1.0/index.textile
- content/realtime/versions/v1.1/index.textile
Fixes typo in all doc versions.
* [page to review]()
> DOC-261: Fix typo

- content/client-lib-development-guide/features.textile
As proposed by https://github.com/ably/docs/issues/1041, see that issue for more details and justification.
Already approved by Paddy in principle, this just implements it.
> Spec: add RTL5i (attached received while in the detaching state)

- writing-style-guide.md
Minor typo corrections in the writing style guide.
> Fix minor typos in writing style guide

- content/asset-tracking/using-the-sdks.textile
Corrects the code example for connecting the publisher.
> Fix asset tracking connection code

- content/core-features/authentication.textile
- data/jsbins.yaml
Just adding some notes about using `authCallback`, since it didn't exist before. 
**TODO:**
> Add code snippet and information for `authCallback`

- content/tutorials/channel-occupancy-events.textile
* [JIRA ticket](https://ably.atlassian.net/browse/DOC-382).
Check all links on this page:
* [Page to review](https://ably-docs-pr-1133.herokuapp.com/tutorials/channel-occupancy-events/)
> DOC-382: fix link

- content/client-lib-development-guide/versioning.textile
Make it clear that, although we tend to follow the semantic versioning scheme, there are differences.
* [DOC-314](https://ably.atlassian.net/browse/DOC-314).
Please check the intro para on this page:
* [Ably Versioning](https://ably-docs-pr-1135.herokuapp.com/client-lib-development-guide/versioning/)
> Clarify our approach to semantic versioning

- content/realtime/presence.textile
- content/rest/presence.textile
Add presence topic page metadata description and keywords
* [DOC-394](https://ably.atlassian.net/browse/DOC-394).
Check front matter for the realtime and rest `presence.textile` files.
> Add presence page metadata

- content/control-api/index.textile
Fixes metadata description for Control API user guide.
* [JIRA ticket](https://ably.atlassian.net/browse/DOC-386).
> fix: metadata description

- content/general/push.textile
- content/general/versions/v1.0/push.textile
- content/general/versions/v1.1/push.textile
- content/partials/types/_device_details.textile
- content/partials/versions/v1.0/types/_device_details.textile
- content/partials/versions/v1.1/types/_device_details.textile
This PR removes mention of smart notifications - a feature that isn't yet released. See [this JIRA](https://ably.atlassian.net/browse/DOC-408) for further information.
The pages this PR changes are:
* [Push notifications overview](https://ably-docs-pr-1146.herokuapp.com/general/push/)
* [Device activation and subscription](http://ably-docs-pr-1146.herokuapp.com/general/push/activate-subscribe/)
> DOC-408: Remove mention of smart notifications

- content/general/incoming-webhooks.textile
This small PR updates the metadata keywords for incoming webhooks in order to improve its visibility in search results. See [JIRA](https://ably.atlassian.net/browse/DOC-285) for details.
This PR only updates the metadata for a file.
> Update incoming webhook meta keywords

- content/root/quick-start-guide.textile
[DOC-231](https://ably.atlassian.net/browse/DOC-231)
This PR aims to improve the readability and consistency of the quickstart guide. The key changes are:
* Removed the front-loaded concepts and linked to the glossary.
* Made the guide step-based.
* Made the wording consistent between languages.
* Added a step for closing the connection.
* Updated the 'next steps' links.
The page to review can seen [here](https://ably-docs-pr-1136.herokuapp.com/quick-start-guide/).
> DOC-231: Improve readability and consistency of quickstart guide

- content/root/quick-start-guide.textile
This PR updates the code examples for JavaScript in the quickstart. See [JIRA](https://ably.atlassian.net/browse/DOC-411) for further information.
To review, visit the [quickstart](https://ably-docs-pr-1170.herokuapp.com/quick-start-guide/) page and view it in JavaScript.
> DOC-411: Update JavaScript code samples for the quickstart

- content/root/quick-start-guide.textile
This PR updates and fixes the code examples for Node JS in the quickstart. See [JIRA](https://ably.atlassian.net/browse/DOC-412) for further information.
To review, visit the [quickstart](https://ably-docs-pr-1169.herokuapp.com/quick-start-guide/) page and view it in Node.
> DOC-412: Update NodeJS code samples for the quickstart

- content/root/quick-start-guide.textile
This PR updates and fixes the code examples for Java in the quickstart. See [JIRA](https://ably.atlassian.net/browse/DOC-413) for further information.
To review, visit the [quickstart](https://ably-docs-pr-1168.herokuapp.com/quick-start-guide/) page and view it in Java.
> DOC-413: Update Java code examples for the quickstart

- pull_request_template.md
Minor update to template.
Diff pull request template.
> Add reminder to include epic if applicable

- content/root/quick-start-guide.textile
This is a small PR updating the Ruby instructions for the quickstart. Some changes had [previously been made](https://github.com/ably/docs/pull/1161) for Ruby. See [JIRA](https://ably.atlassian.net/browse/DOC-414) for further information.
View the [quickstart](https://ably-docs-pr-1172.herokuapp.com/quick-start-guide/) in Ruby to review this PR.
> DOC-414: Update Ruby code samples and descriptions

- content/asset-tracking/index.textile
Clarify scope of trackable IDs and the name of the channel wherein updates are sent.
* [DOC-402](https://ably.atlassian.net/browse/DOC-402) - if applicable.
Check the text at the bottom of the intro section.
* [Asset tracking overview page](https://ably-docs-pr-1180.herokuapp.com/asset-tracking)
> Clarify scope and name of trackables

- content/root/quick-start-guide.textile
This PR adds Go text and code samples to the quickstart.
See [JIRA](https://ably.atlassian.net/browse/DOC-274) for further information.
View the [quickstart](https://ably-docs-pr-1179.herokuapp.com/quick-start-guide/) and select 'Go' to review.
> DOC-274: Add Go code samples and text to quickstart

- content/general/push/publish.textile
Include how to specify APNS headers in push notifications
> Specify APNS headers

- content/general/limits.textile
Document rates and limits for the platform.
Page can be viewed [here](http://ably-docs-pr-1101.herokuapp.com/general/limits)
> DOC-115: Platform limits and rates

- content/control-api/curl-examples.textile
Add more examples to Curl examples page:
* [Jira epic ticket](https://ably.atlassian.net/browse/FEA-1046)
* [Jira ticket](https://ably.atlassian.net/browse/DOC-449).
Please review the following added sections:
* [Key examples section](https://ably-docs-pr-1185.herokuapp.com/control-api/curl-examples/#examples-keys)
* [Rules examples section](https://ably-docs-pr-1185.herokuapp.com/control-api/curl-examples/#examples-rules)
It may be worth testing some examples, and also checking links to docs.
> Extend Control API examples

- content/root/quick-start-guide.textile
Add a link to Control API under Next Steps. The idea is to promote visibility of Control API.
* [Jira epic ticket](https://ably.atlassian.net/browse/FEA-1071)
* [Jira ticket](https://ably.atlassian.net/browse/DOC-463).
On the page to review, navigate to the "Next up" section and check that there is now a link to Control API, and that the link works.
* [Page to review](https://ably-docs-pr-1188.herokuapp.com/quick-start-guide/)
> Add link to Quickstart

- content/general/limits.textile
This PR adds a note on viewing the notifications for exceeded limits in the dashboard.
See [JIRA](https://ably.atlassian.net/browse/DOC-114) for further information - note that the other points listed were covered in [this PR](https://github.com/ably/docs/pull/1101).
To review this PR, visit [this page](http://ably-docs-pr-1197.herokuapp.com/general/limits).
> DOC-114: Add instructions on viewing limit notifications

- content/root/quick-start-guide.textile
This PR updates the Flutter code samples for the quickstart so that they are all working correctly. See [JIRA](https://ably.atlassian.net/browse/DOC-415) for any further details.
To review this PR, view the [quickstart page](http://ably-docs-pr-1205.herokuapp.com/quick-start-guide) in Flutter.
> DOC-415: Update Flutter quickstart code samples

- content/root/quick-start-guide.textile
This PR corrects the code samples for PHP in the quickstart guide. See [JIRA](https://ably.atlassian.net/browse/DOC-417) for further information.
To review, see [this page](http://ably-docs-pr-1207.herokuapp.com/quick-start-guide) in PHP.
> DOC-417: Update PHP code examples

- content/root/quick-start-guide.textile
This PR updates the .NET code examples in the quickstart. See [JIRA](https://ably.atlassian.net/browse/DOC-420) for further information.
View [this page](http://ably-docs-pr-1208.herokuapp.com/quick-start-guide) in .NET to review.
> DOC-420: Update .NET code examples in the quickstart

- content/general/limits.textile
This PR documents the limits introduced for apps under a new "app limits" section. See [JIRA](https://ably.atlassian.net/browse/DOC-438) for further information
View the new app limits section on the [limits page](http://ably-docs-pr-1200.herokuapp.com/general/limits) to review this PR.
> DOC-438: Add app limits documentation

- content/root/quick-start-guide.textile
This PR updates the Obj-C code samples for the quickstart. See [JIRA](https://ably.atlassian.net/browse/DOC-418) for further information. 
To review this PR, view the [quickstart](http://ably-docs-pr-1210.herokuapp.com/quick-start-guide) in Obj-C.
> DOC-418: Update Obj-C code samples

- content/root/quick-start-guide.textile
This PR updates the Swift code samples for the quickstart. See [JIRA](https://ably.atlassian.net/browse/DOC-419) for further information.
To review this PR, view the [quickstart](http://ably-docs-pr-1225.herokuapp.com/quick-start-guide) in Swift.
> DOC-419: Update Swift code samples for quickstart

- content/general/events.textile
- content/general/events/aws-lambda.textile
- content/general/events/azure.textile
- content/general/events/cloudflare.textile
- content/general/events/google-functions.textile
- content/general/events/ifttt.textile
- content/general/events/zapier.textile
- content/general/firehose.textile
- content/realtime/metachannels.textile
Customers should avoid specifying metachannels in a channel filter as a way of monitoring occupancy, presence and lifecycle events.
* [DOC-503](https://ably.atlassian.net/browse/DOC-503)
> Avoid using metachannels with rules

- content/realtime/metachannels.textile
This PR adds some information about the new app stats metachannel.
* [DOC-506](https://ably.atlassian.net/browse/DOC-506).
Please check: 
* stats is added to list of metachannels
* New app stats section
* Jump to app stats works
* Check links to stats page and to schema
The page to review is:
* [Metachannels](https://ably-docs-pr-1227.herokuapp.com/realtime/metachannels/)
> Add app stats metachannel

- content/general/events.textile
- content/general/events/aws-lambda.textile
- content/general/events/azure.textile
- content/general/events/cloudflare.textile
- content/general/events/google-functions.textile
- content/general/events/ifttt.textile
- content/general/events/zapier.textile
- content/partials/general/events/_batched_events.textile
- content/partials/general/events/_enveloped_events.textile
- content/partials/general/events/_non_enveloped_event_headers.textile
When updating source types to include message, lifecycle, presence and occupancy, some sections were missed. 
* [DOC-550](https://ably.atlassian.net/browse/DOC-550).
Check that other sections that need to be updated with all four source types have been. Also, all four source types work for both single and batch mode.
* [Page to review](https://ably-docs-pr-1235.herokuapp.com/general/events/)
> Update source type sections that were missed

- content/root/glossary.textile
This PR adds an entry for the Control API to the glossary.
To review this PR, see the [glossary](https://ably-docs-pr-1248.herokuapp.com/glossary/#control).
> DOC-462: Add Control API to the glossary

- content/core-features/authentication.textile
- content/rest-api/index.textile
This PR adds a Token Revocation section to the Auth & Security topic, and also a small section in the REST API Specification topic.
* [Jira epic ticket](https://ably.atlassian.net/browse/DOC-517) - DOC-538, DOC-537, DOC-540
* [Main topic page](https://ably-docs-pr-1250.herokuapp.com/core-features/authentication/#token-revocation)
* [REST API Spec page](http://ably-docs-pr-1250.herokuapp.com/rest-api/#revoke-tokens)
Note: For content review must be tested under web view for actual rendering.
> Token revocation docs

- content/general/aws-authentication.textile
- content/general/events.textile
- content/general/events/aws-lambda.textile
- content/general/events/azure.textile
- content/general/events/cloudflare.textile
- content/general/events/google-functions.textile
- content/general/events/ifttt.textile
- content/general/events/zapier.textile
- content/index.textile
- content/partials/general/events/_non_enveloped_event_headers.textile
- content/partials/tutorials/_create-reactor-rule-event.textile
- content/realtime/versions/v1.0/channel-metadata.textile
- content/realtime/versions/v1.1/channel-metadata.textile
- content/tutorials/reactor-event-ifttt.textile
"Rule" should not be capitalized unless it is part of a heading, or it is capitalized in a UI element caption.
* [DOC-551](https://ably.atlassian.net/browse/DOC-551).
Check all "Rule -> rule" changes in this PR's modified files.
> Fix rule mis-capitalization

- content/api-streamer/consumer.textile
- content/api-streamer/hub.textile
- content/api-streamer/index.textile
- content/api-streamer/producer.textile
- content/mqtt/index.textile
- content/realtime/metachannels.textile
- content/tutorials/web-rtc-data-channels.textile
- content/tutorials/web-rtc-file-transfer.textile
- content/tutorials/web-rtc-screen-sharing.textile
- content/tutorials/web-rtc-video-calling.textile
This PR updates the "Contact Us" occurrences to make them consistent. It also:
* Replaces all email addresses with a link to Contact Us
* Removes instances of referring to the docs as "Beta" and to contact support to improve them
* Removes reference of tutorials that are yet to be written with links to support
It is easiest to review this PR from the diffs.
> DOC-328: Make contact us occurrences consistent

- content/core-features/history.textile
Describe the order of messages retrieved by the History API.
* [DOC-202](https://ably.atlassian.net/browse/DOC-202).
Review the History topic, under Core Features
* [History](https://ably-docs-pr-1261.herokuapp.com/core-features/history/)
> Explain order of historical messages

- content/root/platform-customization.textile
Add new Platform Customization topic for Enterprise customers. This PR covers the following tickets:
* [DOC-548](https://ably.atlassian.net/browse/DOC-548)
* [DOC-502](https://ably.atlassian.net/browse/DOC-502)
See the new topic called "Platform Customization" under "Getting Started".
* [Platform customization](https://ably-docs-pr-1253.herokuapp.com/platform-customization/)
> Add Platform Customization topic for Enterprise customers

- content/control-api/curl-examples.textile
- content/control-api/index.textile
- content/control-api/testing-with-postman.textile
Change the development status of Control API from Beta to Preview.
* [DOC-566](https://ably.atlassian.net/browse/DOC-566).
* [Control API docs](https://ably-docs-pr-1270.herokuapp.com/control-api/)
> Change Control API from Beta to Preview

- content/core-features/authentication.textile
- content/core-features/versions/v1.0/authentication.textile
- content/core-features/versions/v1.1/authentication.textile
This PR removes references to HS384 from the documentation. See [JIRA](https://ably.atlassian.net/browse/DOC-568) for further information.
Check the diff or view the [authentication](https://ably-docs-pr-1272.herokuapp.com/core-features/authentication) page to review this PR.
> DOC-568: Remove reference to HS384

- content/general/firehose/kafka-rule.textile
- content/general/kafka-connector.textile
This PR adds a short overview page for the Kafka Connector. It will be updated when the Kafka Connector moves to GA status.
View the new page [here](https://ably-docs-pr-1275.herokuapp.com/general/kafka-connector) to review this PR.
> DOC-576: Kafka Connector overview

- config/jsbin_config.example.yaml
- content/code/website-examples/home-page.code
- data/jsbins.yaml
This work changes the following:
- Replaces `var` with `const` in code sample that users see when they finish the registration process.
- Adds comments about API key and channel name.
- Replaces the old Ably logo.
* [DEX-26](https://ably.atlassian.net/browse/DEX-26)
Existing Version:
Changed Version:
> [DEX-26] Modernize jsbin sample

- content/root/best-practice-guide.textile
This PR adds a short note to the best practice guide about app testing, encouraging users to create separate apps within their account for development, test and production.
See [JIRA](https://ably.atlassian.net/browse/DOC-404) for further information.
View the [best practice guide](https://ably-docs-pr-1278.herokuapp.com/best-practice-guide#testing-apps) to review this PR.
> DOC-404: Add section on app testing environments

- content/design-patterns/read-receipts.textile
This PR replaces the link to GitHub with the Glitch source code instead.
See [JIRA](https://ably.atlassian.net/browse/DOC-565) for information.
View the [read receipts](https://ably-docs-pr-1281.herokuapp.com/design-patterns/read-receipts/) page to review this PR.
> DOC-565: Replace GitHub link with Glitch source link

- content/code/realtime/channel-states.code
- data/jsbins.yaml
This PR fixes a broken JSBin for channel states. Previously the JSBin just return `undefined`. This PR also fixes the timestamps which were also broken.
See [JIRA](https://ably.atlassian.net/browse/DOC-488) for details.
Test the [new JSBin](https://jsbin.ably.com/onegoj/1/edit) to review this PR.
> DOC-488: Fix broken channel state JSBin

- content/core-features/authentication.textile
Minor fixes/additions to token revocation docs.
* [DOC-567](https://ably.atlassian.net/browse/DOC-567).
Check the diff and then this page. Also, please check links.
* [Page to review](https://ably-docs-pr-1283.herokuapp.com/core-features/authentication/)
> [DOC-567] - Minor fixes to token revocation docs

- content/tutorials/jwt-authentication.textile
Was originally planned to simply fix bug in TTL setting (too low). However, it was found the live demo was not working, and there were several issues with the tutorial that needed to be addressed.
* [DOC-562](https://ably.atlassian.net/browse/DOC-562).
**Must** be reviewed under web view, rather than Nanoc view. However, the Nanoc page to review is:
* [JWT tutorial](https://ably-docs-pr-1277.herokuapp.com/tutorials/jwt-authentication/)
> [DOC-562] - Rewrite tutorial

- content/general/events.textile
This PR updates the rule source descriptions to match those used in the Control API.
See [JIRA](https://ably.atlassian.net/browse/DOC-574) for further information.
View the [events pages](https://ably-docs-pr-1284.herokuapp.com/general/events#sources) to review this PR.
> DOC-574: Update rule source descriptions

- content/tutorials/peer-to-peer-vue.textile
- content/tutorials/vue-tictactoe.textile
https://ably.atlassian.net/browse/WEB-2134
Navigate to:
- /tutorials/vue-tictactoe#tutorial-step-18
- /tutorials/peer-to-peer-vue#tutorial-step-11
> Update 2x tutorials with internal links

- content/tutorials/channel-occupancy-events.textile
This PR updates the live demo source code link. Previously this was pointing to an earlier iteration of the tutorial.
See [JIRA](https://ably.atlassian.net/browse/DOC-512) for further information.
> DOC-512: Update live demo source code link

- content/general/limits.textile
This PR adds a note to business limits to add 'legacy' to them.
View the [limits page](https://ably-docs-pr-1295.herokuapp.com/general/limits/) to review.
> DOC-660: Add legacy note to business limits

- content/code/realtime/channel-deltas-size.code
- content/code/realtime/channel-deltas.code
- content/realtime/channels/channel-parameters/deltas.textile
- data/jsbins.yaml
Fix delta compression code samples.
* [DOC-582](https://ably.atlassian.net/browse/DOC-582).
Check the diff to see code changes.
The code in the try it out should work:
* [Try it out example](https://ably-docs-pr-1293.herokuapp.com/realtime/channels/channel-parameters/deltas/#using-deltas)
> DOC-582 - fix delta compression examples

- content/control-api/index.textile
* [Jira epic ticket](https://ably.atlassian.net/browse/DOC-609) - if applicable.
* [Jira ticket](https://ably.atlassian.net/browse/DOC-661).
Check new link in see also works(Manage apps with the Ably Control API GitHub Action).
* [Page to review](https://ably-docs-doc-661-add-c-1bbxtp.herokuapp.com/control-api/)
> Add Control API Blog link

- content/asset-tracking/index.textile
This PR fixes a minor type in the asset tracking documentation.
> DOC-516: Fix minor typo in asset tracking trackable description

- content/realtime/channels.textile
- content/rest/channels.textile
This PR adds the `release()` method for channels in both realtime and REST.
View the references for [realtime](https://ably-docs-doc-361-chann-mxpqrb.herokuapp.com/realtime/channels/#release) and [REST](https://ably-docs-doc-361-chann-mxpqrb.herokuapp.com/rest/channels/#release) to review this PR.
> DOC-361: Add channels release 

- content/tutorials/channel-rewind.textile
* [DOC Bugs](https://ably.atlassian.net/browse/DOC-608)
* [DOC-657](https://ably.atlassian.net/browse/DOC-657).
Check tutorial works and output page generates weather updates when selecting a location. Changes are only on Step 3.
* [Retrieving historical data with Channel Rewind](https://ably-docs-doc-657-chann-gdhlsq.herokuapp.com/tutorials/channel-rewind/)
> Doc 657 channel rewind reference error

- content/root/best-practice-guide.textile
* [Bugs](https://ably.atlassian.net/browse/DOC-608)
* [DOC-497](https://ably.atlassian.net/browse/DOC-497).
Check the new link for REST or Realtime goes to Docs and not FAQs.
* [Quickstart guide](https://ably-docs-doc-497-updat-tq1yhr.herokuapp.com/quick-start-guide/)
> Update rest or realtime links

- content/core-features/channels.textile
- content/realtime/channels.textile
- content/realtime/connection.textile
Adding clarification between channels and connections.
* [Quick Wins](https://ably.atlassian.net/browse/DOC-609).
* [Clarify difference between Connections and Channels](https://ably.atlassian.net/browse/DOC-264).
* [Core Features - Channels](https://ably-docs-doc-264-conne-r7iofz.herokuapp.com/core-features/channels/)
* [Realtime Channels](https://ably-docs-doc-264-conne-r7iofz.herokuapp.com/realtime/channels/)
* [Realtime Connection](https://ably-docs-doc-264-conne-r7iofz.herokuapp.com/realtime/connection/)
> Clarifying channels vs connections

- data/transform/pre-parser/erbjs/emojis.js
This is a minor code refactor so no Jira ticket (also, I'm new!)
There is no functional change, so as long as the reviewer is happy function has not been regressed (the tests work) then this should be OK.
> Refactored and made slightly clearer

- content/tutorials/web-rtc-data-channels.textile
- content/tutorials/web-rtc-file-transfer.textile
- content/tutorials/web-rtc-introduction.textile
- content/tutorials/web-rtc-screen-sharing.textile
- content/tutorials/web-rtc-video-calling.textile
> Added internal links to new WebRTC post

- .circleci/config.yml
- package.json
- src/components/blocks/headings/H1.js
- src/components/blocks/software/__snapshots__/Code.test.js.snap
- src/components/blocks/software/__snapshots__/Pre.test.js.snap
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
Adds Ably UI styles to the H1 element used on the docs site
> H1 ably UI styles

- .circleci/config.yml
- src/components/blocks/external-references/A.js
- src/components/blocks/external-references/__snapshots__/A.test.js.snap
I broke links. This fixes them by using props properly.
Before:
https://ably-docs-next-staging.herokuapp.com/documentation/realtime/connection
After:
http://localhost:8000/documentation/realtime/connection
> Edx 45 fix links

- src/components/blocks/complex-functionality/Button.js
This PR cleans up the button code. See commits :)
> [EDX-45] fix button

- src/components/blocks/list/Dl/index.js
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
- src/components/blocks/wrappers/__snapshots__/CopyLink.test.js.snap
* [Jira ticket](https://ably.atlassian.net/browse/EDX-89).
Before:
After:
> Edx 89 definition list display

- .circleci/config.yml
> Edx 94 add tests to circleci

- src/components/blocks/attribs.ts
- src/components/blocks/block.ts
- src/components/blocks/complex-functionality/Input.tsx
Not a merge to new-toolchain so not following formal rules here. This is for @MymmiJ
> I think this is the correct TS way

- gatsby-config.js
- graphql-types.ts
- package-lock.json
- package.json
Ensuring that the TS checks run when the app is run.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-104).
Observe:
> EDX-104: Adding a plugin for TypeScript checks

- src/components/attribs.ts
- src/components/blocks/complex-functionality/Input.tsx
A developer only change to easy Typescript migration
https://ably.atlassian.net/browse/EDX-106
> Common attribs type (TS non visible change)

- package-lock.json
- package.json
- src/components/Button/LanguageButton.tsx
- src/components/Link/LanguageLink.tsx
- src/components/common/language-defaults.ts
- src/maps/language.tsx
> [EDX-105] - no tailwind purge add Typescript

- content/api/rest-sdk/statistics.textile
- content/api/versions/v0.8/rest-sdk/statistics.textile
- content/api/versions/v1.0/rest-sdk/statistics.textile
- content/api/versions/v1.1/rest-sdk/statistics.textile
- content/client-lib-development-guide/documentation-formatting-guide.textile
- content/partials/types/_stats_granularity.textile
- content/partials/versions/v0.8/types/_stats_granularity.textile
- content/partials/versions/v1.0/types/_stats_granularity.textile
- content/partials/versions/v1.1/types/_stats_granularity.textile
- content/rest/statistics.textile
- content/rest/versions/v0.8/statistics.textile
- content/rest/versions/v1.0/statistics.textile
- content/rest/versions/v1.1/statistics.textile
* [EDX-54](https://ably.atlassian.net/browse/EDX-54).
* [EDX-72](https://ably.atlassian.net/browse/EDX-72).
* [Statistics concept](http://ably-docs-edx-72-move-r-nps9wy.herokuapp.com/rest/statistics/)
* [Statistics API](http://ably-docs-edx-72-move-r-nps9wy.herokuapp.com/api/rest-sdk/statistics/)
> [EDX-72] Move REST API stats

- src/components/Article/index.tsx
A small missing class to help with:
[EDX-91](https://ably.atlassian.net/browse/EDX-91)
> [EDX-91] - added dropped class

- src/components/Sidebar/index.tsx
Made the sidebar title compulsory because we always want one (for now)
> Made title compulsory

- content/api/index.textile
* [EDX-110](https://ably.atlassian.net/browse/EDX-110).
* [EDX-114](https://ably.atlassian.net/browse/EDX-114).
Test locally. Note Control API Ref link will not work, as I've not merged api-ref into this branch.
> [EDX-114] Update API overview

- content/api/versions/v1.1/realtime-sdk/channels.textile
- content/design-patterns/read-receipts.textile
- content/partials/versions/v1.1/shared/_channel_enumeration.textile
- content/realtime/presence.textile
- content/realtime/versions/v1.0/presence.textile
- content/root/platform-customization.textile
This PR fixes any broken links identified by `nanoc ilinks` after the migration of API references.
See [EDX-117](https://ably.atlassian.net/browse/EDX-117) for further info.
> [EDX-117]: Check internal links using nanoc ilinks

- content/client-lib-development-guide/features.textile
Adds the batch operations spec to the Realtime IDL as per [this comment](https://github.com/ably/docs/pull/1421#issuecomment-1126184209)
> Add batch operations to realtime

- content/api/index.textile
This PR adds links to each paragraph in the API overview page for ease of navigating to the relevant APIs.
See [JIRA](https://ably.atlassian.net/browse/EDX-145) for further information.
View the API overview page to review.
> [EDX-145] Add links to API overview page

- src/components/blocks/list/Ul.js
- src/styles/global.css
Making in-body unordered lists show with bullet points, as they are intended to.
Also:
Ensure font-weight is consistent across in body text elements
* [Jira ticket](https://ably.atlassian.net/browse/EDX-152).
Ensure bullet points look nice:
* [Page to review](http://localhost:8000/docs/quick-start-guide)
> A nice simple fix for showing unordered lists

- content/tutorials/demo-ably-airtable-starter-kit.textile
- content/tutorials/demo-ably-rock-paper-scissors.textile
- content/tutorials/demo-agile-flush-vue-app.textile
- content/tutorials/demo-decorate-a-tree-2020.textile
- content/tutorials/demo-depict-it.textile
- content/tutorials/demo-fully-featured-scalable-chat-app.textile
- content/tutorials/demo-jamstack-sync-stream-video.textile
- content/tutorials/demo-led-matrix-jumper.textile
- content/tutorials/demo-live-caption-demo.textile
- content/tutorials/demo-multiplayer-games-scalable-networking-framework.textile
- content/tutorials/demo-nextjs-chat-app.textile
- content/tutorials/demo-realtime-midi-player.textile
- content/tutorials/demo-realtime-multiplayer-space-invaders.textile
- content/tutorials/demo-realtime-quiz-framework.textile
- content/tutorials/demo-whiteboard.textile
WIP for  https://ably.atlassian.net/browse/WEB-2367
> [WEB-2367] Demo cards in the tutorial

- content/general/integrations.textile
This PR adds an overview page to the integrations section.
See [JIRA](https://ably.atlassian.net/browse/EDX-142) for further information. 
View the new integrations overview to review this PR.
> [EDX-142] Add an overview to integrations

- content/general/integrations.textile
[CRITICAL BUG] - due to a bug in the metadata, this topic does not render under website view.
* [EDU-818](https://ably.atlassian.net/browse/EDU-818).
`/general/integrations` must be checked under the webview.
> [EDU818] - Fix bug in metadata

- content/general/limits.textile
First ticket in improving documentation on Limits. This ticket addresses one common issue about the warning messages being sent to users not being easy to map to the sections in the documentation. Added warning sections to the end of the relevant sections of the Limits page to help alleviate this. Choose to keep the headers in the 'friendly' tone to make the page more digestiable but put the actual response sense so it's searchable in docs/on the page. 
* [Improve descriptions and examples around limits](https://ably.atlassian.net/browse/EDU-789)
* [Update limit names to match realtime and admin](https://ably.atlassian.net/browse/EDU-728) …
> [EDU-728] - Limits clarification

- static/scripts/api-streamer/examples.js
- static/scripts/quick-start-guide.js
- static/scripts/tutorials/channel-enumeration-rest.js
- static/scripts/tutorials/channel-lifecycle-events.js
- static/scripts/tutorials/channel-occupancy-events.js
- static/scripts/tutorials/encryption.js
- static/scripts/tutorials/history.js
- static/scripts/tutorials/jwt-authentication.js
- static/scripts/tutorials/newsfeed-react.js
- static/scripts/tutorials/presence.js
- static/scripts/tutorials/publish-subscribe.js
- static/scripts/tutorials/web-rtc-data-channels.js
- static/scripts/tutorials/web-rtc-file-transfer.js
- static/scripts/tutorials/web-rtc-screen-sharing.js
- static/scripts/tutorials/web-rtc-video-calling.js
Moving scripts from inline <script> tags in textile into their own files and preparing them for execution.
The next step is, during node creation, to check if there exists a valid static JS file for a given slug and, if there is such a file, to load it as an asset using the static asset URL.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-177).
> [EDX-177] Extract script tags

- graphql-types.ts
- src/components/Sidebar/SidebarLinkMenu.js
Fixes build error based on missing server side window in Gatsby.
> Fix new toolchain build error

- content/core-features/authentication.textile
Remove references to Token Revocation being in beta.
* [DEP-97 - Token Revocation out of beta](https://ably.atlassian.net/browse/DEP-97).
Check for references to Token Revocation being in beta.
* [Authentication](https://ably-docs-dep-97-token--yj6cmo.herokuapp.com/core-features/authentication/#token-revocation)
> [DEP-97] - Remove references to token revocation being in beta

- content/general/limits.textile
This PR adds some clarifications around limit notifications.
* [EDU-789](https://ably.atlassian.net/browse/EDU-789)
* [EDU-728](https://ably.atlassian.net/browse/EDU-728).
* [Limits page](https://ably-docs-edu-728-fix-l-rxi6u8.herokuapp.com/general/limits/)
> [EDU-728] - Limit notification clarifications

- content/tutorials/publish-subscribe.textile
Update the JS version of this tutorial so that:
- It has all the steps necessary for a reader to create a working version.
- Uses ES6 syntax.
- Points to the solution code in its own dedicated repo.
Full details in the ticket:
* [EDU-825](https://ably.atlassian.net/browse/EDU-825).
- Ensure that the tutorial renders correctly in the website
- Complete the tutorial and verify that all the steps are correct and present
Page to review (in the test live deployment below):
- /tutorials/publish-subscribe
> [EDU-825] - Update JS version of tutorial

- data/yaml/page-furniture/sidebar.yaml
Updated Table of Contents to match latest live Table of Contents.
* [EDX-153 - Update ToC](https://ably.atlassian.net/browse/EDX-153).
Run locally new toolchain locally and check links work in the side nav table of contents and that it's rendering correctly.
> [EDX-153] - Update ToC in new toolchain

- content/tutorials/_nest-realtime-app.textile
- content/tutorials/demo-nextjs-chat-app.textile
Update link for the next js tutorial
https://ably.atlassian.net/browse/WEB-2491
1. Instructions on how to review the PR. 
2. Navigate to `/tutorials`
3. Select Next.js from the filter
4. The article link should to redirect to https://ably.com/blog/realtime-chat-app-nextjs-vercel
> [WEB2491] Update next js tutorial link

- content/partials/types/_push_channel_subscription.textile
- content/partials/versions/v1.0/types/_push_channel_subscription.textile
- content/partials/versions/v1.1/types/_push_channel_subscription.textile
Updating formatting on methods so they're highlighted.
* [EDU-908 - method formatting](https://ably.atlassian.net/browse/EDU-908).
Check the methods on formatting correctly on the push page for API.
* [API - Push](https://ably-docs-edu-908-metho-t86yiq.herokuapp.com/api/realtime-sdk/push/)
> correct method formatting

- content/core-features/authentication.textile
Corrects the error handling code in the two code samples:
* [EDU-853](https://ably.atlassian.net/browse/EDU-853).
Check the two code samples, ideally under web view.
* [Token revoc code](https://ably-docs-edu-853-fix-c-9gp7ti.herokuapp.com/core-features/authentication/#token-revocation)
Note under web view keys are populated automatically.
> [EDU-853] - Correct token revoc error handling code

- src/components/Header/TopMainNav/Dropdown/Button/api-references.ts
This PR updates the copy for the API Reference navigation dropdown in the new toolchain.
> [EDX-220] Update copy for API reference navigation

- content/general/limits.textile
This PR raises the free-tier limits. The changes are based on the following:
* https://github.com/ably/website/blob/main/data/models/packages.yml
* Confluence page: https://ably.atlassian.net/wiki/spaces/DEVX/pages/2259616020/New+free+tier+limits
Jira tickets:
* Epic: [EDU-911](https://ably.atlassian.net/browse/EDU-911)
* [EDU-910](https://ably.atlassian.net/browse/EDU-910)
Check the limits page and the diff.
* [Limits page](https://ably-docs-edu-910-updat-44h24a.herokuapp.com/general/limits/)
> [EDU-910] - Update free tier limits

- .slug-post-clean
- .slugignore
Reduce the size of the docs slug and deploy successfully to Heroku
* [Jira ticket](https://ably.atlassian.net/browse/EDX-257).
Ensure that docs deploys successfully and retains all assets.
> [EDX-257] Fix deploy to Heroku

- .eslintrc.json
- package-lock.json
Fixed the ESLint settings and made the package lock be not totally wrong
> Updated package-lock and changed es-lint settings back

- src/components/Header/TopMainNav/Dropdown/Button/resource-data.ts
This PR updates the text in the resources dropdown menu.
See [JIRA](https://ably.atlassian.net/browse/EDX-228) for further information.
Use the header navigation on any page and check the resources tab.
> [EDX-228] Update resource dropdown text

- content/tutorials/aws-persistence.textile
Update AWS Persistence tutorial with outstanding feedback from [historic PR](https://github.com/ably/docs/pull/1437).
Tutorial code has also been moved from the old [separate repo](https://github.com/ably/ably-messages-s3-tutorial) to the main [tutorial repo](https://github.com/ably/tutorials/tree/aws-persistence) and links updated accordingly.
Note, the comment about image has been excluded and moved to a [new ticket](https://ably.atlassian.net/browse/EDU-983).
* [Content Debt](https://ably.atlassian.net/browse/EDU-611).
* [Create flow diagram for AWS Persistence tutorial](https://ably.atlassian.net/browse/EDU-880).
Cross check file diff with …
> [EDU-880] - implement aws feedback

- README.md
- data/createPages/index.js
- data/transform/front-matter.ts
- data/transform/index.js
- gatsby-config.ts
- gatsby-node.ts
- graphql-types.ts
- package-lock.json
- package.json
- src/templates/document.js
* [Jira ticket](https://ably.atlassian.net/browse/EDX-134).
View /docs/realtime/channel-params, ensure it redirects to /docs/realtime/channels/channel-parameters/overview
Ensure that the existing query parameters such as languages etc. are carried over correctly.
> [EDX-134] Redirect Functionality

- content/general/queues.textile
Check link to traditional message queueing pattern description works.
* [Bugs](https://ably.atlassian.net/browse/EDU-608).
* [Broken link on queues page](https://ably.atlassian.net/browse/EDU-510).
Check link in first paragraph of https://ably.com/docs/general/queues#what works and points to the correct page. 
* [Queues - What are Ably Queues?](http://ably-docs-edu-510-broke-hxnixg.herokuapp.com/general/queues/#what)
> [EDU-510] - Fix soa patterns link

- content/general/queues.textile
Correct typo in queues documentation.
* [Bugs](https://ably.atlassian.net/browse/EDU-608).
* [Typo in queue docs](https://ably.atlassian.net/browse/EDU-861).
Check file dif/preview.
* [Queues](https://ably-docs-edu-861-queue-6f4yqw.herokuapp.com/general/queues/)
> [EDU-861] - Queues typo correction

- content/asset-tracking/index.textile
- content/asset-tracking/using-the-sdks.textile
Update the "Using the SDKs" topic. This PR deals with Publishing SDK section, as per this ticket:
* [EDU-903](https://ably.atlassian.net/browse/EDU-903).
Won't display with correct formatting under nanoc - need webview:
* [Using the SDKs](https://ably-docs-edu-903-using-gllwyh.herokuapp.com/asset-tracking/using-the-sdks/)
> [EDU-903] - Update initializing the publisher and tracking docs

- graphql-types.ts
- package.json
- src/components/Article/ArticleFooter.tsx
- src/components/Article/InArticleBanner/InArticleBanner.tsx
- src/components/Article/InArticleBanner/InArticleBannerCopy.tsx
- src/components/Article/InArticleBanner/InArticleOptions.tsx
- src/components/Article/InArticleBanner/index.ts
- src/components/Article/index.tsx
Adding a footer/pre-footer to the end of every documentation page to look like the 'Need help?' section at the bottom of this Figma file:
https://www.figma.com/file/vyr9ZPZ15eUWtCKSEktdEL/Docs-v1?node-id=525%3A13270
* [Jira ticket](https://ably.atlassian.net/browse/EDX-262).
Check the `README.md` for instructions on getting started with the repository, ping me (@MymmiJ ) if you have any questions or difficulties getting the repository running.
Check the bottom of a few pages locally to see if the page appears. Make sure that the code is up to standard.
* [Example page - quickstart guide](http://localhost:8000/docs/quick-start-guide?lang=objc)
> [EDX-262] "Need Help?" section

- README.md
- package-lock.json
- src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.tsx
- src/components/Sidebar/styles.js
* Prevents unwanted interaction between TopMainNav and Top Language Navigation menus, allowing menus to expand properly
* Fixes indentation issue with some sidebar items
* Adds extra instructions to README after feedback from users
On any page:
Ensure dropdown menu items open correctly.
Make sure that nested sidebar items at the same level are visually in line.
[Contrast current version](https://ably-docs-next-staging.herokuapp.com/docs/quick-start-guide?lang=swift)
> [Fix] - Style tweaks

- Procfile
- app.json
- config/nginx.conf.erb
Switch to the nginx buildpack and ensure we serve up `X-Frame-Options` headers to prevent docs from being embedded into iframes.
* [WEB-2519](https://ably.atlassian.net/browse/WEB-2519).
The review app should work as normal with no visible changes to the user. Embedding docs in an iframe should not be possible anymore.
> [WEB-2519] Prevent iframe embedding

- content/general/limits.textile
This PR fixes an incorrect value in an example used within the limits page. See [JIRA](https://ably.atlassian.net/browse/EDU-1008) for full details.
View the limits page to review this PR.
> [EDU-1008]: Fix incorrect limit value in example

- data/createPages/constants.ts
- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
Adds a default language selector label if default is set.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-272).
> [EDX-272] Global language selector default label

- content/general/aws-authentication.textile
- content/partials/general/events/_non_enveloped_event_headers.textile
Check links point to the IDs and Keys page correctly.
* [Quick Wins](https://ably.atlassian.net/browse/EDU-609) - if applicable.
* [Replace links to outdated FAQ article with links to new topic](https://ably.atlassian.net/browse/EDU-1018).
Check links point to the IDs and Keys page correctly.
* [AWS Authentication](https://ably-docs-edu-1018-app--5oawuy.herokuapp.com/general/aws-authentication/)
* [Webhooks - Non-enveloped event payloads - uses the partial](https://ably-docs-edu-1018-app--5oawuy.herokuapp.com/general/webhooks/)
> [EDU-1018] - faq link removal

- content/root/best-practice-guide.textile
Merged two entries in the best practice guide that were basically making the same point, and rewrote them to make that point clearer.
> Best practice guide: merge two presence points and clarify

- content/api/index.textile
This PR adds links to the auto-generated API references to the API overview page.
See [JIRA](https://ably.atlassian.net/browse/EDX-237) for further information.
> [EDX-237]: Add info about auto-generated API references

- content/asset-tracking/using-the-sdks.textile
Adds location animator section to docs for Android.
* [EDU-904](https://ably.atlassian.net/browse/EDU-904)
* [Location animator](https://ably-docs-edu-904-add-l-jhqoec.herokuapp.com/asset-tracking/using-the-sdks/#location-animator)
> [EDU-904] - Add location animator section

- src/components/Menu/TopCodeMenu.tsx
- src/components/StaticQuerySidebar/AblySidebarIconContainer.tsx
- src/components/StaticQuerySidebar/LeftSidebarContainer.tsx
Fixing left sidebar and top language switch nav
* [Jira ticket](https://ably.atlassian.net/browse/EDX-311).
Left sidebar and language switch nav should work fine now on larger (`2xl`) screens
* [Page to review](/docs/api/realtime-sdk/connection?lang=go)
> [EDX-311] Fix language menu, sidebar menu display

- content/tutorials/how-to-ably-react-hooks.textile
A how-to guide, showing how to work with Ably React Hooks.
* [EDU-899](https://ably.atlassian.net/browse/EDU-899).
* Please review the `/tutorials/how-to-ably-react-hooks` page in web view.
> [EDU-899] - Create Ably React Hooks how-to guide

- src/components/ButtonWithTooltip/ButtonWithTooltip.module.css
Color variables has changed, hence background was missing
* [Jira ticket](https://ably.atlassian.net/browse/EDX-323).
Just hover over a code copy button in any code block, you should have "Copy" and "Copied!" tooltips.
> [EDX-323] Fix missing background

- src/components/blocks/headings/H5.tsx
Fixes the font family for h5
* [Jira ticket](https://ably.atlassian.net/browse/EDX-359).
`/docs/key-concepts?lang=nodejs#client-identity`
> [EDX-359] H5 titles have an odd font face

- src/components/Sidebar/RightSidebar/RightSidebar.tsx
Hides right sidebar when have no menu items
* [Jira ticket](https://ably.atlassian.net/browse/EDX-315).
Pub/sub page have no right sidebar
> [EDX-315] Don't show Right Sidebar when the content menu is empty

- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/maps/language.tsx
Language Dropdown labels for JS and C# updated
* [Jira ticket](https://ably.atlassian.net/browse/EDX-324).
> [EDX-324]: Update the labels in the language selector to be in the correct format 

- src/components/blocks/headings/H4.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-358).
> [EDX-358] Odd spacing after the level 3 title (i.e. 1.1 (a) level

- content/tutorials/token-authentication.textile
Update JS example to ES6 syntax. I haven't used promises here because the operations that this tutorial uses doesn't warrant them. I've tried to avoid changing verbiage associated with non-JS languages unless I deemed it absolutely necessary (e.g. the overview/intro)
* [EDU-1023](https://ably.atlassian.net/browse/EDU-1023).
* Please review `/tutorials/token-authentication` in the website view.
> [EDU-1023] Update JS Version of Token Authentication tutorial

- content/root/quick-start-guide.textile
Minor change. You don't need to specify promises interface in the require statement.
Check the diff.
> [EDU-1150] - Minor change to require

- content/root/glossary.textile
* [Quick Wins](https://ably.atlassian.net/browse/EDU-609).
* [Add ATM (Active Traffic Management) to Glossary](https://ably.atlassian.net/browse/EDU-887).
Check ATM (Active Traffic Management) has been added to the glossary:
* [Glossary](https://ably-docs-edu-887-add-a-26vx37.herokuapp.com/glossary/)
> [EDU-887] Add ATM to glossary

- content/realtime/usage.textile
Just updates to JS/Node code. Also added section showing how to use Promise interface.
* [EDU-913](https://ably.atlassian.net/browse/EDU-913).
Check for JS and Node:
* [Realtime usage](https://ably-docs-edu-913-realt-ltgnwv.herokuapp.com/realtime/usage/)
> [EDU-913] - Update JS/Node code

- src/components/Header/TopMainNav/SearchBar/SuggestionBox.module.css
- src/components/Header/TopMainNav/SearchBar/SuggestionBox.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-378).
> [EDX-378] Search box scrolls past the results 

- src/components/Article/ArticleFooter.tsx
- src/components/Article/InArticleBanner/InArticleOptions.tsx
- src/components/GlobalLoading/GlobalLoading.tsx
- src/components/blocks/software/Code/CodeCopyButton.tsx
- src/components/blocks/software/Code/index.tsx
- src/third-party/gtm/gtm.ts
* [Jira ticket](https://ably.atlassian.net/browse/EDX-138).
Check GTM Workspace Docs UI Tracking: https://tagmanager.google.com/#/container/accounts/2078178087/containers/7986506/workspaces/111
Preview workspace using localhost:8000 (assuming gatsby dev is running).
Make sure that when clicking a code button, the support button, or contact us button at the bottom of the page an appropriate event is fired.
> [EDX-138] GTM UI interaction metrics

- package-lock.json
- src/components/Header/TopMainNav/SearchBar/SuggestionBox.module.css
- src/components/blocks/headings/H4.tsx
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
h4s have a text-transform uppercase (in ui-text-h4) which is removed by this PR - the transform is not appropriate for docs, as case can matter.
Also fixes an error in SuggestionBox.module.css with a comment that webpack doesn't understand.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-376).
> [EDX-376] uncapitalize h4s

- src/components/Sidebar/SidebarHeading.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-383).
A good example page would be kafka connector - check that the link in the left sidebar is scrolled into view:
[Kafka Connector page](http://localhost:8000/docs/general/kafka-connector?lang=objc)
> [EDX-383] Left Sidenav scrolls selected page into view

- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
Don't show the Default language button any more please.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-381).
* [Page to review](http://localhost:8000/docs/quick-start-guide?lang=nodejs)
> [EDX-381] Code Snippet no default option

- src/components/blocks/software/Pre.test.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
* [EDX-293](https://ably.atlassian.net/browse/EDX-293?atlOrigin=eyJpIjoiOWM2ODBhZTNlYWVkNGUwNmJmZjlkYTA2NDQ3NzUxMWYiLCJwIjoiaiJ9)
/docs/rest-api?lang=csharp#pagination
> [EDX-293] Preformatted text without a <code> element child should render[E

- content/realtime/connection.textile
Updates JS and Node versions of connection code.
* [EDU-914](https://ably.atlassian.net/browse/EDU-914).
Check JS and Node code on this page:
* [Connection](https://ably-docs-2-edu-914-upd-2maarq.herokuapp.com/realtime/connection/)
> [EDU-914] - Update realtime connection code

- src/components/blocks/software/Code/index.tsx
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
* [EDX-379](https://ably.atlassian.net/browse/EDX-379?atlOrigin=eyJpIjoiZTBkMmY3NGE5OWMyNDU0NmE2Yjk4ZjVlNmUwZGNiNWYiLCJwIjoiaiJ9)
* /docs/quick-start-guide?lang=nodejs
> [EDX-379] API Key in code snippets should limit to 5 *

- src/maps/language.tsx
[EDX-365](https://ably.atlassian.net/browse/EDX-365?atlOrigin=eyJpIjoiYWYwYjQ2N2Y2ZTQyNDUzOGE4M2NiMzE2Yjc4YmYyMGMiLCJwIjoiaiJ9)
* Can check it here - /docs/quick-start-guide?lang=objc
> [EDX-365] -  Objective C should be Objective-C 

- data/transform/pre-parser/textile-js-workarounds/add-italicised-text.test.ts
- data/transform/pre-parser/textile-js-workarounds/add-italicised-text.ts
- src/components/blocks/list/Dl/index.tsx
- src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.test.js
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
Adds 'default' values to definition lists.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-305).
* [Page to review](http://localhost:8000/docs/api/rest-api?lang=javascript)
> [EDX-305] Support default values in definition lists

- content/core-features/authentication.textile
[EDX-364](https://ably.atlassian.net/browse/EDX-364?atlOrigin=eyJpIjoiOGJiZGVjMTI0NjZkNDdlNTg3ODc4NmVkZGU3Y2EyNDIiLCJwIjoiaiJ9)
* docs/core-features/authentication?lang=objc
> [EDX-364] - Adding the missing Auth and Security page

- src/components/LanguageButton/LanguageButton.module.css
- src/components/LanguageButton/LanguageButton.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.module.css
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.module.css
- src/components/Menu/MenuItemButton/MenuItemButton.test.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
Whenever we don't have a language to show, the language should be selectable locally; not globally. Also, the select button should work when selecting languages locally.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-385).
* [Page to review](http://localhost:8000/docs/realtime/connection?lang=flutter)
> [EDX-385 code sample local language select

- src/components/Menu/ReactSelectStyles/control-styles.ts
* [Jira ticket](https://ably.atlassian.net/browse/EDX-390).
On any page, verify that the cursor now takes on the pointer form.
> [EDX-390] cursor pointer lang select

- content/general/push/activate-subscribe.textile
- content/general/push/admin.textile
- content/general/push/publish.textile
This PR adds line spacing between codeblocks so that they can be easily parsed in the new toolchain.
See [JIRA](https://ably.atlassian.net/browse/EDX-408) for further information.
Ensure the codeblocks are still rendered correctly.
> [EDX-408] Add line spacing between consecutive code blocks

- src/components/Article/index.tsx
- src/components/Layout/Layout.tsx
* [EDX-373](https://ably.atlassian.net/browse/EDX-373?atlOrigin=eyJpIjoiYjkyOWI4NTExNzYyNDExODkyNzk2N2UxYjc1ZmM3MjkiLCJwIjoiaiJ9)
* /docs/quick-start-guide?lang=nodejs#step-3
* open the page and open your screen in 1200px, 2500px width
> [EDX-373] - 2XL update Grid for the main as per design

- content/asset-tracking/index.textile
* [EDU-1159](https://ably.atlassian.net/browse/EDU-1159)
Check link to SDK reference docs and link text:
* [Asset Tracking Intro](https://ably-docs-edu-1159-aat--w6iwo4.herokuapp.com/asset-tracking/#see-also)
> [EDU-1159] - Updated link text to specify Android

- data/yaml/page-furniture/sidebar.yaml
This PR removes the sections from the table of contents that are represented in the header navigation.
> [EDX-409] Update the table of contents

- src/templates/base-template.tsx
- src/templates/template-data.d.ts
* [EDX-361](https://ably.atlassian.net/browse/EDX-361?atlOrigin=eyJpIjoiOGZmZWU2ZjFlODY0NDY3ZmFmMzU1N2QwZjMzZjIyNDIiLCJwIjoiaiJ9)
* [docs/core-features/presence?lang=nodejs](https://ably-docs-next-staging.herokuapp.com/docs/core-features/presence?lang=nodejs)
* Open the page the lang parameter should not be visible when opened
* Also try to add hash in the paramter
> [EDX-361] - lang parameter should not be added in the no-filter-lang page

- content/api/realtime-sdk/channels.textile
This PR fixes a block of text that contained too many spans.
See [JIRA](https://ably.atlassian.net/browse/EDX-380) for further information.
Ensure the block renders correctly for all languages.
> [EDX-380] Update block with too many spans

- src/components/Sidebar/RightSidebar/RightSidebar.module.css
* [EDX-388](https://ably.atlassian.net/browse/EDX-388?atlOrigin=eyJpIjoiNzU5Y2Q3ZDZmNDA5NDFlODg2NmZmMzVlY2NlYmY4Y2YiLCJwIjoiaiJ9)
* [/docs/core-features/channels?lang=swift](https://ably-docs-next-staging.herokuapp.com/docs/core-features/channels?lang=swift)
* Scroll down and up it should not move
> [EDX-388] - RS Nav should be fixed when scroll for no lang selector page

- src/components/LanguageButton/LanguageButton.test.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
- src/maps/language.tsx
* [EDX-354](https://ably.atlassian.net/browse/EDX-354?atlOrigin=eyJpIjoiNjUxZjU0MDA0NGM5NDljZjk1YWQ3OTNiZDMzZmYwYjYiLCJwIjoiaiJ9)
* docs/quick-start-guide?lang=javascript
* JS and csharp should be correct now
> [EDX-354]  - Rename JS and csharp label globally

- src/components/blocks/software/Code/extract-code-strings-from-content.test.ts
- src/components/blocks/software/Code/extract-code-strings-from-content.ts
- src/components/blocks/software/Code/index.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
* [Jira ticket](https://ably.atlassian.net/browse/EDX-389).
* Also, refactors LocalLanguageAlternatives so as to not rely on {children}
* Also, avoids bug with useMemo when switching content
Especially check Quickstart guide and check local language functionality with PHP as global lang.
> [EDX-389] Fix multiline code content display

- src/components/blocks/table/Table.module.css
* [Jira ticket](https://ably.atlassian.net/browse/EDX-454).
> [EDX-454] Prevent tables from having a max height

- src/components/HorizontalMenu/HorizontalMenu.test.tsx
- src/components/HorizontalMenu/HorizontalMenu.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.module.css
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
* [EDX 382](https://ably.atlassian.net/browse/EDX-382?atlOrigin=eyJpIjoiMmNlY2U5YWQwN2FjNGI5Nzk3MTM4MjljNDY1NmZlNTciLCJwIjoiaiJ9)
* docs/quick-start-guide
* copy button should not overlapped with different code snippet and try with different screen sizes
> [EDX 382] -  Local Language screen views should not overlap

- src/components/Sidebar/RightSidebar/RightSidebar.tsx
- src/components/Sidebar/SidebarHeading.tsx
…ndented child sections are more obvious also
* [Jira ticket](https://ably.atlassian.net/browse/EDX-465).
> [EDX-465] sidebar fixes

- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/HorizontalMenu/HorizontalMenu.test.tsx
- src/components/HorizontalMenu/HorizontalMenu.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
There is styling issue with Search bar because of the changes done for [EDX-354](https://ably.atlassian.net/browse/EDX-354?atlOrigin=eyJpIjoiZjM1NDY1YmU4YTYwNDRiZjgyMTk1MjAzN2Q4OGVjZDMiLCJwIjoiaiJ9)  to solve this add the overflow-x-auto as variant instead
* docs/quick-start-guide?lang=csharp&q=Kaf
* make sure the code snippet and the top main nav, and top code menu are same design as figma
> [EDX-354] - Add variant for scrollX to avoid conflict

- src/components/Sidebar/Sidebar.module.css
* [EDX-493](https://ably.atlassian.net/browse/EDX-493?atlOrigin=eyJpIjoiNGE0M2NlNTAzZGU0NGFjMzk3YjgzMjNlOGFjMTQxNWUiLCJwIjoiaiJ9)
This solves the issue from removing the Ably logo on the Left Sidebar
* [/docs/core-features/occupancy
* docs/quick-start-guide?lang=python
* Check both no language selection and page that have language selection, You should be able to see the Getting started item  in the navigations
> [EDX-493] -Update the height of Left Sidebar

- content/realtime/authentication.textile
- content/rest/authentication.textile
Original ticket was to correct links, however they've been previously fixed, I checked throughout the docs and couldn't find any not working so just added some clarification about ClientOptions and AuthOptions as suggested in the ticket.
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-608)
* [Jira ticket](https://ably.atlassian.net/browse/EDU-724)
Check the wording of the changes and that the new links work.
* [Realtime]()
* [REST]()
> [EDU-724] - clarify AuthOptions

- data/yaml/page-furniture/apiSidebar.yaml
- src/components/Header/TopMainNav/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarRenderer.tsx
- src/components/Header/TopMainNav/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/add-adhoc-sidebar-items.ts
- src/components/Header/TopMainNav/HamburgerMenu/HamburgerMenu.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/StaticQuerySidebar/LeftSideBar.tsx
- src/components/StaticQuerySidebar/SidebarDataRetrieval.tsx
- src/contexts/article-type-context.ts
* [EDX-456](https://ably.atlassian.net/browse/EDX-456?atlOrigin=eyJpIjoiMzE4MjdhOTdkZjFkNDcyNDlhMmI0ZjI0NDM5MDE3ZmUiLCJwIjoiaiJ9)
* docs/api/rest-api
> [EDX-456] - API Refs  pages own sidebar items

- data/transform/pre-parser/textile-js-workarounds/fix-links.ts
- data/transform/pre-parser/textile-js-workarounds/index.ts
- src/components/HorizontalMenu/HorizontalMenu.test.tsx
- src/components/blocks/external-references/A.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.js.snap
Stops pages breaking if any elements have a style applied.
Fixes links if they have punctuation.
> [Bugfix] ahrefs

- gatsby-browser.ts
Change the should scroll condition on page change
* [Jira ticket](https://ably.atlassian.net/browse/EDX-466).
> [EDX-466] Page heading cut off on page load

- __fixtures__/addsearchMock.json
- src/components/Header/TopMainNav/SearchBar/SearchBar.tsx
- src/components/Header/TopMainNav/SearchBar/SuggestionBox.tsx
- src/hooks/use-key-press.ts
Fixing search issues
* [Jira ticket](https://ably.atlassian.net/browse/EDX-485).
> [EDX-485] Search results don't match the specs

- data/createPages/createContentMenuDataFromPage.js
- src/components/Menu/MenuItemButton/MenuItemButton.module.css
- src/components/blocks/api-reference/headings/ApiReferenceH6.tsx
- src/components/blocks/wrappers/CopyLink.module.css
* [EDX-490](https://ably.atlassian.net/browse/EDX-490?atlOrigin=eyJpIjoiZmFhNTNlYjFjNGQ1NDc1OWIzYWE5Yzg0NjczMjBmOTciLCJwIjoiaiJ9)
* [EDX-461](https://ably.atlassian.net/browse/EDX-461?atlOrigin=eyJpIjoiZDkyNWNhNGYwY2JkNDgyMzlhM2FjZjVlZjUwYmMwOTQiLCJwIjoiaiJ9)
- https://ably-docs-2-edx-461-hxzn0rvy50.herokuapp.com/docs/api/realtime-sdk#connection
--  should have the new copy link and appear in the RHS
- https://ably-docs-2-edx-461-hxzn0rvy50.herokuapp.com/docs/api/rest-api
-- the H6 should not have Copy Link and not appear in the RHS
> [EDX-461,EDX-490] - Methods and properties in API Ref pages should have Copy Link and appear in the RHS nav

- src/components/blocks/typography/P/Tip.tsx
* [EDX-520](https://ably.atlassian.net/browse/EDX-520?atlOrigin=eyJpIjoiMjQxZDUwMDgyYjg5NGU2MDhjMGQ4N2U3OTU2MTY0NjIiLCJwIjoiaiJ9)
* docs/realtime/statistics?lang=javascript
> [EDX-520] - The tip element should be full body width

- src/components/Article/ArticleFooter.tsx
* [EDX-517](https://ably.atlassian.net/browse/EDX-517?atlOrigin=eyJpIjoiZWM5MWY5ZDQwMjQ2NDI2OGJiMDNiMDg1YWUyZWViOTEiLCJwIjoiaiJ9)
* all pages
> [EDX-517] - Need Help box fix issues

- src/components/Sidebar/SidebarHeading.test.tsx
- src/components/Sidebar/SidebarHeading.tsx
- src/components/Sidebar/SidebarLinkMenu.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-475).
> [EDX-475] UI cleanup - Expandable sections in the side menu shouldn't be bold

- data/transform/pre-parser/textile-js-workarounds/fix-links.test.ts
- data/transform/pre-parser/textile-js-workarounds/fix-links.ts
- data/transform/pre-parser/textile-js-workarounds/index.ts
- src/components/blocks/external-references/A.tsx
Beautiful regex to solve a full stop problem...
* [Jira ticket](https://ably.atlassian.net/browse/EDX-516).
Check
http://localhost:8000/docs/api/rest-sdk?lang=javascript ('Token' link) vs. https://ably-docs-next-staging.herokuapp.com/docs/api/rest-sdk?lang=javascript
http://localhost:8000/docs/api/ vs. https://ably-docs-next-staging.herokuapp.com/docs/api/
> [EDX-516] fix trailing dots in links

- src/components/blocks/external-references/styles.css
* [EDX-518](https://ably.atlassian.net/browse/EDX-518?atlOrigin=eyJpIjoiNDc0MDE2MjAxOTVkNGVlZGFhZmJjYTFkZWFiZDczZDQiLCJwIjoiaiJ9)
* [EDX-519](https://ably.atlassian.net/browse/EDX-519?atlOrigin=eyJpIjoiYjRjOTMyMjg4M2MxNDQ2NTkxODUzOGI2YTQ0OTliNGMiLCJwIjoiaiJ9)
* /docs/api/realtime-sdk?lang=javascript
- Also fix this issue om` /stats` /docs/api/realtime-sdk?lang=javascript#methods
> [EDX 518,EDX-519] - Clickable code styled text should have the default blue colour

- src/components/Layout/Layout.tsx
- src/components/Sidebar/RightSidebar/RightSidebar.module.css
- src/components/Sidebar/RightSidebar/RightSidebar.tsx
- src/styles/global-entries.css
* [EDX-481](https://ably.atlassian.net/browse/EDX-481?atlOrigin=eyJpIjoiMjMzYzNkOTNlZTE5NGVjNDgxOTVkNzFlYTBkZThhNGIiLCJwIjoiaiJ9)
- https://ably-docs-2-edx-481-0sly54gf4x.herokuapp.com/docs/api/realtime-sdk
> [EDX-481] - RHS Padding adjustments

- content/realtime/channels.textile
Update JS code. Also remove JSBins as per [this DR](https://ably.atlassian.net/wiki/spaces/DEVX/pages/2243592433/DXDR3+Short+term+plan+for+JSBin).
* [Epic EDU-779](https://ably.atlassian.net/browse/EDU-779)
* [EDU-915](https://ably.atlassian.net/browse/EDU-915)
View the channels page to make sure the JavaScript code is up to date:
* [Channels page](https://ably-docs-2-edu-915-cha-5y6bx0.herokuapp.com/realtime/channels/)
> Update JS code

- src/components/Sidebar/RightSidebar/RightSidebar.module.css
- src/components/Sidebar/RightSidebar/RightSidebar.tsx
- src/components/StaticQuerySidebar/LeftSideBar.tsx
- src/components/StaticQuerySidebar/LeftSidebar.module.css
- src/styles/global-entries.css
- tailwind.config.js
> [EDX-486] Fix for a build fail

- src/components/Header/TopMainNav/SearchBar/EmptyState.tsx
- src/components/Header/TopMainNav/SearchBar/SearchBar.tsx
- src/components/Header/TopMainNav/SearchBar/SuggestionBox.tsx
Creating empty states for search and error
* [Jira ticket](https://ably.atlassian.net/browse/EDX-486).
> [EDX-486] Search bar features - 'no results' and text highlighting

- data/yaml/page-content/homepage.yaml
This PR fixes broken links on the homepage, ensures the CTAs are consistent and removes any duplicate tiles.
Check the homepage in the review app.
> [EDX-494] Fix and update homepage tiles

- src/components/Sidebar/SidebarItem/ExpandableAccordionHeading.tsx
- src/components/Sidebar/SidebarItem/NonExpandableHeading.tsx
- src/components/Sidebar/SidebarItem/SidebarItem.tsx
- src/components/Sidebar/SidebarItem/accordion-heading-props.ts
- src/components/Sidebar/SidebarItem/index.ts
- src/components/Sidebar/SidebarLinkMenu.tsx
- src/components/StaticQuerySidebar/LeftSideBar.tsx
- src/contexts/index.ts
- src/contexts/pathname-context.ts
- src/templates/base-template.tsx
Fixing active states on first page load (gatsby build process)
* [Jira ticket](https://ably.atlassian.net/browse/EDX-515).
> [EDX-515] Staging Issue: There is an issue when you first visit a page without navigating to that page

- src/components/Homepage/BodySection/Card/Card.tsx
- src/components/Homepage/BodySection/Card/CardContent.tsx
- src/components/Homepage/BodySection/Card/CardTitle.tsx
- tailwind.config.js
* [Jira ticket](https://ably.atlassian.net/browse/EDX-524).
> [EDX-524] Change font sizes in cards on Docs Home page

- src/components/Header/TopMainNav/SearchBar/SuggestionBox.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-556).
> [EDX-556] Some search results have the tags (like rest, realtime) and some don’t

- .tool-versions
- data/createPages/createContentMenuDataFromPage.js
- data/createPages/createPageVariants.js
- data/createPages/createPageVariants.test.js
- data/createPages/index.js
- src/components/Sidebar/SidebarHeading.tsx
- src/templates/base-template.tsx
- src/templates/template-data.d.ts
Provides different RHS menus based on language
* [Jira ticket](https://ably.atlassian.net/browse/EDX-526).
Check the following pages:
* [Quickstart guide](http://localhost:8000/docs/quick-start-guide?lang=ruby)
* [API reference; connection](http://localhost:8000/docs/api/realtime-sdk/connection?lang=ruby)
And of course any others that you can think of. Change the language at the top of the page and observe that the menu items update as you change them. Check that they are as you expect from the page contents.
> [EDX-526] RHS menu language variants

- .tool-versions
- src/components/common/language-defaults.ts
- src/templates/base-template.tsx
Fixes redirect rules so we can't see invalid pages.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-555).
> [EDX-555] 'empty grey containers'

- src/components/Container/index.tsx
- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/HorizontalMenu/HorizontalMenu.test.tsx
- src/components/blocks/Html/LinkableHtmlBlock.js
- src/components/blocks/headings/H2.tsx
- src/components/blocks/list/Dl/index.tsx
- src/components/blocks/software/Code/MultilineCodeContent.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/CopyLink.tsx
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- src/hooks/get-current-header-id.ts
- src/styles/global.css
- tailwind.config.js
This PR also removes maxWidth from top nav, because that's referenced in another ticket and this is the easiest way to sort out the horizontal scroll under copy button (there is no ticket for that).
It also sorts https://ably.atlassian.net/browse/EDX-487
* [EDX-584](https://ably.atlassian.net/browse/EDX-584).
* [EDX-479](https://ably.atlassian.net/browse/EDX-479).
* [EDX-487](https://ably.atlassian.net/browse/EDX-487).
> [EDX-584] ignore horizontal scrollbar

- src/components/Header/TopMainNav/SearchBar/KeyIcon.module.css
- src/components/Header/TopMainNav/SearchBar/SearchBar.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-548).
> [EDX-548] Search field UI Changes

- src/components/Homepage/BodySection/BodySection.tsx
- src/components/Homepage/BodySection/BodySectionDescriptionContainer.tsx
- src/components/Homepage/BodySection/Card/CardContent.tsx
- src/components/blocks/external-references/styles.css
- src/components/blocks/typography/P/PendingClassName.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-582).
> [EDX-582]  The font for the Documentation paragraphs should be 16px not 18px

- src/components/blocks/api-reference/headings/ApiReferenceH6.tsx
- src/components/blocks/list/Dl/index.tsx
- src/components/blocks/table/Table.module.css
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
> [EDX-582] paragraphs dls tables and h6

- content/client-lib-development-guide/documentation-formatting-guide.textile
- gatsby-ssr.ts
- src/components/blocks/Html/GenericHtmlBlock.js
- src/components/blocks/typography/P/Tip.tsx
- src/components/blocks/typography/P/index.tsx
- src/utilities/debug/log-return.ts
* [Jira ticket](https://ably.atlassian.net/browse/EDX-599).
> [EDX-599] Paragraph rendering bug

- src/components/Header/HamburgerMenu/HamburgerButton/HamburgerIcon.tsx
- src/components/Header/TopMainNavIllustration/TopMainNavAblyLogo.tsx
- src/components/Header/TopMainNavUser/TopMainNavUserMenu.tsx
- tailwind.config.js
This completes the work from EDX-588 by Nikita by restricting icon sizes and removing unviewable JSX elements (flex md:hidden wrapping a hidden md:flex item).
> [EDX-563] - minor tweaks to icons.

- .circleci/config.yml
- bin/start-nginx
- config/nginx.conf.erb
- gatsby-config.ts
Configure nginx to serve up the site _without_ trailing slashes.
* EDX-444
Pages on the review app should have a `301` redirect if requested with a trailing slash.
> [EDX-444] Trailing slashes and nginx

- src/components/Header/Dropdown/DropdownMenu.tsx
- src/components/Header/Dropdown/DropdownMenuContainer.tsx
- src/components/Header/Dropdown/Summary/MaybeShowSummaryLink.module.css
- src/components/Header/Dropdown/Summary/MaybeShowSummaryLink.tsx
- src/components/Header/Dropdown/Summary/Summary.module.css
- src/components/Header/Dropdown/Summary/Summary.tsx
- src/components/Header/Dropdown/Summary/SummaryTitle.tsx
- src/components/Homepage/BodySection/BodySection.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-573).
> [EDX-375] Top navigation - remove max width

- src/components/Footer/Footer.tsx
- src/components/Layout/Layout.tsx
- src/components/Sidebar/Sidebar.tsx
- tailwind.config.js
> Hotfix: overlapping footer

- src/components/Header/SearchBar/SuggestionBox.tsx
Temporarily taking out breadcrumbs from search suggestion hits
> [Hotfix 🔥] Take out breadcrumbs  

- data/cli-functionality/parser-steps/html-parser.ts
- data/cli-functionality/parser-steps/post-parser.ts
- data/transform/post-parser/index.ts
- read-textile.ts
Adds the final post-parser and html-parser steps into the textile debugger (diff, step by step).
> Add the final steps into the read-textile differ

- .circleci/config.yml
- config/nginx.conf.erb
This helps us to serve up our various assets across domains while proxying docs under ably.com. This is very much inspired by our setup for Voltaire.
> [FIX] Add additional CORS support to nginx config

- content/general/limits.textile
Self-service is changing to PAYG. PAYG limits are also being updated.
* [EDU-911](https://ably.atlassian.net/browse/EDU-911)
* [EDU-1158](https://ably.atlassian.net/browse/EDU-1158)
Check limits against [this page](https://ably.atlassian.net/wiki/spaces/product/pages/2181267624/Limits+in+v5+Pricing).
* [Limits page](https://ably-docs-edu-1158-upda-fsmmga.herokuapp.com/general/limits/)
> [EDU-1158] - Update for PAYG changes

- read-textile.ts
* Improves readability of CLI output from textile debug script
* Adds 'diffOnly' flag that allows viewing only the changed lines in each step
> Improvements to textile debug script

- README.md
Update to the README reflecting that we're at v1, some things have changed.
> [CHORE]: Quick update to README reflecting v1 status

- src/components/Header/Dropdown/Button/DropdownButton.tsx
- src/components/Header/Dropdown/Contents/ContentsContainer.tsx
- src/components/Header/Dropdown/DropdownMenu.tsx
- src/components/Header/Dropdown/DropdownMenuContainer.tsx
- src/components/Header/Dropdown/Summary/Summary.tsx
- src/components/Header/Dropdown/Summary/SummaryDescription.tsx
- src/components/Header/Dropdown/Summary/SummaryTitle.tsx
- src/components/Header/Dropdown/index.ts
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerDropdownFooter.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/BackButton.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/HamburgerSidebarDropdownButton.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/HamburgerSidebarDropdownSummary.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarSubmenu.tsx
- src/components/Header/Header.tsx
- src/components/Header/SearchBar/SearchBar.tsx
- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/HorizontalMenu/HorizontalMenu.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-606).
> [EDX-606] General UX/UI Feedback

- src/components/Header/Dropdown/Button/DropdownButton.tsx
- src/components/Header/Dropdown/Contents/ContentsContainer.tsx
- src/components/Header/Dropdown/DropdownMenu.tsx
- src/components/Header/Dropdown/DropdownMenuContainer.tsx
- src/components/Header/Dropdown/Summary/Summary.tsx
- src/components/Header/Dropdown/Summary/SummaryDescription.tsx
- src/components/Header/Dropdown/Summary/SummaryTitle.tsx
- src/components/Header/Dropdown/index.ts
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerDropdownFooter.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/BackButton.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/HamburgerSidebarDropdownButton.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/HamburgerSidebarDropdownSummary.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarSubmenu.tsx
- src/components/Header/Header.tsx
- src/components/Header/SearchBar/SearchBar.tsx
- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/HorizontalMenu/HorizontalMenu.tsx
Reverts ably/docs#1805
This reversion fixes an issue where the latest changes in main combined with this PR to cause the language selector to show on the left
> DRAFT: Revert "[EDX-606] General UX/UI Feedback"

- src/components/Menu/MenuItemButton/MenuItemButton.module.css
* [Jira ticket](https://ably.atlassian.net/browse/EDX-596).
> [EDX-596] The font size for local language selectors should be 14px (p3) per Figma

- src/components/blocks/wrappers/CopyLink.module.css
- src/components/blocks/wrappers/CopyLink.tsx
* [Jira ticket](https://ably.atlassian.net/browse/EDX-553).
> [EDX-553] Copy link 

- src/components/Sidebar/RightSidebar/RightSidebarMobile.tsx
Make right sidebar mobile dropdown (on page content selection tool) 150% wider
* [Jira ticket](https://ably.atlassian.net/browse/EDX-564).
Ensure right sidebar menu has wider options, selections.
Disclosure arrow location is to be changed in a subsequent PR.
> [EDX-564] Make right sidebar mobile dropdown (on page content selection tool) 150% wider

- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/HorizontalMenu/HorizontalMenu.tsx
- src/components/Menu/TopCodeMenu.tsx
Fixes language select dropdown position bug.
> hotfix: language bar bug

- src/components/Header/Dropdown/Button/AccountPanel/AccountOptions.tsx
- src/components/Header/Dropdown/Button/AccountPanel/AccountUtilityLinks.tsx
- src/components/Header/Header.tsx
- src/components/Header/TopMainNavUser/SignedIn/SignIn.tsx
- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/HorizontalMenu/HorizontalMenu.tsx
> hotfix: Fix singed in header

- src/components/Article/index.tsx
- src/components/Header/Dropdown/Button/DropdownButton.tsx
- src/components/HorizontalMenu/HorizontalMenu.module.css
- src/components/Menu/TopCodeMenu.tsx
- tailwind.config.js
Fixes mobile header overflow-x issue
> hotfix: Header overflow-x fix

- src/components/blocks/typography/P/P.test.tsx
- src/components/blocks/typography/P/PendingClassName.tsx
Filling in some of the gaps in our testing.
* EDX-271.
> [EDX-271] Add paragraph component tests

- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/components/Menu/ReactSelectStyles/control-styles.ts
- src/components/Menu/ReactSelectStyles/custom-react-select-styles.ts
* [Jira ticket](https://ably.atlassian.net/browse/EDX-569)
> [EDX-569] The distance between the disclosure arrow and the language selector should be 24px on desktop and mobile.

- content/protocols/index.textile
Add a protocols page
* [Jira ticket](https://ably.atlassian.net/browse/EDX-499).
Check /protocols in the new toolchain.
[EDX-499]: https://ably.atlassian.net/browse/EDX-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDX-499] add protocols page

- data/yaml/page-content/homepage.yaml
Fixes homepage links pointing to /general/ pages, skipping the redirect and fixing a broken link.
> [FIX] - Fix homepage links to general pages

- content/general/limits.textile
Updated limits page to reflect new v5 PAYG pricing based on support ticket
* [EDU-1174](https://ably.atlassian.net/browse/EDU-1174)
Please ensure all the correct information has been updated based on https://ably.atlassian.net/wiki/spaces/product/pages/2447179818/PDR+50+Accommodate+higher+limits+in+v5+PAYG
@m-hulbert and pass to Mike Clark for final review 
[EDU-1174]: https://ably.atlassian.net/browse/EDU-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updated limits to reflect v5 version

- content/api-streamer/consumer.textile
- content/api-streamer/hub.textile
- content/api/index.textile
- content/protocol-adapters/index.textile
- content/protocols/sse.textile
- content/realtime/channels/channel-parameters/deltas.textile
- content/realtime/metachannels.textile
- content/root/glossary.textile
- content/tutorials/channel-rewind.textile
- content/tutorials/sse-and-http-streaming.textile
Add a page covering the SSE protocol.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-501).
Check /protocols/sse in the new toolchain.
> [EDX-501] add sse

- content/core-features/authentication.textile
Prevents broken search result from affecting user experience
* [Jira ticket](https://ably.atlassian.net/browse/WEB-2861).
Check this page:
https://ably-docs-web-2861-docs-qgkupq.herokuapp.com/docs/core-features/authentication.ably-jwt
You should be redirected to /core-features/authentication
> [WEB-2861] Add redirect from broken link to authentication page

- data/compare.yaml
https://ably.atlassian.net/browse/WEB-3034
> [WEB-3034] Remove faq links in white label

- app.json
This will add logtail for review apps
See: https://ably.atlassian.net/browse/WEB-3044
See review app https://dashboard.heroku.com/apps/ably-docs-add-logtail-t-chxvmi
> [WEB-3044] add logtail to heroku review apps

- src/components/LanguageButton/LanguageButton.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/Menu/TopCodeMenu.tsx
- src/components/blocks/software/Code/CodeCopyButton.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.js
- src/components/blocks/wrappers/LocalLanguageAlternatives.test.tsx
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
[EDU-1337](https://ably.atlassian.net/browse/EDU-1337?atlOrigin=eyJpIjoiODNkZTViNmMwN2VmNGQ5MjgwMWM4ZjhlNDAzZTI2NzgiLCJwIjoiaiJ9)
[EDU-1347](https://ably.atlassian.net/jira/software/c/projects/EDU/boards/162?modal=detail&selectedIssue=EDU-1347&sprint=506)
*  Find any pages that has language selector and the REST/Realtime tab should be present
* Find a page that has different versions and it should only display the latest version
[EDU-1337]: https://ably.atlassian.net/browse/EDU-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EDU-1347]: https://ably.atlassian.net/browse/EDU-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> [EDU-1337] - Implement design for REST/Realtime Selector box

- content/account/control-api.textile
- content/api/index.textile
- content/auth/capabilities.textile
- content/auth/index.textile
- content/general/firehose/amqp-rule.textile
- content/general/firehose/kafka-rule.textile
- content/general/firehose/kinesis-rule.textile
- content/general/firehose/pulsar-rule.textile
- content/general/firehose/sqs-rule.textile
- content/general/limits.textile
- content/root/glossary.textile
- content/root/tools.textile
- data/yaml/page-furniture/sidebar.yaml
This PR migrates the Control API into the new content design. It also merges the three standalone pages into a single page.
See [JIRA](https://ably.atlassian.net/browse/EDU-1231) for further information.
> [EDU-1231] Migrate and merge Control API into new content design

- src/components/SDKInterfacePanel/SDKInterfacePanel.tsx
This PR ensures that mobile design works well.
[EDU-1346](https://ably.atlassian.net/browse/EDU-1346)
Only change required was to add rounded borders to the top of the SDK panel
[EDU-1346]: https://ably.atlassian.net/browse/EDU-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Adds rounded border to top of panel

- src/components/LanguageButton/LanguageButton.test.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/Menu/TopCodeMenu.tsx
- src/components/SDKInterfacePanel/SDKInterfacePanel.test.tsx
- src/components/SDKInterfacePanel/SDKInterfacePanel.tsx
- src/components/SDKInterfacePanel/index.ts
- src/components/blocks/software/Pre.test.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/LocalLanguageAlternatives.test.tsx
* [EDU-1364](https://ably.atlassian.net/browse/EDU-1364)
**Update following tests:**
- Pre Component :  Add rest and realtime languages in the attributes and add new tests with realtime and rest data
- LocalLanguageAlternative:  Add rest and realtime languages in the attributes and new tests make sure the SDKInterface menu is visible  if SDK languages exists
- LanguageButton: adding new tests to make sure SDK languages still supported and with localChange being removed is should still display a correct active button
**Add new test file**
- SDKInterfacePanel - add different scenarios to make sure this component is fully testes
*  Run the tests in your local
[EDU-1364]: …
> [EDU-1364] - Add & Update Existing Tests for the Rest/Realtime Selector & other related changes

- package-lock.json
- package.json
Slack Issue [here](https://ably-real-time.slack.com/archives/C01LR5XFHFX/p1681672091395959)
Review here - https://ably-docs-kotlin-upgrad-ulsfma.herokuapp.com/docs/asset-tracking?lang=kotlin
> Update Ably UI so kotlin code can be highlighted

- package-lock.json
- package.json
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
[EDU-1387](https://ably.atlassian.net/browse/EDU-1387)
- Need to run npm i first
- then run develop
- single code ex page is - `/docs/mqtt?lang=javascript`
[EDU-1387]: https://ably.atlassian.net/browse/EDU-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Upgrade Ably-ui and Language navigation display if only 1 language

- src/components/Footer/FooterTopNav/FooterLogo.tsx
Replace the footer logo to StaticImage
https://ably-docs-replace-stati-kk3csc.herokuapp.com/docs
> Replace the footer logo to StaticImage

- content/core-features/authentication.textile
> [CEX-227] Add token limits docs

- content/basics/use-ably.textile
Add a page giving an overview of the ways you can use Ably.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-414).
Note - new branch and PR after rebase of IA update for clarity, [original PR](https://github.com/ably/docs/pull/1745)
Check /basics/use-ably in the new toolchain
> [EDX-414] basics - how

- content/core-features/authentication.textile
the link was blindly copy pasted probably by me and refers to two places in the file
> Fix token limits link

- content/api/realtime-sdk/connection.textile
- content/api/rest-api.textile
- content/api/rest-sdk/messages.textile
- content/auth/capabilities.textile
- content/auth/revocation.textile
- content/channels/index.textile
- content/connect/index.textile
- content/presence-occupancy/presence.textile
This PR applies the updates from `main` branch into the new content structure. These updates would be lost in a rebase as the content has been restructured.
The following PRs have been applied:
* https://github.com/ably/docs/pull/1912
* https://github.com/ably/docs/pull/1911
* https://github.com/ably/docs/pull/1892
* https://github.com/ably/docs/pull/1870
> [EDU-1392] Update content from main branch in new content structure

- content/auth/capabilities.textile
- content/auth/identified-clients.textile
- content/channels/index.textile
- content/channels/options/deltas.textile
- content/channels/options/encryption.textile
- content/channels/options/index.textile
- content/channels/options/rewind.textile
- content/connect/index.textile
- content/connect/states.textile
- content/metadata-stats/metadata/rest.textile
- content/metadata-stats/metadata/subscribe.textile
- content/presence-occupancy/presence.textile
- content/protocols/index.textile
- content/storage-history/storage.textile
This PR updates the placeholder links with the correct content now that all pages have been created.
> Update placeholder links in new content structure

- data/yaml/page-furniture/sidebar.yaml
This PR update the table of contents in preparation for launch. The main points are that it:
* Removes sections left in to test against
* Splits the 'Products' section into component parts
> Update table of contents for pre-launch

- content/core-features/authentication.textile
Rename the slow mode token claim prefix/namespace as agreed in [CEDR11](https://ably.atlassian.net/wiki/spaces/product/pages/2609905686/CEDR11+Naming+of+slow+mode+user+claim?focusedCommentId=2616131592).
There is already an [approved PR](https://github.com/ably/realtime/pull/4923) which will get merged right away. We need this documentation change to be merged as close as possible to the prod deployment of the token claim changes.
There is no Jira ticket for this task.
> Rename slow mode token claims documentation

- content/root/glossary.textile
This PR updates several terms in the glossary to be consistent with the changes made to terminology as part of the new IA.
> [EDU-144] Update glossary terms to match new IA

- content/basics/ably.textile
This PR adds a 'What is Ably' introductory page.
> [EDU-1196] Add an intro to Ably page

- data/yaml/page-content/homepage.yaml
This PR updates the homepage tiles for the new content structure.
Review the homepage.
> [EDU-1237] Update homepage tiles

- content/channels/options/rewind.textile
This PR updates the description for limits on rewind. It is possible to rewind into persisted history using a time-based value now.
See [JIRA](https://ably.atlassian.net/browse/EDU-1405) for further info.
> [EDU-1405] Remove note on time-based rewind restriction

- content/compare/push-vs-pusher.textile
This PR fixes broken partial references in `compare/push-vs-pusher` to get the page to render again.
Part of WEB-2718
Best done with a local copy of the website and pointing bundler to this branch
> [FIX] Broken partial references in push-vs-pusher template

- content/api/realtime-sdk/presence.textile
- content/asset-tracking/index.textile
- content/basics/use-ably.textile
- content/channels/messages.textile
- content/channels/options/deltas.textile
- content/general/firehose/amqp-rule.textile
- content/general/firehose/kinesis-rule.textile
- content/general/firehose/sqs-rule.textile
- content/presence-occupancy/occupancy.textile
- content/presence-occupancy/presence.textile
- content/protocols/mqtt.textile
- content/protocols/sse.textile
- content/storage-history/storage.textile
- content/tutorials/jwt-authentication.textile
This PR fixes various broken links from where pages have been redirected in the new IA.
> [EDU-1422] Fix: various broken links from page deletions

- data/yaml/page-furniture/footerMenu.yaml
This PR updates the links in the docs footer to avoid people being redirected.
> [EDU-1408] Update links in the docs footer

- content/general/limits.textile
Corrected the API request rate limit
per https://ably.atlassian.net/browse/WEB-3263
> Correct API Request Rate limit value

- content/spaces/index.textile
This PR adds a product overview for Spaces and the Spaces SDK.
See [JIRA](https://ably.atlassian.net/browse/MMB-208) for the related ticket and further information.
> [MMB-208] Add Spaces product overview

- content/spaces/index.textile
- data/yaml/page-content/channels.yaml
- data/yaml/page-content/spaces.yaml
This PR updates the copy for the Spaces landing page and makes the channels landing page consistent.
> [MMB-288] Update Spaces landing page copy

- content/api-streamer/consumer.textile
Adds the event name `greeting` to the example code.
* [EDU-1396](https://ably.atlassian.net/browse/EDU-1396) -- Event name is missing from C# quickstart code
[EDU-1396]: https://ably.atlassian.net/browse/EDU-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-1396] Adds the event name

- content/spaces/locations.textile
- data/yaml/page-content/spaces.yaml
This PR makes the usage of 'member location' consistent.
> [MMB-293] Make use of member location consistent

- content/getting-started/sdks.textile
- content/spaces/index.textile
- content/spaces/locking.textile
This PR makes some final changes to the content to make Spaces release ready by clarifying the status and add it to the list of available SDKs.
> [MMB-294] Make spaces content release ready

- content/getting-started/sdks.textile
- content/spaces/cursors.textile
- content/spaces/setup.textile
This PR corrects the `outboundBatchInterval` calculation and updates the Spaces SDK version.
> [MMB-297] Update outboundBatchInterval calculation

- content/spaces/avatar.textile
- content/spaces/cursors.textile
- content/spaces/locations.textile
- content/spaces/locking.textile
This PR fixes the Spaces code samples to ensure functions are asynchronous where required and corrects the component locking example to correctly set attributes.
> [MMB-296] Update async code examples

- content/spaces/space.textile
On the /docs/spaces/space page:
- Changed the writing style to active voice. 
- Removed 'new line character' and 'whitespace'
[EDU-1430](https://ably.atlassian.net/browse/EDU-1430)
[EDU-1430]: https://ably.atlassian.net/browse/EDU-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1430: Updates content style to an active voice and corrects wording

- content/spaces/locking.textile
- content/spaces/space.textile
This PR adds ErrorInfo codes to the relevant places throughout the Spaces documentation. 
See [JIRA](https://ably.atlassian.net/browse/MMB-262) for further information.
> [MMB-262] Add ErrorInfo codes to Spaces docs

- content/spaces/locking.textile
This PR adds getSelf() and getOthers() descriptions to component locking.
> [MMB-299] Add getSelf() and getOthers() for .locks

- data/yaml/page-furniture/sidebar.yaml
- src/components/Sidebar/Sidebar.tsx
Early feedback on the new docs IA has been that it would be useful to have the top level sections of the sidebar collapsible and collapsed by default.
- Indented the sidebar data 1 level to make it collapsible
- Added top level overview link to get back to top page
* [Jira ticket](https://ably.atlassian.net/browse/ACT-39).
* [Page to review](http://localhost:8000/docs/products/channels)
> [ACT-39] collapsible sidebar items

- .eslintrc.json
- gatsby-browser.tsx
- gatsby-ssr.tsx
- src/components/GlobalLoading/GlobalLoading.tsx
- src/components/Layout/Layout.tsx
- src/components/Layout/index.ts
- src/components/PageTitle.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/icons/ExpandLeftIcon.tsx
- src/components/Sidebar/icons/ExpandRightIcon.tsx
- src/components/StaticQuerySidebar/LeftSideBar.tsx
- src/components/StaticQuerySidebar/SidebarDataRetrieval.tsx
- src/contexts/SidebarContext.tsx
- src/pages/docs.tsx
- src/pages/docs/how-to/pub-sub.tsx
- src/pages/docs/products/channels.tsx
- src/pages/docs/products/spaces.tsx
- src/templates/base-template.tsx
Added a sidebar context to control state for wether the sidebar is open or closed
* [Jira ticket](https://ably.atlassian.net/browse/ACT-73).
* [Page to review](https://ably-docs-act-73-collap-wdxna5.herokuapp.com/docs/products/channels)
> Make the sidebar collapsible

- content/api/rest-api.textile
- content/spaces/setup.textile
- content/spaces/space.textile
This PR:
- Audits the entire Spaces docs for broken links
- Fixes all broken links (just minor syntax fixes) 
- 7 found in total
[EDU-1435: Fix broken links in the Spaces Docs](https://ably.atlassian.net/browse/EDU-1435)
> EDU-1435: Fixes broken links

- src/components/Layout/index.ts
- src/pages/docs.tsx
This fixes a small issue with CSS bundles caused by reordering imports in #2009.
> [FIX] Style conflicts

- content/tutorials/reactjs-realtime-commenting.textile
This PR fixes the import of Ably for the realtime commenting tutorial.
See [JIRA](https://ably.atlassian.net/browse/EDU-1178) for further information.
> [EDU-1178] Fix ably import for realtime commenting

- content/spaces/react.textile
- content/spaces/setup.textile
- data/yaml/page-content/spaces.yaml
- data/yaml/page-furniture/spacesSidebar.yaml
- package-lock.json
Add React documentation for spaces
* [Jira epic ticket](https://ably.atlassian.net/browse/SDK-3890)
* [Jira ticket](https://ably.atlassian.net/browse/SDK-3900).
* Page to review: /docs/spaces/react
> [SDK-3900] Add react documentation for spaces

- content/api/rest-api.textile
Updates the REST API docs to:
- Mark event name as optional for a message publish
- Include the status code in the return section for message publish
Page to review: docs/api/rest-api#publish
> Rest api docs

- how-tos/pub-sub/.env.example
- how-tos/pub-sub/how-to.mdx
- how-tos/pub-sub/package-lock.json
- how-tos/pub-sub/package.json
- how-tos/pub-sub/src/basketballGame.js
- how-tos/pub-sub/src/basketballPublisher.js
- how-tos/pub-sub/src/basketballSubscriber.js
- how-tos/pub-sub/src/components/Scoreboard.tsx
- how-tos/pub-sub/src/footballGame.js
- how-tos/pub-sub/src/footballPublisher.js
- how-tos/pub-sub/src/footballSubscriber.js
- how-tos/pub-sub/src/index.tsx
Implement the publishing and subscribing of basketball and football scores
* [Jira ticket](https://ably.atlassian.net/browse/ACT-78).
> [ACT-78] How-to publisher / subscriber

- src/components/Article/InArticleBanner/InArticleBanner.tsx
- src/components/Article/InArticleBanner/InArticleBannerCopy.tsx
- src/components/Article/index.tsx
- src/components/Homepage/HomepageContent.tsx
- src/components/Layout/Layout.tsx
- src/components/Link.tsx
- src/components/PageTitle.tsx
- src/components/ProductPage/BodySection/BodySection.tsx
- src/components/ProductPage/BodySection/CallToAction.tsx
- src/components/ProductPage/BodySection/Card/Links.tsx
- src/components/Sidebar/RightSidebar/RightSidebar.tsx
- src/components/Sidebar/RightSidebar/RightSidebarWrapper.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/StaticQuerySidebar/LeftSideBar.tsx
- src/components/blocks/Html/index.tsx
- src/components/blocks/complex-functionality/Script.tsx
- src/contexts/user-context/wrap-with-provider.tsx
Small fixes in React and Typescript logic all over the components folder.
Pull the branch as local and check if it builds, ans if there are TypeScript, React and linter errors or warnings.
> FIX: Project wide typescript and react logic small changes

- src/components/ProductNavigation/ProductNavigation.tsx
- tailwind.config.js
- Home Tab
- Remove the Home icon from the Home tab.
- Padding
- Update the padding on nav items 
[Jira ticket](https://ably.atlassian.net/browse/ACT-70)
> [ACT-70] Tab styling

- content/getting-started/react.textile
see ably/ably-js#1493 for context on the first commit
> React docs updates

- content/spaces/avatar.textile
- content/spaces/cursors.textile
- content/spaces/locations.textile
- content/spaces/locking.textile
- content/spaces/space.textile
Some fixes to Spaces docs, for things noticed whilst working on [MMB-156](https://ably.atlassian.net/browse/MMB-156).
Please review commit by commit.
[MMB-156]: https://ably.atlassian.net/browse/MMB-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Further fixes to Spaces docs

- data/yaml/page-content/spaces.yaml
This PR updates the links on the Spaces product landing page to the new example pages.
> [COL-576] Update product landing page example links

- data/yaml/page-furniture/sidebar.yaml
Add link to` /docs/how-to/pub-sub`
> [ACT-81] Link to how tos

- content/api/index.textile
- content/spaces/avatar.textile
- content/spaces/cursors.textile
- content/spaces/locations.textile
- content/spaces/locking.textile
- content/spaces/space.textile
- src/components/Header/Dropdown/Button/api-references.ts
This PR adds a navigation item for the Spaces API reference and links to it from relevant methods throughout the conceptual content.
> [COL-534] Add links to Spaces API reference

- src/components/blocks/software/Code/ApiKeyMenu.tsx
- src/components/blocks/software/Code/ApiKeyMenuSelector.tsx
- src/components/blocks/software/Code/index.tsx
- src/components/blocks/software/Code/util.ts
- src/contexts/user-context.ts
- src/contexts/user-context/wrap-with-provider.tsx
- src/pages/docs/how-to/pub-sub.tsx
This includes a small refactor to the naming and structure so it's less confusing
> [hotfix] Fix docs pages crashing for users who have apps but not keys

- data/compare.yaml
Want to update the number of Ably datacenters so that it is correct.
> Update number of Ably datacenters copy

- content/root/platform-customization.textile
There was no information in the docs on how to set up and configure defining the regional routing and storage for your account once you've spoken to your CSM. This PR adds some information on the relevant page for this purpose.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-209).
> [EDU-209] - Add further information on setting up Regional routing and storage using the client options config

- content/account/2fa.textile
- content/account/sso.textile
- content/account/users.textile
- data/yaml/page-furniture/sidebar.yaml
This PR adds instructions for the following account management tasks:
* User roles
* SSO
* 2FA
The new section can be seen [here](https://ably-docs-edu-480-sso-ezd5tm7n.herokuapp.com/docs/account/users).
> [EDU-480] Add instructions for user management, SSO and 2FA

- content/auth/token.textile
A small typo correction on the Token page where a random " was added.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1470).
> [EDU-1470] - Fix typo where unncessary quotes were placed on Token page

- content/general/webhooks.textile
This PR:
- Amends an incorrect link.
[EDU-1483: Fix incorrect link](https://ably.atlassian.net/browse/EDU-1483)
> EDU-1483: Amends incorrect link

- content/livesync/models/models.textile
This PR:
- Amends code snippet
[COL-660: Amend modelsClient code snippets](https://ably.atlassian.net/browse/COL-660)
> COL-660: Amends modelsClient code snippets

- content/livesync/models/models.textile
This PR:
- Overalls the quality of language 
- Improves the readability and language 
[COL-674: Improve models doc clarity](https://ably.atlassian.net/browse/COL-674)
> COL-674: Improves doc clarity

- content/livesync/connector/index.textile
This PR:
- Updates the overall structure of the doc.
- Clearly explains the purpose of the Database Connector
- Creates clear paths for users to follow with or without an existing database.
- Adds clearer language to describe the processes accurately.
- Improves the overall language.
[COL-657: Integration guidelines for existing systems with LiveSync](https://ably.atlassian.net/browse/COL-657)
> Updates LiveSync install section

- content/account/2fa.textile
- content/account/users.textile
This PR provides information on account deletion and makes the 2FA requirements clearer.
> [EDU-1484] Clarify account deletion and 2FA requirements

- content/livesync/connector/database.textile
- content/livesync/models/index.textile
This PR:
- Amends outbox code example/s.
- Adds a definition list that explains the code example (in the outbox section).
[COL-662: Add data column guidelines](https://ably.atlassian.net/browse/COL-662)
> COL-662: Amends and describes outbox examples

- content/channels/index.textile
(just read through on the site and realised as previously worded it could be misleading)
> Batch publish: slight wording clarification

- data/onCreateNode/create-graphql-schema-customization.ts
- gatsby-config.ts
- src/components/GlobalLoading/GlobalLoading.tsx
- src/external-scripts/index.ts
- src/external-scripts/one-trust.ts
This brings docs inline with our new OneTrust implementation for consent management, giving our users more control over their cookies
* WEB-1325
❗ Blocked by #2141.
> [WEB-1325] OneTrust consent management

- content/auth/basic.textile
- content/auth/identified-clients.textile
- content/auth/revocation.textile
- content/auth/token.textile
- content/channels/index.textile
- content/channels/options/deltas.textile
- content/channels/options/encryption.textile
- content/channels/options/index.textile
- content/channels/options/rewind.textile
- content/connect/index.textile
- content/general/firehose.textile
- content/general/webhooks.textile
- content/getting-started/quickstart.textile
- content/getting-started/react.textile
- content/getting-started/setup.textile
- content/metadata-stats/stats.textile
- content/partials/general/events/_non_enveloped_events.textile
- content/presence-occupancy/presence.textile
- content/storage-history/history.textile
- src/maps/language.tsx
This PR updates the docs for JavaScript v2: 
* Updates JS version number
* Makes Promises default and only variant of the library
* `generateRandomKey()` is now async
* Adds `usePresenceListener` hook
* Adds `ChannelProvider`
> [EDU-1505] Update docs for JavaScript v2.0 

- how-tos/pub-sub/package.json
- how-tos/pub-sub/src/basketballPublisher.complete.js
- how-tos/pub-sub/src/basketballPublisher.js
- how-tos/pub-sub/src/basketballSubscriber.js
- how-tos/pub-sub/src/footballPublisher.js
- how-tos/pub-sub/src/footballSubscriber.complete.js
- how-tos/pub-sub/src/footballSubscriber.js
- how-tos/pub-sub/yarn.lock
- src/pages/how-to/pub-sub.tsx
This PR updates to pub/sub how-to to use v2 of the JavaScript SDK.
> [EDU-1524] Update how-to to use JavaScript v2

- content/protocols/sse.textile
The SSE docs reference an outdated Glitch demo. This PR removes reference to it.
> [EDU-1534] Remove outdated SSE demo

- src/components/SDKsPage/data.ts
This PR adds a tile for React Native to the list of available SDKs.
> [EDU-1535] Add React Native to list of SDKs

- content/general/limits.textile
The limits for bandwidth were mixed between MiB and GiB, so I have explicitly stated the units for each column in that row.
> [EDU-1536] Mixed units in table for bandwidth limits

- content/auth/capabilities.textile
- content/auth/identified-clients.textile
- content/auth/revocation.textile
- content/auth/token.textile
- content/channels/index.textile
- content/channels/options/index.textile
- content/general/push/admin.textile
- content/general/push/publish.textile
- content/general/webhooks.textile
- content/getting-started/setup.textile
- content/metadata-stats/metadata/subscribe.textile
- content/metadata-stats/stats.textile
- content/storage-history/history.textile
A small update to the docs, the Python documentation already appears to have most code snippets that are applicable. I have added some changes to the token page for generating tokens etc in Python.
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-1489).
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1491).
All of the affected pages are Python code samples within Channels product.
> [EDU-1491] Minor update adding Python code snippets

- content/account/sso.textile
This PR ensures that we explicitly state the required name fields when configuring SSO with SAML.
> [EDU-1538] Update required SAML attributes for SSO

- content/getting-started/react.textile
- content/getting-started/setup.textile
This PR highlights the changes made in JavaScript version 2.
> Add UI notices for new and updated features in JS v2

- data/yaml/page-content/asset-tracking.yaml
This PR fixes the meta description for Asset Tracking. See [JIRA](https://ably.atlassian.net/browse/EDU-1560) for further details.
> [EDU-1560] Fix meta description for asset tracking product page

- content/livesync/database-connector.textile
- content/livesync/models.textile
- content/livesync/outbox-nodes-tables.textile
Some links were broken in the LiveSync release. This fixes those.
> Fix invalid links in LiveSync

- .circleci/config.yml
- jest.config.js
- package.json
- src/components/blocks/external-references/AElementHelpers/check-link-is-internal.test.ts
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- tailwind.config.js
- yarn.lock
As first part of many small updates to docs site, in order to modernize it, ably-ui package needs to be updated to newest version.
* [Jira epic ticket](https://ably.atlassian.net/browse/WEB-3426)
Mount the branch and try building the project.
> Ably UI update 14

- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/components/Menu/ReactSelectStyles/control-styles.ts
- src/components/Menu/ReactSelectStyles/option-styles.ts
- src/components/Menu/styles.css
- src/components/Select/styles.ts
- src/styles/global.css
Updating font-family to manrope in global styles and remove next, as there is no more need for him.
Check the fonts used in docs.
> [WEB-3426] update font-family to manrope remove next from global

- src/components/Header/Dropdown/Button/DropdownButton.tsx
- src/components/Header/TopMainNavUser/TopMainNavLink.tsx
- src/components/Homepage/BodySection/Card/FeatureCard.tsx
- src/components/Homepage/BodySection/Card/SdkCard.tsx
- src/components/ProductPage/BodySection/CallToAction.tsx
- src/components/ProductPage/BodySection/Card/ExampleCard.tsx
- src/components/ProductPage/BodySection/Card/FeatureCard.tsx
- src/components/ProductPage/BodySection/Card/Links.tsx
- src/components/ProductPage/BodySection/Card/QuickstartCard.tsx
- src/components/ProductPage/BodySection/Card/TutorialCard.tsx
- src/components/Sidebar/SectionTitle.module.css
- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/SidebarHeading.test.tsx
- src/components/Sidebar/SidebarHeading.tsx
- src/components/Sidebar/SidebarItem/ExpandableAccordionHeading.module.css
- src/components/Sidebar/SidebarItem/ExpandableAccordionHeading.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
Updating font weights based on comments in ticket below.
* [Ticket](https://ably.atlassian.net/browse/WEB-3426).
Check Sidebar and card fonts mostly.
> [Web-3426] CSS update font weights

- src/components/Header/Dropdown/Summary/MaybeShowSummaryLink.tsx
- src/components/Header/Dropdown/Summary/SummaryDescription.tsx
- src/components/Header/Dropdown/Summary/SummaryTitle.tsx
- src/components/Header/Header.tsx
- src/styles/global.css
First part of feedback iterations, consists of font weights, sizes, some colors.
* [Jira ticket](https://ably.atlassian.net/browse/WEB-3426)
Most of it is on the main nav, sidebars and dropdown menu
> [DRAFT] fix classes, remove inline styles

- content/push/device.textile
- content/push/publish.textile
This PR:
- Adds .NET code examples to the required areas of the recently updated Push notification docs.
[EDU-926: Add Flutter to push notifications](https://ably.atlassian.net/browse/EDU-926)
> EDU-926: Adds flutter code examples

- content/push/publish.textile
This PR:
- Removes incorrect code from code examples 
[EDU-1495: Correct code examples](https://ably.atlassian.net/browse/EDU-1495)
> EDU-1495: Removes incorrect code from examples

- content/push/device.textile
This PR:
- Adds Java and Kotlin code examples in place of _just_ Android
> EDU-1567: Adds Java and Kotlin code examples in place of just Android

- content/spaces/setup.textile
This PR updates the import of Spaces to ensure it pulls in the correct version of Ably Pub/Sub depending on which NPM version you're using.
> [EDU-1584] Update spaces imports for npm versions

- content/auth/basic.textile
- content/auth/capabilities.textile
- content/auth/identified-clients.textile
- content/auth/revocation.textile
- content/auth/token.textile
- content/channels/index.textile
- content/channels/options/encryption.textile
- content/channels/options/index.textile
- content/getting-started/quickstart.textile
- content/getting-started/setup.textile
- content/metadata-stats/stats.textile
- content/presence-occupancy/presence.textile
- content/storage-history/history.textile
Added or updated PHP code samples to ensure full up to date coverage of languages.
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-1489) - if applicable.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1496).
> [EDU-1496] Ensure full code coverage for PHP

- content/auth/basic.textile
- content/auth/capabilities.textile
- content/auth/identified-clients.textile
- content/auth/token.textile
- content/channels/index.textile
- content/channels/options/encryption.textile
- content/channels/options/index.textile
- content/channels/options/rewind.textile
- content/connect/index.textile
- content/connect/states.textile
- content/metadata-stats/metadata/subscribe.textile
- content/presence-occupancy/presence.textile
- content/storage-history/history.textile
Ensuring documentation has full code coverage for Go.
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-1489)
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1526).
> [EDU-1526] Ensure full code coverage for go

- content/channels/index.textile
> Removed unused comment

- content/chat/rooms/reactions.textile
This PR adds headers to the structure of a room reaction.
> [CHAT-399] Add headers to room reactions

- content/presence-occupancy/presence.textile
The code snippet was passing the content as if it were a POST request.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1589).
> Corrected GET request for batch presence

- content/protocols/index.textile
- content/protocols/pusher.textile
- data/yaml/page-furniture/sidebar.yaml
This PR combines the content from the Pusher Adapter [FAQ](https://faqs.ably.com/using-the-ably-pusher-protocol-adapter) and [tutorial](https://ably.com/tutorials/pusher-adapter) with the intention of replacing them.
Ensure all content from the original content sources is covered.
> [EDU-1498] Add Pusher Adapter content

- content/protocols/index.textile
- content/protocols/pubnub.textile
- data/yaml/page-furniture/sidebar.yaml
This PR combines the content from the PubNub Adapter [FAQ](https://faqs.ably.com/using-the-ably-pubnub-protocol-adaptor) and [tutorial](https://ably.com/tutorials/pubnub-adapter) with the intention of replacing them.
Ensure all content from the original content sources is covered.
> [EDU-1548] Add PubNub Adapter content

- content/auth/basic.textile
- content/auth/capabilities.textile
- content/auth/identified-clients.textile
- content/auth/token.textile
- content/channels/index.textile
- content/channels/options/encryption.textile
- content/channels/options/index.textile
- content/channels/options/rewind.textile
- content/connect/index.textile
- content/connect/states.textile
- content/getting-started/quickstart.textile
- content/metadata-stats/metadata/subscribe.textile
- content/presence-occupancy/presence.textile
- content/storage-history/history.textile
Adding missing Flutter code samples or updating existing Flutter code samples throughout Pub/Sub Channels documentation.
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-1489) - if applicable.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1492).
> [EDU-1492] - Ensure full code coverage for Flutter

- content/auth/token.textile
- content/channels/index.textile
- content/channels/options/index.textile
- content/connect/index.textile
- content/getting-started/quickstart.textile
- content/getting-started/setup.textile
- content/metadata-stats/metadata/subscribe.textile
- content/metadata-stats/stats.textile
- content/presence-occupancy/presence.textile
- content/storage-history/history.textile
> Updating Java code snippets throughout docs.

- src/components/Footer/FooterTopNav/FooterStatus.tsx
- tailwind.config.js
This PR cherry-picks (as much as possible) ably/ably-ui#430 into this repo (until we upgrade docs to AblyUI 14).
[INF-4803](https://ably.atlassian.net/browse/INF-4083
Review the status widget in the footer.
[INF-4803]: https://ably.atlassian.net/browse/INF-4803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [INF-4803] Update Ably status widget

- content/channels/index.textile
This PR:
- This PR adds the new server-side batching content to the docs 
- Updates all relevant areas of the docs relevant to server-side batching and limits
> EDU-1581: Adds server-side batching docs

- content/metadata-stats/metadata/subscribe.textile
This PR adds Go to the list of languages supported on the metadata subscribe page.
> [EDU-1636] Add Go to list of langs in metadata subscribe

- content/chat/rooms/messages.textile
- content/chat/setup.textile
- Fix chat code sample for `message.subscribe` in https://docs.ably.com/docs/chat/rooms/messages#subscribe
- Fix chat code sample for creating a chat client in https://docs.ably.com/docs/chat/setup#instantiate
- Changed heading from "Error handling" to "Logging" in https://docs.ably.com/docs/chat/setup - it is a section about logging in the Chat SDK.
Pages linked above.
> Fix chat setup and message subscribe code samples

- content/spaces/avatar.textile
- content/spaces/cursors.textile
- content/spaces/locations.textile
- content/spaces/locking.textile
- content/spaces/react.textile
- content/spaces/setup.textile
This PR updates Spaces to use promises now that the Spaces SDK supports using v2+ of Pub/Sub.
> [EDU-1637] Update Spaces to support JS v2.3

- content/general/limits.textile
- content/root/glossary.textile
- content/storage-history/storage.textile
This PR updates the wording around the minimum and maximum time that Ably can store messages for.
> [EDU-1624] Update wording around message storage limits

- data/yaml/page-content/spaces.yaml
- src/components/Homepage/BodySection/Card/FeatureCard.tsx
- src/components/Image.tsx
- src/components/ProductPage/BodySection/BodySection.tsx
- src/components/ProductPage/BodySection/Card/ExampleCard.tsx
- src/components/ProductPage/BodySection/Card/FeatureCard.tsx
- src/components/ProductPage/BodySection/Card/QuickstartCard.tsx
- src/components/ProductPage/BodySection/Card/TutorialCard.tsx
- src/components/ProductPage/BodySection/Card/index.ts
- src/pages/index.tsx
- src/pages/products/channels.tsx
- src/pages/products/chat.tsx
- src/pages/products/livesync.tsx
* [`src/components/Homepage/BodySection/Card/FeatureCard.tsx`](diffhunk://#diff-7d8c99d08fd51839a181d0ae06a5ba4cd80654b19eadd2105b9cddcb05b65d8bL2-R11): Updated the `FeatureCard` component to make the entire card clickable by adding a `navigate` function and conditional rendering for `image` and `links`.
* [`src/components/ProductPage/BodySection/Card/FeatureCard.tsx`](diffhunk://#diff-03149d7b17dd30385ef1ff5ff9b9db8b7764730f9733f0ac81d86f18c8bbb5a7R4-R20): Similar updates to make the card clickable and conditionally render `image` and `links`.
* [`src/components/ProductPage/BodySection/Card/QuickstartCard.tsx`](diffhunk://#diff-a0b485770ab1e4a49f6590d71aaa9092ae1d93472d9c2242e162210877756320R4-R16): Made the `QuickstartCard` component clickable and added conditional rendering for `image` …
> [WEB-3917] - Link whole card

- content/push/configure/device.textile
- content/push/configure/web.textile
- content/push/publish.textile
This PR: 
- Adds REST coverage to the push docs.
[EDU-1568](https://ably.atlassian.net/browse/EDU-1568)
[EDU-1568]: https://ably.atlassian.net/browse/EDU-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1568: Adds REST coverage to push

- content/channels/index.textile
Update channel idempotent publishing doc. Current wording used is a bit confusing, adding more clarity for the same.
Link to internal conversation -> https://ably-real-time.slack.com/archives/C012DA3MCB0/p1725522278686219
> Update rest idempotent publishing doc

- src/external-scripts/inkeep.ts
This PR updates quick questions in Inkeep and adds Docs and Blog tabs to the search results
> Update Inkeep quick questions and search tabs

- content/account/control-api.textile
- static/open-specs/.spectral.yaml
- static/open-specs/control-v1.yaml
See WEB-3909
In the PR docs for new endpoints and response schemas for stats in the ControlAPI
> [WEB-3909] ControlAPI Stats Endpoints

- content/account/control-api.textile
- content/metadata-stats/stats.textile
- static/open-specs/control-v1.yaml
This PR corrects the schema version for account-level statistics.
> Fix Control API schema version

- content/chat/rooms/history.textile
> Fix typo in chat message storage and history page

- content/getting-started/setup.textile
Small fix to Flutter package name in SDK setup
> [EDU-1694] Fix flutter package name in SDK setup

- src/components/SDKsPage/MainSection/index.tsx
- src/components/SDKsPage/data.ts
- src/components/SDKsPage/sdks.module.css
This PR adds a tab for Chat to the list of SDKs. It also fixes an issue with the font weight for active tabs.
> [EDU-1700] Add Chat to SDK tabs

- static/open-specs/control-v1.yaml
Update open api spec for creating and modifying rules to include mongodb change stream ingress rules.
> Control API docs for ingress/mongodb rule

- content/messages/batch.textile
- content/presence-occupancy/presence.textile
- content/pricing/limits.textile
This PR updates the information related to presence and server-side batching: 
* Updates the limits section with the new limit for batched presence members
* Updates the presence page with a section about large-scale presence sets
> [EDU-1711] Update presence information regarding server-side batching

- package.json
- src/components/GlobalLoading/GlobalLoading.tsx
- src/components/Layout/Header.tsx
- src/components/Layout/Layout.tsx
- src/components/Layout/RightSidebar.tsx
- src/components/Layout/utils/options.ts
- src/contexts/layout-context.tsx
- src/data/nav/pubsub.ts
- src/data/nav/types.ts
- src/hooks/use-set-layout-options.ts
- src/pages/api/control-api.tsx
- src/pages/how-to/pub-sub.tsx
- src/pages/index.tsx
- src/pages/sdks/index.tsx
- yarn.lock
Fixes for a variety of small post-launch bugs. Commits are quite granular and describe what's going on but here's the word of bot.
Review link: https://ably-docs-web-4082-gith-3odnys.herokuapp.com/
This pull request includes several changes to the codebase, primarily focusing on adding a `template` property to layout options and improving the loading and script injection logic in the `GlobalLoading` component. The most important changes are summarized below:
* Added a `template` property to the `LayoutOptions` type and updated the `defaultLayoutOptions` in `src/components/Layout/utils/options.ts` to include this new property. This change allows for more flexible layout configurations based on the template type. [[1]](diffhunk://#diff-e40e80cb89d2abaada836d8b9411adafe8d6417b99963ca828b27aa0 …
> [WEB-4082] Post-launch nav fixes I

- content/chat/rooms/messages.textile
- src/data/languages/languageData.ts
Added message edit and delete docs for Kotlin and Swift Chat SDKs
> chat: edit and delete for mobile SDKs

- src/external-scripts/inkeep.ts
Simple change of meeting URL in the Hubspot widget.
> [WEB-4211] Update Inkeep Hubspot meeting link

- content/metadata-stats/stats.textile
This PR updates the statistics page and adds information about flattened stats:
* Adds instructions for using the Control API to retrieve stats
* Adds code samples for using a metachannel to retrieve stats
* Updates the sample stats with a flattened version
* Replaces the metrics JSON with more readable tables, including new stats
> [EDU-1607] Refresh stats page and update to flattened stats

- content/chat/connect.textile
- content/chat/rooms/history.textile
- content/chat/rooms/messages.textile
- content/chat/rooms/presence.textile
- content/chat/rooms/reactions.textile
- content/chat/setup.textile
- Fixed https://github.com/ably/ably-chat-kotlin/issues/105
- TODOs
> [ECO-5229] Fixed chat kotlin snippets

- content/chat/rooms/messages.textile
- Updates the messages.update signature for chat-js, including a `copy` function.
> chat: add JS message copying and update signature

- content/chat/rooms/moderation/hive-model-only.textile
Adds documentation for Hive text only moderation rules.
[CHA-828]
[CHA-828]: https://ably.atlassian.net/browse/CHA-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hive text only rules

- content/chat/rooms/moderation/index.textile
Adds an introduction to the Chat moderation documentation.
> chat: moderation introduction

- content/pricing/free.textile
- content/pricing/pro.textile
- content/pricing/standard.textile
This PR makes upgrading and downgrading between packages clearer:
* Upgrade instructions now sit on all relevant pages, rather than only on the page you wanted to upgrade _from_. 
* Clarifies the final package cost when downgrading. 
Addresses #2465
> [EDU-1839] Clarify upgrade and downgrading of packages

- content/platform/deprecate/index.textile
- content/platform/deprecate/protocol-v1.textile
- src/data/nav/platform.ts
This PR adds new content to the Platform section for a deprecation policy and notice. This includes
* A Products and SDK section
* A link to the list of available SDKs
* A deprecation policy for SDKs
* A deprecation notice about v1 of the protocol 
This section will also document product release stages and versioning in a future PR.
> [EDU-1921] Deprecation policy and notice

- content/platform/index.textile
Add LiveObjects section to https://ably.com/docs/platform
> Add LiveObjects section to platform/index

- src/data/nav/liveobjects.ts
Following the discussion in https://github.com/ably/docs/pull/2464#discussion_r1998875244 update the navigation for LiveObjects docs
> Add Advanced section for some of the LiveObjects navigation items

- src/data/languages/languageData.ts
[ably-js 2.7.0](https://github.com/ably/ably-js/releases/tag/2.7.0) was just released with Annotations feature. The LiveObjects released should be released in the next 2.8.0 version.
> Update language data for JavaScript SDK to 2.8 for LiveObjects branch

- src/data/languages/languageData.ts
ably-js 2.7.0 release https://github.com/ably/ably-js/releases/tag/2.7.0
> Update language data for JavaScript SDK to 2.7

- content/chat/getting-started/javascript.textile
- src/data/nav/chat.ts
This PR adds a new getting started guide for Ably Chat with JavaScript.
It includes;
* A new getting started guide for Chat in JavaScript.
* Adds the guide to the existing 'getting started' section for now. Other items will be moved/removed once there are more guides.
Note the spacing of bullet points will be improved in #2511.
> [EDU-1851] Add a Chat getting started guide for JavaScript

- content/liveobjects/batch.textile
- content/liveobjects/concepts/objects.textile
- content/liveobjects/concepts/operations.textile
- content/liveobjects/concepts/synchronization.textile
- content/liveobjects/counter.textile
- content/liveobjects/inband-objects.textile
- content/liveobjects/index.textile
- content/liveobjects/lifecycle.textile
- content/liveobjects/map.textile
- content/liveobjects/quickstart.textile
- content/liveobjects/rest-api-usage.textile
- content/liveobjects/typing.textile
This PR adds an experimental flag to all LiveObjects docs.
> [EDU-1936] Add the experimental flag to LiveObjects

- src/data/languages/languageData.ts
LiveObjects to release in [ably-js 2.9.0](https://github.com/ably/ably-js/pull/2029)
> Update ably-js language version to 2.9 - LiveObjects release

- src/templates/examples.tsx
There's a bug with the `pub-sub-message-encryption` [example](https://ably.com/examples/pub-sub-message-encryption?lang=javascript) currently where the `encrypted` query parameter is lost on the left-hand preview iframe when the language is switched. From looking into it, this seems to be a bug with Sandpack itself - the `startRoute` param on `SandpackPreview` is lost on re-render, even when it isn't conditionally applied like we do now.
This slightly hacky fix re-applies the param to the first (i.e. left) preview iframe on `pub-sub-message-encryption` on language change, via a brief setTimeout (because it needs one, it seems).
> [WEB-4356] Re-add encrypted param on encryption examples on language change

- content/chat/moderation/index.textile
Adds a note that free credits are available to test hive moderation rules.
> chat/moderation: add free credits note for hive

- content/chat/index.textile
- content/chat/rooms/message-reactions.textile
- content/chat/rooms/messages.textile
- content/chat/setup.textile
- src/data/nav/chat.ts
Add Chat Message Reactions docs. Currently only JS.
> Add Chat Message Reactions docs

- src/components/Layout/mdx/tables.tsx
This PR updates the tables component for MDX pages based on new designs.
* Top aligns content in cells
* Ensures 24px padding between columns
* Updates the heading text weight
> [EDU-1825] Update MDX table styling based on designs

- content/errors/codes.textile
Adds docs for error code 40023.
> errors: add 40023 error code docs

- examples/chat-online-status/javascript/src/script.ts
- examples/chat-online-status/react/src/App.tsx
- examples/chat-room-history/javascript/src/script.ts
- examples/chat-room-history/react/src/App.tsx
- examples/chat-room-messages/javascript/src/script.ts
- examples/chat-room-messages/react/src/App.tsx
- examples/chat-room-reactions/javascript/src/script.ts
- examples/chat-room-reactions/react/src/App.tsx
- examples/chat-typing-indicator/javascript/src/script.ts
- examples/chat-typing-indicator/react/src/App.tsx
- examples/package.json
- examples/yarn.lock
- src/components/Examples/ExamplesRenderer.tsx
Updated demos with dependencies on old chat version.
Updated `ably` dependency to 2.7.0, required by chat.
Update ably/chat dependency to 0.7.0 when its released. For now I've left it as the full git tag so its easy to test.
> Update ably-chat-js demos to latest single channel version

- src/pages/docs/chat/getting-started/javascript.mdx
Removed the `AllFeaturesEnabled` configuration from the `getStarted`  js guides.
> Chat: Correct getting started guide

- content/platform/architecture/index.textile
- src/data/nav/platform.ts
- src/pages/docs/platform/architecture/connection-recovery.mdx
- src/pages/docs/platform/architecture/edge-network.mdx
- src/pages/docs/platform/architecture/fault-tolerance.mdx
- src/pages/docs/platform/architecture/idempotency.mdx
- src/pages/docs/platform/architecture/infrastructure-operations.mdx
- src/pages/docs/platform/architecture/message-ordering.mdx
- src/pages/docs/platform/architecture/performance.mdx
- src/pages/docs/platform/architecture/platform-scalability.mdx
This PR adds some additional articles to expand on the existing architecture section. 
Some additional follow-up PRs will make some editorial adjustments to each article, adds links throughout the documentation where relevant to the articles, and review the structure of the architecture section.
> [EDU-1960] Add architecture articles to the platform section

- src/components/Layout/Layout.tsx
https://github.com/ably/docs/pull/2597 fixed the Control API but didn't account for the Chat REST API. This PR addresses that inconsistency.
> Fix the layout of the Chat REST API

- src/components/Layout/Layout.tsx
Reverts ably/docs#2640
This has had some unintended side effects. Reverting and investigating.
> Revert "Fix the layout of the Chat REST API"

- examples/chat-presence/javascript/src/script.ts
- examples/chat-presence/react/src/App.tsx
- examples/chat-room-history/javascript/src/script.ts
- examples/chat-room-history/react/src/Chat.tsx
- examples/chat-room-messages/react/src/App.tsx
- examples/chat-room-reactions/javascript/src/script.ts
- examples/chat-room-reactions/react/src/App.tsx
- examples/chat-typing-indicator/javascript/README.md
- examples/chat-typing-indicator/react/src/App.tsx
- examples/package.json
- examples/yarn.lock
- src/components/Examples/ExamplesRenderer.tsx
- src/data/languages/languageData.ts
- src/pages/docs/chat/connect.mdx
- src/pages/docs/chat/getting-started/javascript.mdx
- src/pages/docs/chat/getting-started/react.mdx
- src/pages/docs/chat/moderation/custom/index.mdx
- src/pages/docs/chat/moderation/direct/hive-dashboard.mdx
- src/pages/docs/chat/rooms/history.mdx
- src/pages/docs/chat/rooms/index.mdx
- src/pages/docs/chat/rooms/message-reactions.mdx
- src/pages/docs/chat/rooms/messages.mdx
- src/pages/docs/chat/rooms/occupancy.mdx
- src/pages/docs/chat/rooms/presence.mdx
- src/pages/docs/chat/rooms/reactions.mdx
- src/pages/docs/chat/rooms/typing.mdx
- static/open-specs/chat.yaml
Incorporates the changes for the Chat V1 API review.
Only does this for JS.
[CHA-955]
[CHA-955]: https://ably.atlassian.net/browse/CHA-955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chat v1 api review (JS)

- src/pages/docs/chat/index.mdx
Adds links to the React/Kotlin getting started guides for chat to the chat docs root.
> chat: add getting started links for kotlin/react to docs root

- examples/chat-room-reactions/javascript/src/script.ts
- examples/chat-room-reactions/react/src/App.tsx
- examples/package.json
- examples/yarn.lock
- src/components/Examples/ExamplesRenderer.tsx
- src/data/languages/languageData.ts
- src/pages/docs/chat/getting-started/javascript.mdx
- src/pages/docs/chat/getting-started/react.mdx
- src/pages/docs/chat/rooms/reactions.mdx
Renaming reaction.type to reaction.name for consistency with message reactions.
> chat: update reaction.type to name for js/react

- content/getting-started/python.textile
- src/data/nav/pubsub.ts
[Getting started guide](https://ably-docs-edu-1979-crea-fd39ju.herokuapp.com/docs/getting-started/python) for Pub/Sub with Python
> Add Python getting started guide for Pub/Sub

- src/pages/docs/chat/rooms/message-reactions.mdx
- static/open-specs/chat.yaml
- **Change reaction types to short-form in chat REST API reference**
- **Remove annotation types from chat reaction type table**
- **Add mapping of annotation type to reaction type**
> message reactions short reftype CHA 1036

- src/pages/docs/chat/getting-started/javascript.mdx
- src/pages/docs/chat/getting-started/react.mdx
- src/pages/docs/chat/rooms/history.mdx
- src/pages/docs/chat/rooms/index.mdx
- src/pages/docs/chat/rooms/message-reactions.mdx
- src/pages/docs/chat/rooms/messages.mdx
- src/pages/docs/chat/rooms/occupancy.mdx
- src/pages/docs/chat/rooms/presence.mdx
- src/pages/docs/chat/rooms/reactions.mdx
- src/pages/docs/chat/rooms/typing.mdx
- src/pages/docs/guides/chat/build-livestream.mdx
Corrected a bunch of incorrect types/logic that we had defined throughout chat docs.
[CHA-1058](https://ably.atlassian.net/browse/CHA-1058)
[CHA-1058]: https://ably.atlassian.net/browse/CHA-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chat: Update documentation to match 0.10.0 release

- src/data/languages/types.ts
- src/data/nav/chat.ts
- src/pages/docs/chat/getting-started/react-ui-components.mdx
- src/pages/docs/chat/react-ui-components/component-styling.mdx
- src/pages/docs/chat/react-ui-components/components.mdx
- src/pages/docs/chat/react-ui-components/index.mdx
- src/pages/docs/chat/react-ui-components/providers.mdx
- src/pages/docs/chat/react-ui-components/setup.mdx
- Added a getting started guide to take your through basic setup and usage of Ably Chat React UI Components.
- Added a docs page on some of the components and providers available in the React UI Components library.
> Added docs for Ably Chat React UI Components

- src/components/Markdown/MarkdownProvider.tsx
- src/components/blocks/external-references/A.tsx
When rewriting links, check that they're internal more effectively, checking for anchor links isn't enough.
Review link: https://ably-docs-web-4478-link-yfjmim.herokuapp.com/
> [WEB-4478] fix: test for internal links when rewriting more comprehensively

- src/pages/docs/chat/rooms/presence.mdx
Changes reflecting the latest SDK release
> chat: fix examples for presence in chat-swift

- data/onPostBuild/llmstxt.ts
Adds support for including MDX pages in the generated `llms.txt` file.
- **Fixed GraphQL schema**: Added missing `slug` and `articleType` fields to `FileHtml` type definition
- **Added MDX support**: Extended the llms.txt generator to include MDX pages from `/docs/*` alongside existing textile pages
- **Fixed query structure**: Replaced invalid GraphQL filters with JavaScript-based filtering for better compatibility
- **Fixed slug generation**: Prevented double "docs" prefixes in MDX page URLs
- llms.txt now includes 196 pages total: 100 textile + 96 MDX pages
- All chat documentation (`/docs/chat/*`) and other MDX content is now included in the AI training data
Ensures comprehensive documentation coverage for LLM training.
> Add MDX pages support to llms.txt generation

- content/getting-started/flutter.textile
- src/data/nav/pubsub.ts
- src/pages/docs/getting-started/flutter.mdx
- src/pages/docs/getting-started/index.mdx
Added the Flutter getting started guide for Pub/Sub
> [EDU-1976] - Added Flutter getting started guide

- content/auth/capabilities.textile
- content/partials/core-features/_authentication_capabilities.textile
Update capability description for subscribe to also include objects, as well as presence and messages.
> Update capability description for subscribe

- content/getting-started/dotnet.textile
- src/data/nav/pubsub.ts
- src/pages/docs/getting-started/dotnet.mdx
- src/pages/docs/getting-started/index.mdx
This PR adds a new getting started guide for Pub/Sub. The C#/Dotnet guide.
> [EDU-1975] - Added dotnet getting started guide

- content/presence-occupancy/presence.textile
- src/pages/docs/auth/token.mdx
- src/pages/docs/pub-sub/advanced.mdx
Minor code samples fixes.
I've noticed and fixed one of these and then asked Cursor to fix more. It didn't do a big enough search but did find a few code typos to fix.
> Fix a few code typos

- src/data/languages/languageData.ts
Latest release https://github.com/ably/ably-js/releases/tag/2.11.0
> Update ably-js language data to 2.11

- src/pages/docs/liveobjects/map.mdx
Resolves [PUB-2017](https://ably.atlassian.net/browse/PUB-2017)
[PUB-2017]: https://ably.atlassian.net/browse/PUB-2017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PUB-2017] Add docs for `LiveMap.size()` method

- src/pages/docs/liveobjects/counter.mdx
- src/pages/docs/liveobjects/map.mdx
Docs for https://github.com/ably/ably-js/pull/2072
> [PUB-2015] Document `clientId` surfaced in LiveObjects subscription callbacks

- src/data/nav/chat.ts
- src/pages/docs/chat/getting-started/swift.mdx
Chat Swift SDK getting started guide which uses SwiftUI to help the user create a working Chat example app with a UI.
> [ECO-5269] Chat Swift getting started guide which helps build a SwiftUI Chat App

- src/pages/docs/liveobjects/quickstart/swift.mdx
> Fix link to Swift LiveObjects repo

- src/data/nav/pubsub.ts
- src/pages/docs/chat/getting-started/javascript.mdx
- src/pages/docs/chat/getting-started/kotlin.mdx
- src/pages/docs/chat/getting-started/react-native.mdx
- src/pages/docs/chat/getting-started/react-ui-components.mdx
- src/pages/docs/chat/getting-started/react.mdx
- src/pages/docs/chat/getting-started/swift.mdx
- src/pages/docs/getting-started/dotnet.mdx
- src/pages/docs/getting-started/flutter.mdx
- src/pages/docs/getting-started/go.mdx
- src/pages/docs/getting-started/java.mdx
- src/pages/docs/getting-started/javascript.mdx
- src/pages/docs/getting-started/kotlin.mdx
- src/pages/docs/getting-started/objective-c.mdx
- src/pages/docs/getting-started/php.mdx
- src/pages/docs/getting-started/python.mdx
- src/pages/docs/getting-started/react-native.mdx
- src/pages/docs/getting-started/react.mdx
- src/pages/docs/getting-started/ruby.mdx
- src/pages/docs/getting-started/swift.mdx
- **Environment Variables**: Updated the guide to use `.env` file for API key management instead of hardcoded values for better security practices
- **Prerequisites Improvements**: 
- Added direct link to create new Ably app in step 2
- Enhanced instructions for API key setup
- Updated security note to emphasise adding `.env` to `.gitignore`
- **Code Examples**: Updated JavaScript code to use `process.env.ABLY_API_KEY` for cleaner, more secure implementation
- **Language Selector Logic**: Fixed RightSidebar component to not show language selector on the getting-started guides, but still showing for SDK setup page (as this comes under getting-started url)
- **CLI**: Moved CLI instructions to the bottom of prerequisites, and ensured this is labelled as `Optional`.
- **History**: Stated …
> [EDU-2027] - General getting started guide improvements

- src/pages/docs/platform/pricing/faqs.mdx
Based on https://sdk.ably.com/builds/ably/specification/main/features/#TM6 extras is also part of the message size calculation
> add extras to /docs/pricing/faqs#message-size

- src/pages/docs/platform/architecture/index.mdx
This PR fixes an indentation issue with bullet points that was likely missed in the migration from textile.
> fix: bullet point formatting in architecture overview

- src/pages/docs/liveobjects/batch.mdx
- src/pages/docs/liveobjects/counter.mdx
- src/pages/docs/liveobjects/index.mdx
- src/pages/docs/liveobjects/map.mdx
- src/pages/docs/liveobjects/rest-api-usage.mdx
Pricing details based on the tests done in https://ably.atlassian.net/browse/PUB-1604
Resolves [PUB-1604](https://ably.atlassian.net/browse/PUB-1604).
[PUB-1604]: https://ably.atlassian.net/browse/PUB-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PUB-1604] Explain LiveObjects pricing in docs

- src/data/languages/languageData.ts
- src/pages/docs/chat/getting-started/android.mdx
- src/pages/docs/chat/setup.mdx
This change bumps the version of chat kotlin and also updates the gradle config to work with the new KMP setup.
> chat: bump kotlin version and gradle config

- static/open-specs/chat.yaml
https://ably.atlassian.net/browse/CHA-1099
> Add client-reactions endpoint in chat http api reference

- src/data/languages/languageData.ts
> Update LiveObjects Swift version
