- docs.gemspec
- lib/ably-docs.rb
Please see https://github.com/ably/website/pull/309
This needs to be merged into `#source` branch, and then the Gemfile in the website needs to reference `#source` instead of this working branch `#gem`.
> Allow usage of this the docs repo as a Gem to avoid need to use submodules

- content/client-lib-development-guide/features.textile
discussion in https://github.com/ably/ably-js/pull/120
> Tweak cipherparams description, add getDefaultParams

- content/assets/stylesheets/documentation.scss
@lmars I deployed your changes but then saw that the Jump to nav still overlaps on other pages because it is right aligned to a fixed position.
> Jump to nav is now left aligned so will not ever overlap content

- content/client-lib-development-guide/features.textile
Following the [ably-ruby PR to support a wildcard clientId](https://github.com/ably/ably-ruby/pull/66), it became apparent that there is no way currently to determine whether an authenticated client can assume any clientId, or is an anonymous client, because in both instances `Auth#clientId` is `null`.
This PR addresses that issue, and also introduces a new `identityConfirmed` attribute that can be used to cover the situation whereby a client is not yet authenticated or connected and as such the `null` value `Auth#clientId` could mean it's anonymous, but could also mean its `clientId` is unknown at the time
@paddybyers @SimonWoolf WDYT?
BTW. Whilst I would like to include this in the spec, this has no impact on the realtime system, and as such, can be progressively introduced into client …
> Wildcard clientId Auth attribute

- content/client-lib-development-guide/features.textile
This addresses the proposed clarification of the implicit behaviour in https://github.com/ably/docs/issues/67
@paddybyers @SimonWoolf please review
> Consistency in implicit attach and wait for sync on presence#get

- content/client-lib-development-guide/features.textile
See https://github.com/ably/ably-js/issues/43#issuecomment-159657024
As we have not agreed the spec, and it is not a core feature, deferring this until 0.9
@SimonWoolf @paddybyers you happy with this?
> Remove connect callback as not agreed in spec

- content/root/how-ably-works.textile
Looks good. Couple of trivial style tweaks. (also for the auth diagrams: second one seems to have much smaller arrowheads than the first)
Minor concern: we don't give any guidance on whether to use server-signed token requests or server-requested tokens. I'd guess most devs probably just want to be told 'do it this way except in circumstances X,Y,Z'? (If we really don't want to have a preferred one, should we maybe just pick one for the 'how ably works' page to keep it simple, relegate the other to an "Alternatively, ..." paragraph with no diagram?)
> Proofread of how-ably-works draft

- content/client-lib-development-guide/features.textile
Following two discussions https://github.com/ably/ably-ios/pull/208#discussion_r52734670 and https://github.com/ably/ably-js/commit/1b151df5558339d8b2fd80bbadd2375d9a138b4a on how to handle implicit failures, this PR aims to address the issue by:
* Ensuring that any failure to implicitly attach can notify the caller
* Treating subscribe operations as atomic i.e. if the channel is in a FAILED state, then report the failure to the caller and do no register the listener
This approach is more future-proof as we look to optimise channel attach states i.e. only for subscribe, only for publish etc. based on which operations are called on a channel.  Whilst we could have simply removed the implicit attach, this will hurt us in the long run.
@SimonWoolf @paddybyers @tcard please review
> Completion listeners for implicit operations

- content/client-lib-development-guide/features.textile
This is a requirement of RTL2c that was overlooked in the IDL.
See https://github.com/ably/ably-ios/pull/253#discussion-diff-54078011.
> IDL: Add ChannelEvent enum with ERROR variant.

- config/config.rb
Tried deploying docs.ably.io just now, noticed this repo expects fog creds to be under a 'default' key. Since the infrastructure repo expects ably fog creds to be under an 'ably' key, no point in duplicating them
> Use fog creds from key 'ably', rather than 'default'

- content/general/queues.textile
- content/general/webhooks.textile
@paddybyers @SimonWoolf I have added some very high level documentation in regards to our message queue functionality.  I needed this before we publish our blog post about upcoming queue functionality that we will hopefully test soon with DubTrack.
cc @ashleyf1
> docs: Add notes on message queue functionality

- content/code/rest/channel-history.code
- content/code/rest/channel-publish.code
- content/code/rest/publish-on-behalf-of-client.code
- content/realtime/connection.textile
- content/rest-api/index.textile
- content/rest/channels-messages.textile
- data/jsbins.yaml
A customer has asked how to publish on behalf of a realtime client, a pattern that is often used by Pusher because of their legacy handling of clients typically being receivers only.
This documents how to do that with Ably
> Publish on behalf of a realtime client

- content/client-lib-development-guide/features.textile
See https://www.ably.io/documentation/rest/channels-messages#publish-on-behalf
We need to add `connectionKey` to message definition so that REST clients can publish on behalf of other realtime clients.
@paddybyers I would like to merge this ASAP as it is a blocker for a customer.
> spec: Allow REST publisher to publish on behalf of another client

- content/client-lib-development-guide/features.textile
Per discussion https://github.com/ably/ably-js/issues/155#issuecomment-233481789
Only realtime change needed for now is sending `heartbeatPeriod: config.realtime.heartbeatTimer` in connectionDetails. Honouring qs-param-requested alternate periods is optional & low-priority so can be postponed
> heartbeat timeout proposal

- content/types/_paginated_result.textile
Fixes https://github.com/ably/docs/issues/185
Before merging I will ensure this is not a method in any of the libs
> docs: Remove duplicate items() method on PaginatedResult

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/192
Name chosen to match [what java lib already uses](https://github.com/ably/ably-java/blob/fb719af9bb21b57429cbc3267a6d654284b1ec7c/lib/src/main/java/io/ably/lib/rest/Auth.java#L231-L233). (In particular, the 'normal' constructor when given a string interprets it as a token string, changing that seemed like an unnecessary break in backwards compatibility, especially as a `fromJSON` static method is more explicit anyway)
> Add TokenDetails#fromJSON and TokenRequest#fromJSON

- content/client-lib-development-guide/features.textile
It was a function taking a TokenDetails, TokenRequest or String, but it should be a function that takes nothing and IO-returns a TokenDetails, TokenRequest or String.
IO-returning functions can always fail in a unspecified but platform-consistent manner, so it's relevant for the ongoing #194.
> Fix type of authCallback in IDL.

- content/client-lib-development-guide/features.textile
@paddybyers whilst working on the JSON patch demo and adding functionality to recover the history following discontinuity, it occurred to me that we are really not explicit about what happens for `untilAttach` queries.
I am not sure if client libraries will do the right thing or not at present, so propose adding this to the 0.9 spec
cc @SimonWoolf if you've not left
cc @tcard
> spec: Clarify untilAttach behaviour after discontinuity

- content/client-lib-development-guide/features.textile
This property is now present in the connectionDetails and 0.9 is a good time to remove.
Matching issue to remove in the product when 0.9 is detected, see https://github.com/ably/realtime/issues/802
> Remove deprecated ProtocolMessage#connectionKey

- content/code/reactor/webhook-hmac-sha-256.code
- content/general/versions/v0.8/webhooks.textile
- content/general/webhooks.textile
- data/jsbins.yaml
This PR fixes a typo in our WebHooks docs (we previously incorrectly mentioned AES256 instead of SHA-256 for the HMAC algorithm), and also adds some instructions to test the signature verification to help developers check this themselves more easily in their chosen language.
@paddybyers @SimonWoolf you happy for me to merge in?
> api: WebHook HMAC SHA-256 instructions + demo

- content/realtime/encryption.textile
- content/realtime/versions/v0.8/encryption.textile
- content/rest/encryption.textile
- content/rest/versions/v0.8/encryption.textile
generateRandomKey() doesn't return a value, it takes a callback.
Plus convert the examples from 128-bit to 256-bit keys
> Fix broken ably-js simple encryption example

- content/general/authentication.textile
- content/general/versions/v0.8/authentication.textile
Wildcards now only match multiple segments if at the end of a resource name, see https://github.com/ably/realtime/pull/1027#issuecomment-297261069
> Update resource name wildcard docs for latest realtime behaviour

- content/realtime/encryption.textile
- content/rest/encryption.textile
- content/types/_cipher_params.textile
See https://github.com/ably/ably-java/pull/329
I have no idea why we left Java with a different default, this fixes that change in the docs.
> api: All libs default to 256 bits for Crypto

- content/realtime/connection.textile
The trouble with code examples is people ignore the text, assume the code is a recommended pattern and copy and paste it.
e.g. [this intercom conversation](https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/all/conversations/11471199775) just now with a customer who thought that connection state recovery wasn't working because they copied our example code for connection state recovery, which uses an example of only recovering if the url doesn't change, and their url was changing.
This tries to make that clearer, and gives an explicit copyable example for always attempting a recovery.
> Make it clear that the same-url logic is just an example

- content/client-lib-development-guide/features.textile
Context: https://github.com/ably/wiki/issues/222#issuecomment-334567652
> Apply maxMessageSize limit to protocolmessages, not messages, and firm up the definition

- content/realtime/connection.textile
- content/realtime/push/activate-subscribe.textile
Looks like the Swift docs were slightly out of date?
(certainly not an iOS expert here)
> Fixes some iOS Swift docs (handles renames)

- content/realtime/presence.textile
Using .on throws a warning of eminent depreciation, which can be concerning for new users (see https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/all/conversations/14795960096). Changed to .subscribe.
> Changed .on to .subscribe

- content/tutorials/token-authentication.textile
A few changes to the token auth tutorial to help with readability and a few fixes. This doesn't in any way look into the actual structure or contents:
- client server => client-server to match auth page.
- General missing and incorrect words (missing 'the', sentence structure, setup to set up when a verb, etc)
- Removed JavaScript as a language option due to it not being an option.
- British => American spelling (Minimising => minimizing, etc)
- Extra spacing removed
- We => You as per our current writing specs.
> Various gramatical changes to the token auth tutorial

- content/client-lib-development-guide/features.textile
RTN4 tells us a ConnectionEvent should be emitted but RTN4a and RTN4h both mentioned emitting ConnectionState, this PR fixes that.
> Spec should describe emitting ConnectionEvent not ConnectionState

- content/client-lib-development-guide/features.textile
Implements what we decided in [this thread](https://github.com/ably/docs/pull/424/files#r184432509) last week
> Clarify ConnectionEvent vs ConnectionState, likewise Channel

- content/tutorials/react-native-presence-publish-subscribe.textile
For website issue https://github.com/ably/website/issues/1577.
Only found a single case of RDDP. Many references exist of 'Ably platform', would we want those changed to 'Ably network'?
> RDDP changed to DSN

- content/client-lib-development-guide/features.textile
See https://github.com/ably/docs/pull/323
Messages should no longer be NACK’ed when a channel becomes detached given we can continue to publish in the detached state
> spec: Fix inconsistency with transient publishes functionality (RTL11)

- content/client-lib-development-guide/documentation-formatting-guide.textile
Added examples of both new jump_to usage and api_separator usage to doc formatting guide.
> Updated documented jump_to and api_separator usage

- content/client-lib-development-guide/features.textile
Rather belated, but here's my attempt at clarifying when a URL is included in log entries shown to users.  Specifically addressing https://github.com/ably/ably-ruby/pull/171#issuecomment-426831624 and https://github.com/ably/ably-ruby/pull/171/commits/ea425be4a855d68649a81f161c4483ce6a38ab99.
> spec: TI5 Clarify when a URL should be appended to log messages

- content/rest/_request.textile
(actually was back in march but I forgot to update the docs at the time)
> Rest#request: js lib now conforms strictly to the httppaginatedresponse spec. also clarify.

- content/realtime/channels.textile
- content/realtime/history.textile
- content/realtime/presence.textile
- content/realtime/types.textile
- content/rest/channels.textile
- content/rest/history.textile
- content/rest/presence.textile
- content/rest/types.textile
update history docs to use PaginatedRequestParams for History calls (breaking change made in v1.1
See https://github.com/ably/ably-dotnet/pull/323 for more details
> update history docs to use PaginatedRequestParams

- content/general/push/admin.textile
For issues brought up in https://github.com/ably/ably-php/pull/76#discussion_r289413576. Main point is in the code it seems `Hash` should be `array` so I've changed it here, though if I've misunderstood that please let me know.
> PHP list to list_ for push, remove () from functions

- content/realtime/channels.textile
- content/realtime/messages.textile
- content/rest-api/beta.textile
- content/rest-api/index.textile
- content/rest/channels.textile
- content/rest/messages.textile
For #684, largely involves mentioning batch publishing more extensively throughout the docs, as well as cleaning up some of the batch publish docs themselves.
Includes the addition of subscribe/publish sections in realtime/channels and history/publish in rest/channels to make the functionality even more obvious per feedback in the initial issue.
> Extend batch docs

- content/tutorials/channel-lifecycle-events.textile
- content/tutorials/channel-occupancy-events.textile
- content/tutorials/history.textile
- content/tutorials/jwt-authentication.textile
- content/tutorials/presence.textile
- content/tutorials/publish-subscribe.textile
- content/tutorials/queue-amqp-neutrino-profanity.textile
- content/tutorials/queue-amqp-wolfram-alpha.textile
- content/tutorials/queue-stomp-neutrino-profanity.textile
- content/tutorials/token-authentication.textile
- content/tutorials/webhook-chuck-norris.textile
For https://github.com/ably/tutorials/issues/47. Updates to tags for pubsub and presence tutorials, with said tags having their js lib reference corrected.
Also updates tags for other tutorials, but without a js lib change.
> Update tutorials to tags

- content/client-lib-development-guide/features.textile
- content/general/push.textile
- content/general/push/_push_intro.textile
- content/general/push/activate-subscribe.textile
- content/general/push/publish.textile
- content/general/versions/v1.0/push.textile
- content/realtime/push.textile
- content/rest/push.textile
- content/types/_push_channel.textile
This PR updates the 1.1 spec to make use of only `subscribeClient` over `subscribeClientId`, and also fixes some documentation which incorrectly makes use of `subscribeClientId`. For #697.
Also fixes `activate` method not appearing in TOC. This was due to a clashing href, which this PR fixes with https://github.com/ably/docs/pull/698/commits/7746a7823f3d07f31d3da7c1fbc6b6e123587310. For #696.
Fixes spelling error per #699.
> Correction on subscribeClientId usage

- content/general/push/activate-subscribe.textile
- content/general/push/admin.textile
- content/realtime/push.textile
- content/rest/push.textile
Adds seperator to push docs. Includes links to Push Tutorials in seperator as well.
> Add API seperator to push docs

- content/realtime/channel-metadata.textile
Previous documentation was a little vague on how exactly you make a rule for a metachannel (the regex has to be quite specific or it won't work).
Also previously contained `Please note: the *Channel Lifecycle* events are *not* supported with Reactor Webhooks` which is wrong, not sure where that came from. Replaced with a quick note that you can just create a Channel Lifecycle webhook as an easy alternative to making a message rule on [meta]channel.lifecycle
> Clarify how to make a rule for a metachannel

- content/client-lib-development-guide/features.textile
This PR adds a requirement that a late-initialised `clientId` is propagated to any existing local device registration.
> Push spec clarifications

- content/sse/index.textile
[SSE resume phase 2](https://github.com/ably/realtime/pull/2542) (and its [hefty preparatory stuff](https://github.com/ably/realtime/pull/2523)) are now deployed, so we can remove the wording about sse being in beta.
Changed `token` to `accessToken`, since afaict we're [no closer to a decision on `token` than we were a month ago](https://github.com/ably/realtime/pull/2507), and in the meantime the docs have been wrong.
Also toned down the pro-token-auth wording a bit -- it comes across as schizophrenic to have docs that say "Typically token authentication should be used" and that it's "rarely advisable" to use an api key when literally every one of the SSE code examples and tutorials we provide use basic auth. (And presumably they do so because it's a PITA to do token auth properly with …
> Misc updates to SSE docs (in particular no longer in beta)

- content/client-lib-development-guide/features.textile
Also: check deviceToken validity on each launch; handle failures to obtain a deviceToken.
Partially fixes: https://github.com/ably/realtime/issues/2544
> Push: ensure all LocalDevice details are deleted on deregistration

- Rules
Should mean code now appears correctly in all `general` routes, including the push docs.
fixes #749
> Added general route to code compilation route

- content/code/realtime/rewind.code
- content/realtime/channel-params.textile
- content/realtime/channels.textile
- content/realtime/history.textile
- data/jsbins.yaml
This is a first draft of some documentation for channel parameters, and `rewind`.
@SimonWoolf @codemerx please review for accuracy, and please add examples for SSE and MQTT.
I don't feel strongly about where this goes in the hierarchy but this seems to make sense, alongside channel-metadata.
> Channel Parameters: add first draft of documentation, including rewind

- content/tutorials/token-authentication.textile
fixes #764 if I've understood correctly.
> Added jcenter to token auth tutorial for java

- content/client-lib-development-guide/features.textile
Currently this just encodes what ably-ruby does, https://github.com/ably/ably-ruby/pull/133 .
A few obvious questions:
- the ably-ruby behaviour is to use a query string param, which Paddy points out was so it would end up in router logs. Do we want to keep that, or make it a header instead (a bit neater, but needs router changes to log it)? (Or allow both? In ably-js in particular if it's in the query string param we could replace the `rnd` xhr cachebuster with it)
- Do we want to enabled it by default? in ably-ruby it's disabled by default
> Add addRequestIds client option

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/787
ably-js implementation: https://github.com/ably/ably-js/pull/623
TODO: open issues for any realtime client lib that does bundling-while-disconnected (not sure which of them do)
> Add RTL6d7: no bundling if realtime message id set

- app/assets/javascripts/application.js
- content/client-lib-development-guide/documentation-formatting-guide.textile
- content/code/authentication/jwt-token.code
- content/core-features/authentication.textile
- content/realtime/usage.textile
- content/rest/channel-status.textile
- content/rest/usage.textile
- content/shared/_channel_metadata.textile
- data/jsbins.yaml
Going to add small fixes to this PR rather than making a load of PRs for many 1 line changes. I'll tag each commit with the issue to make it clearer what does what.
fixes #761 , currently not able to run the actual website repo locally so can only check locally `docs`, if it behaves like everything else this should work to remove number formatting + divide up the page a bit better until our full rework.
fixes #751 adding ChannelStatus code examples for all languages.
fixes #759 , note on what `channelId` is.
fixes #760 's indentation issue.
fixes #580 , removes incorrect claim that `rest.clientId` and `realtime.clientId` exist (is actually `rest.auth.clientId`)
fixes #578, adds JSBin example for JWT token generation + usage
> Various small doc issue fixes

- data/compare.yaml
I removed specific pricing comparisons from compare table. We're updating the pricing and this section doesn't add much value anyway.
@tomczoink can you please just give this a once over and then merge into master if all is OK?
I've also updated the comparisons that don't live in this table directly in the website repo.
> Removes specific pricing from comparisons

- content/client-lib-development-guide/features.textile
From https://github.com/ably/ably-java/commit/257a6c1e481c572de3d365e3c40c29a7d17632ca:
> This isn't in the spec (yet). The previous behavior causes the
activation callback to be called right away with no error, while a
previous activation is ongoing. The correct behavior is to serialize
the calls, so that the second call is processed after the first has
finished.
> At the same time, remove the CalledActivate enqueue from
NotActivated, which relied on the old behavior but wasn't doing
anything really useful. (This needs to be removed from the spec
too.)
So, this:
```js
rest.push.activate((err) => {
console.log('First:', err);
});
// Push is now syncing the existing registration.
rest.push.activate((err) => {
console.log('Second:', err);
});
// Syncing finishes.
```
Before,
```
Second: …
```
> Push: Fix activate() behavior while syncing device

- content/realtime/channel-params.textile
Adding documentation for the `delta` channel parameter similar to what we have for the `rewind` one.
> Documenting the delta channel param

- content/partials/core-features/_authentication_capabilities.textile
- content/partials/shared/_channel_enumeration.textile
It's nothing to do with subscribing to metachannels (if you want to subscribe to [meta]channel.lifecycle, you need the 'subscribe' capability for [meta]channel.lifecycle, as with any other channel). The channel-metadata capability is just about the channel status and channel enumeration apis. (The actual channel metadata docs get this right).
And add a paragraph of explanation about the different ways some of the capabilities work, as I'm not sure it's obvious to new users.
Also fixed a statement about permissions for channel enumeration wrt prefixes that I think we intended to implement but never got around to it.
> Capabilities docs: fix description of channel-metadata capability

- README.md
Use `integration/1.2`, not `master-1-2`, for our 1.2 staging branch.
> Rename integration branches

- content/client-lib-development-guide/versions/features-1-1__1-2.diff
- content/client-lib-development-guide/versions/v1.1/features.textile
- content/client-lib-development-guide/versions/v1.1/protocol.textile
- lib/helpers/versions_helper.rb
- Updates the client lib spec to v1.2, adding in a diff and v1.1 folder
- Adds seperate versioning for client lib folder and doc folders, so as to allow the version of the spec to change prior to the version of the rest of the docs. This can be easily extended to other folders in the future if needed
The 1.2 spec changes have been taken from https://github.com/ably/docs/pull/843.
> Updated client lib spec to v1.2

- content/client-lib-development-guide/features.textile
They have defaults in the API, so it shouldn't be mandatory to provide them in the libraries.
`end` was already marked as `api-default` which implicitly makes it optional, but only in the IDL.
> Client libs spec: Optional Rest.stats.start/end.

- layouts/_head.html.erb
We are not currently tracking users who visit this domain, and although we do not link to it expressly, it is also not gated in anyway. Additionally this has been web crawled and appearing on Google because the lack of a robots.txt file until recently.
There is no concern of this tracking being duplicated to ably.io/documentation because this file is not something that is passed on.
> [WEB-381] Add GA tracking to docs.ably.io

- content/realtime/channels/channel-parameters/rewind.textile
The params key was missing from the JS demo in the rewind documentation which broke the demo, now added in
> missing params key in js example on rewind documentation, added in

- README.md
- content/code/hub-product/http-javascript.code
- content/code/hub-product/native-sdks-javascript.code
- content/code/hub-product/native-sdks-nodejs.code
- content/code/hub-product/sse-nodejs.code
- data/jsbins.yaml
*Hub products that require JsBin assets.*
Please note:
- These samples are based on an existing .code example, where the javascript portion was replaced with the respective code snippet
- The HTML section will need to be reviewed we may require copy updates.
- ANY script change will need to be communicated upstream, so that the website UI matches the JSBin content. We may need to merge this branch early (to QA the TRY IT button has the correct URL) WDYT?
- The snippet tokens (aka API_KEY and FULLY_QUALIFIED_CHANNEL_NAME) will not be dynamically replaced. The *channel name* (if it is present) is replaced at runtime, and our JSBin assets require pre-rendered assets. (ask @fliptopbox or @kennethkalmer for details) 
*These assets will not be available to the website until they have been …
> [FEA-495] hub product code samples

- content/root/quick-start-guide.textile
Caused by a formatting regression from 82ff1a415a9d where removing trailing whitespace broke the code sample.
Broken:
Fixed:
> Fix Ruby code sample in the quick start

- content/rest-api/index.textile
- content/rest-api/versions/v0.8/index.textile
- content/rest-api/versions/v1.0/index.textile
- content/rest-api/versions/v1.1/index.textile
[DOC-11] Enforce syntax consistency for API requests that require substitution.
[DOC-11]: https://ably.atlassian.net/browse/DOC-11
> [DOC-11] Fix keyName channel id and device id syntax

- content/general/events.textile
- data/redirects.yaml
The old pages we had for webhooks and functions will now re-direct to the event pages that cover everything needed.
> Add redirects for old webhook/function pages

- content/client-lib-development-guide/features.textile
Fixes https://github.com/ably/docs/issues/437
Example implementation in https://github.com/ably/ably-js/pull/672
> Only allow channels.release() for channels in an inactive( initialized, detached, or failed) state

- content/partials/shared/_channel_enumeration.textile
context: https://github.com/ably/realtime/issues/3160
as we haven't yet decided on how enumeration will work with decoupling, I settled for adding caveats to allow us to return less results and/or duplicated results in the future, even if we don't currently do so.
> Channel Enumeration API: add lots of warnings and caveats

- content/client-lib-development-guide/features.textile
- content/realtime/history.textile
- content/realtime/presence.textile
Remove references to the untilAttach param in the docs for presence history.
Context: https://github.com/ably/realtime/issues/3069#issuecomment-707279282 . Literally no-one uses it, because there's no usecase for it, since you get a full presence sync when you attach. And it adds complexity to the server. So I intend to take advantage of the fact that no-one uses it to remove support for it without breaking anyone's code.
The only snag is that ably-dotnet for some reason includes `untilAttach` as a standalone parameter to the history() call rather than just being one of the other params, so that can't be removed without a breaking change. So for that client lib I've left it in the documentation and marked it as deprecated. We should add new versions of the method that don't take that …
> Presence.history: remove untilAttach param

- content/general/push.textile
- content/realtime/channel-metadata.textile
I think the only major customer visible changes outside of the dashboard is the push metachannel. This isn't currently enabled and is gated on https://ably.atlassian.net/browse/FEA-408.
> Add push log metachannel

- content/core-features/channels.textile
- content/core-features/versions/v1.1/channels.textile
- First commit to check access. 
- Fixes minor typo: "it's" is *always* "it is" (which is not what we want here).
* [page to review](https://ably-docs-tony-minor-fi-quv3zv.herokuapp.com/core-features/channels/)
> Minor typo fix

- lib/documentation_languages.rb
On the language selector the case for JavaScript was incorrectly specified as "Javascript". This PR changes only the text displayed on the selector.
Go to any page such as Channels that has the code selector. Check that the JavaScript entry on the selector displays JavaScript.
* [Page to review](https://ably-docs-fix-doc-229-c-txkawm.herokuapp.com/realtime/channels/)
> Fix: corrects case for JavaScript on selector

- content/client-lib-development-guide/documentation-formatting-guide.textile
- content/tutorials/history.textile
- content/tutorials/index.textile
- layouts/_head.html.erb
Content team need to add metadata to the docs content published.  This is a blocker for them so I wanted to unblock them.
Note there is an associated website PR to come.
See https://github.com/ably/website/pull/3524.
> [WEB-408] - Support SEO metadata

- content/client-lib-development-guide/documentation-formatting-guide.textile
Spotted by @fliptopbox right after merging #1016.
Although this didn't cause a rendering issue on docs.ably.io, it might on the website. However, the formatting guide isn't directly accessible from the website navigation.
> fix: missing trailing `---` in formatting guide

- content/tutorials/realtime-cryptocurrency-app-flutter.textile
- data/redirects.yaml
Fixes link that causes doc tool crash when run locally. 
This crash does NOT occur if testing and reviewing locally with website, it occurs only if you run the nanoc tool.
Details in [DOC-260](https://ably.atlassian.net/browse/DOC-260).
Checkout branch locally and run `bundle exec nanoc live -p 4000`, and then `nanoc check elinks` nanoc should NOT crash.
> Fix link that causes doc crash

- content/asset-tracking/index.textile
Fixes the link `Using the SDKs` on https://ably.com/documentation/asset-tracking#see-also
> DOC-311: Fix broken link in asset tracking

- content/tutorials/react-native-presence-publish-subscribe.textile
As part of work to deprecate `ably-js-react-native` (see [ably-js issue](https://github.com/ably/ably-js/issues/743)) this PR replaces all references to the react-native SDK.
> Remove references to ably-js-react-native from tutorials

- README.md
The current instructions for publishing the documentation to the website under `/documentation/` are out of date. This PR updates them with the new process.
> Update instructions for publishing docs to the website

- content/client-lib-development-guide/features.textile
"Aborts the retry process" suggests that we should just abandon the
whole connection state recovery logic. In implementation terms, this
may be translated to breaking an actual loop with the associated
connection state TTL ([this happened recently in Go](https://github.com/ably/ably-go/pull/297)).
This doesn't make much sense, and it's really not useful. What should
happen instead is that the reconnection loop should skip the wait, and
attempt the next try right away.
> RTN11c: Explicit connect should keep trying to recover connection state

- content/general/versions/v1.0/push.textile
- content/partials/general/push/_push_intro.textile
- content/partials/versions/v1.1/general/push/_push_intro.textile
Just a very small change, because OS X was renamed to macOS in 2016.
> replace OS X with macOS

- content/compare/fanout-vs-pubnub.textile
- content/partials/compare/security/_pubnub_details.textile
- data/compare.yaml
See: [DOC-320](https://ably.atlassian.net/browse/DOC-320)
Removed the ISO 27001 entry, updated the SOC 2 compliance (we're now compliant), and fixed the SOC syntax (it's type 1 or 2, not I or II).
The [other comparisons](https://ably.com/compare/all) also need looking at, but those aren't part of the docs repo (they're hosted in [Contentful](http://contentful.com/) and managed by the Content team).
> Fix compliance claims in comparison pages

- content/partials/general/events/_batched_events.textile
This PR corrects errors in the `source` for the batched webhook examples. There are also some minor changes to readability in the examples and associated text.
The updated page can be viewed [here](http://ably-docs-pr-1108.herokuapp.com/general/events/#examples) and compared to the live version [here](https://ably.com/documentation/general/events#examples).
> DOC-299: Correct and update webhook batched event payload examples

- content/core-features/authentication.textile
- content/core-features/versions/v1.1/authentication.textile
I noticed a few spots where the API key was not a string literal, so if a user tried to run it, it won't actually work. Adding quotation marks will fix it.
Going from
```js
var signature = hash((base64Header + "." + base64Claims), pSgEzQDIR1JKtCYC);
```
to
```js
var signature = hash((base64Header + "." + base64Claims), "pSgEzQDIR1JKtCYC");
```
> Add quotation marks to make sure the code can run (Javascript)

- content/asset-tracking/using-the-sdks.textile
Part of work from renaming `ably-asset-tracking-cocoa` to `ably-asset-tracking-swift` at https://github.com/ably/ably-asset-tracking-cocoa/issues/151
> Update link from ably-asset-tracking-cocoa to Swift

- content/partials/tutorials/_step-1-create-app-and-api-key.textile
- content/partials/tutorials/_step-1-setup-free-account.textile
- content/tutorials/android-push-notifications.textile
- content/tutorials/channel-enumeration-rest.textile
- content/tutorials/channel-lifecycle-events.textile
- content/tutorials/channel-occupancy-events.textile
- content/tutorials/channel-rewind.textile
- content/tutorials/encryption.textile
- content/tutorials/history.textile
- content/tutorials/jwt-authentication.textile
- content/tutorials/mqtt-snake.textile
- content/tutorials/newsfeed-react.textile
- content/tutorials/presence.textile
- content/tutorials/publish-subscribe.textile
- content/tutorials/pubnub-adapter.textile
- content/tutorials/pusher-adapter.textile
- content/tutorials/queue-amqp-neutrino-profanity.textile
- content/tutorials/queue-amqp-wolfram-alpha.textile
- content/tutorials/queue-stomp-neutrino-profanity.textile
- content/tutorials/react-native-presence-publish-subscribe.textile
- content/tutorials/reactjs-realtime-commenting.textile
- content/tutorials/reactor-event-cloudflare.textile
- content/tutorials/reactor-event-ifttt.textile
- content/tutorials/tfl-live-tracking-fitbit.textile
- content/tutorials/token-authentication.textile
- content/tutorials/web-rtc-data-channels.textile
- content/tutorials/web-rtc-file-transfer.textile
- content/tutorials/web-rtc-screen-sharing.textile
- content/tutorials/web-rtc-video-calling.textile
- content/tutorials/webhook-chuck-norris.textile
[DOC-345](https://ably.atlassian.net/browse/DOC-345)
Update step 1 tutorial partial to reflect changed UI, choose either to create an app or use an existing one, and clarify info about Ably apps and API keys.
Ensure that tutorials using the existing partial now use the new one.
> Replace existing tutorial step 1 partial

- README_INTERNAL.md
- app/assets/javascripts/application.js
- config/config.rb
- config/jsbin_config.example.yaml
- content/client-lib-development-guide/documentation-formatting-guide.textile
- content/code-index.textile
Change jsbin domain from jsbin.ably.io to jsbin.ably.com.
* [Review app](https://ably-docs-pr-925.herokuapp.com/)
> [FEA-547] Change jsbin domain from ably.io to ably.com (AUGUST)

- content/general/push/activate-subscribe.textile
- content/general/push/admin.textile
2 fixes:
- Typo: deliver instead of delivery
- Correction: Both realtime and rest have the `push` property.
> Push notifications documentation improvements

- content/asset-tracking/using-the-sdks.textile
See [DOC-357](https://ably.atlassian.net/browse/DOC-357)
Removed `GOOGLE_MAPS_API_KEY` (not required) and clarify difference between the two MapBox tokens.
> Update API key requirements

- content/root/how-ably-works.textile
This PR corrects a typo in "How Ably Works" and rewords the opening paragraph for improved readability. It also adds `meta_keywords` and `meta_description` to the page.
The page can be reviewed [here](https://ably-docs-pr-1130.herokuapp.com/how-ably-works/).
> DOC-271: Fix typo in how ably works

- content/control-api/curl-examples.textile
- content/control-api/index.textile
- content/control-api/testing-with-postman.textile
Adds development status section to Control API docs. 
* [JIRA ticket](https://ably.atlassian.net/browse/DOC-393).
Check each page of the Control API docs. There should now be a development status section indicated Control API is in Beta.
* [Page to review](https://ably-docs-pr-1137.herokuapp.com/control-api/)
> Add beta notice to control api docs

- content/tutorials/publish-subscribe.textile
There were breaking changes to the Ably Go library with the release of v1.2.0. This PR updates the Go Pub/Sub tutorial to make use of the new library version.
Check that there's no formatting errors.
* [Pub/Sub tutorial for Go](https://ably-docs-pr-1138.herokuapp.com/tutorials/publish-subscribe/)
> Update the Pub/Sub tutorial for Go to 1.2.0

- content/tutorials/publish-subscribe.textile
The live demo refers to a QR code which is not visible, so I'm suggesting that we just remove it.
Because it's not clear from the formatting that there is an editable text box and a button, I've adjusted the layout of and captions for each of those.
* [DOC-398](https://ably.atlassian.net/browse/DOC-398).
Please check that reference to QR code is removed and that it is clear how to run the live demo.
* [Page to review](https://doc-398-remove-qr-code.herokuapp.com/tutorials/publish-subscribe#live-demo)
> Tidy pub/sub tutorial live demo instructions

- content/client-lib-development-guide/features.textile
The feature spec currently contradicts itself regarding DeviceDetails, and its led to inconsistency between SDKs. In one section, it doesn’t specify `DeviceDetails.deviceSecret`, but in the interface definition, it does, deviceSecret: String?. From reading RSH8b (below), we should put deviceSecret in LocalDevice, not in DeviceDetails.
> (RSH8b) The LocalDevice id and deviceSecret attributes are generated, and persisted as part of the LocalDevice state, when required by step (RSH3a2b) in the Activation State Machine. At that time, the clientId attribute is also initialised, if the client is identified according to (RSA7).
Unfortunately, ably-java and cocoa have diverged. Cocoa has put the deviceSecret in deviceDetails (wrong, but followed the interface definition), and java has put the …
> Move deviceSecret to LocalDevice, out of DeviceDetails

- content/client-lib-development-guide/features.textile
`channels#release` in should raise error in `realtime` for specific states and should return without error in `rest`
[RSN4c](https://docs.ably.io/client-lib-development-guide/features/#RSN4c) should be put under [RTS4](https://docs.ably.io/client-lib-development-guide/features/#RTS4)
Discussion: https://ably-real-time.slack.com/archives/C030C5YLY/p1615715227000800
> remove RSN4c, add RTS4b (channels#release)

- content/root/quick-start-guide.textile
This PR adds a note to the Quickstart about avoiding the use of basic authentication on the client-side. See [JIRA](https://ably.atlassian.net/browse/DOC-88) for further information.
The note can be reviewed in the [Quickstart](https://ably-docs-pr-1162.herokuapp.com/quick-start-guide/).
> DOC-88: Add a note to Quickstart about using basic auth

- content/root/quick-start-guide.textile
This PR fixes the Ruby connection example code so that it generates a demo API key when published. See [JIRA](https://ably.atlassian.net/browse/DOC-369) for further information.
Run the website locally against this PR and check that the Ruby code block generates a demo API key.
> DOC-369: Update Ruby connection example to generate demo API key in Quickstart

- content/code/quick-start-guide/close.code
- content/code/quick-start-guide/connect.code
- content/code/quick-start-guide/send-message.code
- content/root/quick-start-guide.textile
- data/jsbins.yaml
This PR updates the existing JSBins for the quickstart to modern JavaScript. It also adds a new JSBin for closing a connection to Ably. See [JIRA](https://ably.atlassian.net/browse/DOC-367) for further information. 
Note: I have raised [this JIRA](https://ably.atlassian.net/browse/DOC-456) to look at removing JQuery from JSBin as a future improvement.
The [quickstart](https://ably-docs-pr-1166.herokuapp.com/quick-start-guide/) should be checked to ensure the new JSBins are correctly linked.
The new JSBins can be checked from that page or individually using:
* [Connect](https://jsbin.ably.com/uhexob/1/edit)
* [Publish and …
> DOC-367: Update quickstart JSBins

- app.json
It is currently not possible to generate a review app for pull requests on this repo because we specify that we want the review apps to be on "free" dynos. We don't need this restriction and currently it prevents us from building review apps.
The review app for the PR should build and be accessible.
* [https://ably-docs-pr-1171.herokuapp.com/](https://ably-docs-pr-1171.herokuapp.com/)
> Remove review app restrictions from app.json

- content/tutorials/jwt-authentication.textile
This PR just adds two small lines of code into the JWT tutorial. Previously it was a requirement to look at the GitHub Step 2 commit in order to get the full code. With this change all code is available within the tutorial itself.
See [JIRA](https://ably.atlassian.net/browse/DOC-295) for further information.
View the [JWT tutorial](https://ably-docs-pr-1176.herokuapp.com/tutorials/jwt-authentication) to review this change. Following the steps should no longer require copying any code from GitHub.
> DOC-295: Add missing code into JWT tutorial text

- app/assets/stylesheets/documentation.scss
- content/asset-tracking/example-apps.textile
- content/asset-tracking/index.textile
- content/asset-tracking/using-the-sdks.textile
- content/client-lib-development-guide/features.textile
- lib/documentation_languages.rb
JIRA https://ably.atlassian.net/browse/WEB-1743
For part two see: https://github.com/ably/website/pull/4004
Need a 'generic' rendering of code blocks for unsupported languages
It would be good to have a "Generic" or "Plain" code block type for source code that doesn't require syntax highlighting but is still rendered in monospace, with appropriate line breaks. (Currently, if you leave out the language type then, in the website, line breaks disappear and in docs.ably.com, everything is highlighted in the same way as inline code is).
- Visit `/documentation/client-lib-development-guide/features#idl`
- You …
> [WEB-1743] Generic rendering of code blocks (part 1 of 2)

- content/partials/types/_presence_action.textile
- content/partials/versions/v0.8/types/_presence_action.textile
- content/partials/versions/v1.0/types/_presence_action.textile
- content/partials/versions/v1.1/types/_presence_action.textile
This makes it consistent with all other languages. For example, nodeJS has:
```js
var PresenceActions = [
'absent', // (reserved for internal use)
'present',
'enter',
'leave',
'update'
]
```
Please see [Presence action](https://ably.com/documentation/realtime/presence#presence-action) and toggle between the different languages in the black top bar at the top to compare languages:
> Add `// reserved for internal use` comments to `ARTPresenceAbsent` and `Absent` enum cases

- content/client-lib-development-guide/features.textile
- content/client-lib-development-guide/versions/v1.1/features.textile
By looking inside ably-java, ably-cocoa and go-services repo, we can see that there are no usages of `X-Ably-DeviceIdentityToken`, only `X-Ably-DeviceToken`. This PR fixes the feature spec header string, but also adds a note about this mistaken documentation for future reference.
WDYT @paddybyers, I think you have the most context here.
> Document correct header `X-Ably-DeviceToken` and add note about wrongly documented `X-Ably-DeviceIdentityToken`

- content/root/quick-start-guide.textile
This PR fixes the URL for the JavaScript CDN in the quickstart guide. See [JIRA](https://ably.atlassian.net/browse/DOC-482) for further information.
To review this PR, visit [this page](http://ably-docs-pr-1196.herokuapp.com/quick-start-guide) and view the page in JavaScript.
> DOC-482: Fix quickstart JavaScript URL

- content/client-lib-development-guide/features.textile
Clarify that HAS_PRESENCE doesn't mean that there is definitely ≥1 present member, it just means that the client lib should expect a SYNC (and so that presence ops that wait_for_sync need to wait for that, etc.).
Context: third bullet point of https://github.com/ably/realtime/pull/3326
> Spec: Slight change in semantics to RTP1 (HAS_PRESENCE)

- content/core-features/occupancy.textile
- content/core-features/presence.textile
This PR adds an occupancy topic to the core features and a paragraph detailing the difference between presence and occupancy to avoid confusion between the two features. See [JIRA](https://ably.atlassian.net/browse/DOC-390) for further information.
View the new [occupancy topic](http://ably-docs-pr-1209.herokuapp.com/core-features/occupancy) to review this PR.
> DOC-390: Add an occupancy topic to core features

- content/general/limits.textile
This PR attempts to address [this comment](https://github.com/ably/docs/pull/1101#issuecomment-907109874) from the PR introducing limits. The intention is to be consistent with terminology and not refer to instantaneous rate limits as "per second limits".
This PR can be reviewed by viewing the [limits](http://ably-docs-pr-1199.herokuapp.com/general/limits) page.
> DOC-480: Refer to "per second" limits as instantaneous rate limits

- content/realtime/connection.textile
- content/root/quick-start-guide.textile
Small CSharp API usage correction.  In the latest version of the SDK when
establishing a callback for 'Connection' events the first parameter should
be a 'ConnetionEvent' and not a 'ConnectionState'.
I have only changed this for the latest version of the docs.  I need to do
more research and see if this applies to older versions of the SDK.
> CSharp API usage correction

- content/client-lib-development-guide/features.textile
The `agents` client option will only be offered by SDKs which need to be subsequently wrapped by other SDKs (i.e. other Ably SDKs are dependent upon them).
Currently we know that this means:
- [ably-java](https://github.com/ably/ably-java) and [ably-cocoa](https://github.com/ably/ably-cocoa): wrapped by [ably-flutter](https://github.com/ably/ably-flutter), [ably-asset-tracking-android](https://github.com/ably/ably-asset-tracking-android) and [ably-asset-tracking-swift](https://github.com/ably/ably-asset-tracking-swift).
- [ably-js](https://github.com/ably/ably-js): wrapped by [ably-asset-tracking-js](https://github.com/ably/ably-asset-tracking-js)
The prototype for this interface is in `ably-java` [here](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/types/Client …
> Add agents client option

- content/tutorials/sse-and-http-streaming.textile
This PR removes the live demo section of the SSE demo as it was pointing to an inaccessible Glitch project that is currently not working. See [JIRA](https://ably.atlassian.net/browse/DOC-531) for further information.
View the [SSE tutorial](https://ably-docs-pr-1249.herokuapp.com/tutorials/sse-and-http-streaming) to review this PR.
> DOC-531: Remove broken SSE tutorial live demo section

- content/api-streamer/producer.textile
- content/rest/channels.textile
- content/rest/history.textile
- content/rest/messages.textile
This PR removes all instances where channel options are passed as `nil` in the Go code samples. This is because passing them as `nil` will return an error. See [JIRA](https://ably.atlassian.net/browse/DOC-460) for further information.
To review this PR, check the following pages viewed in Go:
* [API Streamer](https://ably-docs-pr-1246.herokuapp.com/documentation/api-streamer/producer)
* [rest/channels](https://ably-docs-pr-1246.herokuapp.com/documentation/rest/channels)
* [rest/history](https://ably-docs-pr-1246.herokuapp.com/documentation/rest/history)
* [rest/messages](https://ably-docs-pr-1246.herokuapp.com/documentation/rest/messages)
> DOC-460: Remove occurrences of passing channel options as nil in Go

- content/rest/authentication.textile
This PR corrects the "Jump To" labels for the REST authentication API reference.
To review this PR, check the [REST authentication page](https://ably-docs-pr-1247.herokuapp.com/documentation/rest/authentication).
> DOC-530: Correct navigation headings for authentication API reference

- content/root/best-practice-guide.textile
This PR adds an unsubscribe versus detach section to the best practice guide to explain the differences and things to be aware of. See [JIRA](https://ably.atlassian.net/browse/DOC-383) for further information.
View the [best practice guide](https://ably-docs-pr-1252.herokuapp.com/best-practice-guide#detach-vs-unsubscribe) to review this PR.
> DOC-383: Add unsubscribe versus detach section

- content/general/push.textile
- content/partials/general/push/_push_intro.textile
Make it clear that the W3C Push API is experimental, requires us to grant access to it, and that we're interested in feedback.
Removed the "Contact us" link from the partial that populates the table at `/general/push/#platform-support`, to encourage the reader to read the note in `/general/push/#download`.
* [DOC-204](https://ably.atlassian.net/browse/DOC-204).
Read sections 4 and 4.1 in the review app:
* [Push API platform support](https://ably-docs-pr-1254.herokuapp.com/general/push/#platform-support)
> Warn about using experimental W3C Push API

- content/rest/channels.textile
- content/rest/encryption.textile
This PR updates Go code blocks to add support for `CipherParams` and `ChannelOptions`. See [JIRA](https://ably.atlassian.net/browse/DOC-459) for further information.
Two pages have been updated in this PR:
* [REST channels](https://ably-docs-pr-1254.herokuapp.com/rest/channels)
* [REST encryption](https://ably-docs-pr-1254.herokuapp.com/rest/encryption)
> DOC-459: Update go code blocks to add support for CipherParams and ChannelOptions

- content/partials/types/_paginated_result.textile
This PR changes the `PaginatedResult` partial to link to itself. The same partial is used in `realtime/types` so redirecting users there isn't necessary when they're viewing it within context. See [JIRA](https://ably.atlassian.net/browse/DOC-452) for further information.
To review this PR, check any page using the paginated result partial, for example:
[Realtime/channels](https://ably-docs-pr-1258.herokuapp.com/realtime/channels#paginated-result)
> DOC-452: PaginatedResult partial can link to itself rather than to types

- content/realtime/channels.textile
This PR adds a section discussing the differences and things to be aware of between attaching, subscribing, unsubscribing and detaching from a channel. These topics were recently added to the best practice guide, however it makes sense to include them in the realtime documentation too. See [JIRA](https://ably.atlassian.net/browse/DOC-553) for further information.
View the [realtime channels](https://ably-docs-pr-1256.herokuapp.com/realtime/channels#attach-vs-subscribe) page to review this PR.
> DOC-553: Add attach vs subscribe to realtime channels section

- content/realtime/channels.textile
This PR adds a section to the realtime channel documentation on detaching from channels. See [JIRA](https://ably.atlassian.net/browse/DOC-326) for further information. 
View the [channels](https://ably-docs-pr-1262.herokuapp.com/realtime/channels) documentation to review the PR.
> DOC-326: Add a section on detaching to channels docs

- README_INTERNAL.md
This PR adds a section to the internal README for running the Nanoc `check` command to check the documentation for any broken links.
> DOC-391: Add instructions for running nanoc link checks

- config/tutorials/tutorials.json
This PR updates the tutorial homepage to refer to "Ably Client Library SDKs" instead of "Ably native SDKs" to conform to the writing style guide.
Run this branch locally against the website and visit `/tutorials` to review this PR.
> DOC-578: Reword use of native SDKs to client library SDKs for tutorial homepage

- content/core-features/authentication.textile
This PR updates the authentication text to state that API Keys can be created programmatically using the Control API.
See [JIRA](https://ably.atlassian.net/browse/DOC-479) for further information.
View the [authentication page](https://ably-docs-pr-1285.herokuapp.com/core-features/authentication#capabilities-explained) to review this PR.
> DOC-479: Add use of Control API to authentication information 

- content/general/kafka-connector.textile
This PR removes the 'enterprise-only' note from the Kafka Connector documentation. 
View the [Kafka Connector](https://ably-docs-pr-1294.herokuapp.com/general/kafka-connector/) page to review this PR.
> DOC-662: Remove statement about enterprise-only from Kafka connector

- content/tutorials/_ably-async-await-post.textile
- content/tutorials/_ably-aws-web-components.textile
- content/tutorials/_ably-flutter-plugin.textile
- content/tutorials/_access-control-with-ablyD.textile
- content/tutorials/_airtable-database-realtime-messages.textile
- content/tutorials/_building-a-realtime-sms-voting-app-in-the-web.textile
- content/tutorials/_building-serverless-chat-app-part-1.textile
- content/tutorials/_building-serverless-chat-app-part-2.textile
- content/tutorials/_event-streaming-with-redis-and-golang.textile
- content/tutorials/_iot-wearable-azure-cognitive-services-ably.textile
- content/tutorials/_myth-busting-jamstack-cant-handle-dynamic-content.textile
- content/tutorials/_peer-to-peer-game-with-pub-sub.textile
- content/tutorials/_pubsub-golang.textile
- content/tutorials/_realtime-chat-app-nextjs-vercel.textile
- content/tutorials/_realtime-fullstack-app-dotnet-angular-mongodb.textile
- content/tutorials/_realtime-ticket-booking-kafka.textile
- content/tutorials/_showcase-ably-postgres-connector.textile
- content/tutorials/_testing-ws-sockjs-building-web-app.textile
- content/tutorials/_vue-realtime-collaboration-app.textile
- content/tutorials/_webrtc-signaling-fsharp-fable-ably.textile
- content/tutorials/_websockets-pubsub-spring-boot.textile
This PR adds a number of tutorials on the Ably blog to the dev docs tutorials page. The Ably blog pieces are treated as external tutorials.
https://ably.atlassian.net/browse/WEB-2163
Will need to be tested under nanoc and web view.
Navigate to:
* [tutorials](https://ably-docs-pr-1292.herokuapp.com/tutorials/)
> [WEB-2163] Add developer blogs to Tutorials

- content/tutorials/encryption.textile
- content/tutorials/presence.textile
- content/tutorials/publish-subscribe.textile
- content/tutorials/web-rtc-data-channels.textile
- content/tutorials/web-rtc-file-transfer.textile
- content/tutorials/web-rtc-screen-sharing.textile
- content/tutorials/web-rtc-video-calling.textile
- this code used the Google URL shortner, a service that was closed down in 2019 https://developers.google.com/apps-script/advanced/url-shortener
- the error the call to this service made broke the whole QR code functionality, so this was not working since 2019
- because this is not necessary for the page, and should be done in a lot easier to debug fashion, we decided to remove this feature and potentially bring it back when tutorials are re-platformed
- this will prevent an obnoxious error in Sentry https://sentry.io/organizations/ably-uq/issues/2976824031/?project=6156014&query=is%3Aunresolved
- and reduce the page size by around 50kb (gapi …
> Remove QR code functionality

- content/root/how-ably-works.textile
While looking through "how ably works", I've noticed in the presence section, that we do not specify a time unit for how long presence events are stored on disk. I assume this should be `hours`.
See diff
> docs: add missing time unit

- content/client-lib-development-guide/index.textile
There was a tiny spelling mistake on the Client Library Development Guide page ('ot' instead of 'or'). This PR fixes that.
* [Page to review](https://github.com/ably/docs/blob/74e6dc2cea543b4726da6be3d66f10c12c6365c0/content/client-lib-development-guide/index.textile)
> Fix spelling mistake

- content/realtime/channels.textile
- content/root/best-practice-guide.textile
This PR documents channel mode flags in the realtime channels page and also updates the best practice guide for being present without subscribing.
To review this PR, see:
* [Realtime channels](http://ably-docs-doc-570-chann-qn6r5t.herokuapp.com/realtime/channels/#setting-channel-mode-flags)
* [Best practice guide](https://ably-docs-doc-570-chann-qn6r5t.herokuapp.com/best-practice-guide/#being-present-without-subscribing-to-presence)
> DOC-570: Document channel mode flags

- content/realtime/channels.textile
This PR fixes a parameter that was incorrectly labelled as `Flutter` causing the parameter to be unlabelled in other languages.
Check the [`publish()` method parameters](http://ably-docs-doc-498-missi-2ww98b.herokuapp.com/realtime/channels/#publish) are all correctly labelled.
> DOC-498: Fix incorrect lang property to display message parameter

- content/code/realtime/rewind.code
- content/realtime/history.textile
- data/jsbins.yaml
This PR updates the description of the rewind feature on the realtime history page to reflect the use of channel parameters. It also updates the associated JSBin to reflect this too.
See [JIRA](https://ably.atlassian.net/browse/DOC-476) for further information.
View the [realtime/history](http://ably-docs-doc-476-histo-gnxoh9.herokuapp.com/realtime/history/#rewind) page to review this PR.
> DOC-476: Update description of rewind on history page to reflect parameters

- content/asset-tracking/index.textile
Add note on Swift SDK limitations. The associated PR does not have a description, but the code comment is:
```
It's not possible to change time interval for location updates in `CLLocationManager` from Apple `CoreLocation` framework.
Documentation: https://developer.apple.com/documentation/corelocation/cllocationmanager
```
Ticket to update docs:
* [DOC-654](https://ably.atlassian.net/browse/DOC-654)
In the Resolution section, see `desiredInterval` - time interval cannot be changed in the Swift SDK.
* [Page to review](https://ably-docs-doc-654-locat-i3lfik.herokuapp.com/asset-tracking/#resolution)
> DOC-654: time interval can't be changed on Swift.

- content/client-lib-development-guide/index.textile
Fixes a broken link to test API documentation on https://ably.com/documentation/client-lib-development-guide/
> Fix broken test API link

- content/mqtt/index.textile
Removes enclosing scopes (`{}`) from the MQTT code snippets. These were unnecessary, and the examples look better without them.
Code samples on this page:
* [MQTT](https://ably-docs-mqtt-remove-s-r7kvzw.herokuapp.com/mqtt/)
> Remove extraneous enclosing scopes from mqtt examples

- content/rest-api/token-request-spec.textile
This PR corrects the API key format from using a`:` as the first separator to a `.`.
> DOC-552: Correct API key format

- data/transform/index.js
Index.textile files should appear on root / paths instead of /index pages
* [Jira ticket](https://ably.atlassian.net/browse/EDX-39).
* Check that slugs are created in the appropriate way.
> EDX-39: Map index.textile files to root / paths instead of /index pages

- content/partials/shared/_channel_namespaces.textile
- content/realtime/channels.textile
- content/rest/channels.textile
[The GitHub issue](https://github.com/ably/docs/issues/836) provides more context as there was some initial confusion as to whether wildcard but wildcards are [**not** supported](https://github.com/ably/docs/issues/836#issuecomment-599473068). 
There's some [occasional customer confusion](https://github.com/ably/docs/issues/836#issuecomment-725290103) so added a simple clarification line to the channel pages.
* [Quick wins](https://ably.atlassian.net/browse/DOC-609)
* [DOC-207](https://ably.atlassian.net/browse/DOC-207).
Check clarification that channels doesn't support wildcards:
* [REST - …
> channel wildcard clarification

- content/root/quick-start-guide.textile
- Add a dedicated signup step
- Mention WebSocket related to connecting
- Small unrelated change to add missing `npm` command
- Open the quick start guide page
> Quick start guide changes to support paid campaign experiment

- content/root/quick-start-guide.textile
Minor fix to "jump to" dropdown.
Navigate to quickstart page. In the "jump to" selector select "Create Ably account" item - this should jump you down to the correct section. 
* [Quickstart](http://ably-docs-fix-toc-dropd-nmdqia.herokuapp.com/quick-start-guide/)
> Minor fix to dropdown in Quickstart

- content/root/quick-start-guide.textile
Updated the textual content to first call out signing up.
The subsequent paragraph provides alternatives e.g. use the demo API key.
> Quick start guide "Create an Ably Account works" tweaks

- content/api/realtime-sdk/stats.textile
- content/api/versions/v0.8/realtime-sdk/stats.textile
- content/api/versions/v1.0/realtime-sdk/stats.textile
- content/api/versions/v1.1/realtime-sdk/stats.textile
- content/realtime/statistics.textile
- content/realtime/versions/v0.8/statistics.textile
- content/realtime/versions/v1.0/statistics.textile
- content/realtime/versions/v1.1/statistics.textile
This PR moves the realtime stats API reference to a new `/api` section for all versions.
See [EDX-86](https://ably.atlassian.net/browse/EDX-86) for further info.
View the stats API reference pages to review this PR.
> [EDX-86]: Migrate realtime stats API reference

- gatsby-browser.js
- src/components/Article/index.js
- src/components/Layout/index.js
- src/components/Sidebar/SidebarItem.js
- src/components/Sidebar/StickySidebar.js
- src/components/Sidebar/styles.js
- tsconfig.json
Replacing all menu items with styled menu items that match our style guide.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-45).
Check that menu items render correctly per https://www.figma.com/file/4KdtIEGY2BfZPq5tT1u6D3/Migration-Guide?node-id=21%3A346
Verify that updated scrolling behaviour makes sense (in code or by checking): intended behaviour is that:
* Gatsby never takes over scrolling when moving between variations of a particular page (e.g. different language variations)
* Gatsby never takes over scrolling when moving to or from a specific section link (e.g. #channel-states)
* Gatsby scrolls user to top when viewing a …
> Edx 45 menu items

- .eslintrc.json
- src/components/blocks/external-references/A.js
- src/components/blocks/external-references/A.tsx
- src/components/blocks/external-references/__snapshots__/A.test.js.snap
- src/components/blocks/external-references/styles.css
- src/components/blocks/software/Code.js
- src/components/blocks/software/Pre.js
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Code.test.js.snap
- src/components/blocks/software/__snapshots__/Pre.test.js.snap
- src/components/blocks/software/pre-props.ts
- src/components/blocks/software/styles.css
- src/components/blocks/wrappers/CopyLink.js
- src/components/blocks/wrappers/__snapshots__/CopyLink.test.js.snap
- src/components/html-component-props.ts
- src/styles/colors.js
Updates GUI colors to be in line with migration guide: https://www.figma.com/file/4KdtIEGY2BfZPq5tT1u6D3/Migration-Guide?node-id=0%3A410
* [Jira ticket](https://ably.atlassian.net/browse/EDX-42).
Ensure that new colors match guidelines provided by Lenka here:
"I raised this with Jamie and he decided to change the colour of the hyperlinks to our GUI Blue Default and display the underline only on hover. I already updated the Migration Guide. You can use our Active Blue, Focus Blue etc. for other states."
Ensure references to the pre-migration GUI colors are no longer used in the code base.
> [EDX-42] GUI colours

- content/api/realtime-sdk.textile
- content/api/realtime-sdk/channels.textile
- content/api/realtime-sdk/push-admin.textile
- content/api/realtime-sdk/push.textile
- content/api/versions/v1.1/realtime-sdk.textile
- content/api/versions/v1.1/realtime-sdk/channels.textile
- content/api/versions/v1.1/realtime-sdk/push-admin.textile
- content/api/versions/v1.1/realtime-sdk/push.textile
- content/general/push/activate-subscribe.textile
- content/general/push/admin.textile
- content/general/push/publish.textile
- content/general/versions/v1.1/push/activate-subscribe.textile
- content/general/versions/v1.1/push/admin.textile
- content/general/versions/v1.1/push/publish.textile
- content/partials/types/_push_channel.textile
- content/partials/types/_push_device.textile
- content/partials/versions/v1.1/types/_push_channel.textile
- content/realtime/push.textile
- content/realtime/versions/v1.1/push.textile
- content/tutorials/android-push-notifications.textile
This PR moves the realtime push API reference to a new `/api` section for all versions. 
It is also consolidates the API references between `/realtime/push`, `/general/push/admin` and `/general/push/activate-subscribe`, splitting them into two separate references.
See [EDX-84](https://ably.atlassian.net/browse/EDX-84) for further info.
View the push and push-admin API reference pages to review this PR.
> [EDX-84]: Migrate realtime push API reference

- content/general/kafka-connector.textile
This PR removes the preview status from the Kafka Connector and adds links to the associated tutorial.
See [JIRA](https://ably.atlassian.net/browse/DOC-741) for further information.
View the [Kafka Connector](https://ably.com/docs/general/kafka-connector) page to review this PR.
> [DOC-741] Update Kafka Connector and remove preview status

- config/tutorials/tutorials.json
- content/tutorials/ably-kafka-connector.textile
* [DOC-742](https://ably.atlassian.net/browse/DOC-742).
Tutorial did not display on Tutorials homepage, although it does display if the URL is invoked directly. The reason is the tutorial is in the group `kafka`, but that group does not exist. This PR does two things:
1. Adds the kafka group in `tutorials.json`.
2. Also adds the tutorial to the Integrations tab (as well as the channels tab). 
The effect of this is the tutorial will be displayed as follows:
I've added multiple reviewers as I want to make sure this approach is acceptable. Thanks.
Currently, this can only be reviewed by running the webview locally.
> [DOC-742] Add kafka group to tutorials

- content/api/realtime-sdk.textile
- content/api/realtime-sdk/connection.textile
- content/api/realtime-sdk/messages.textile
- content/api/rest-sdk/messages.textile
- content/api/versions/v0.8/realtime-sdk.textile
- content/api/versions/v0.8/realtime-sdk/connection.textile
- content/api/versions/v0.8/realtime-sdk/messages.textile
- content/api/versions/v0.8/rest-sdk/messages.textile
- content/api/versions/v1.0/realtime-sdk.textile
- content/api/versions/v1.0/realtime-sdk/connection.textile
- content/api/versions/v1.0/realtime-sdk/messages.textile
- content/api/versions/v1.0/rest-sdk/messages.textile
- content/api/versions/v1.1/realtime-sdk.textile
- content/api/versions/v1.1/realtime-sdk/connection.textile
- content/api/versions/v1.1/realtime-sdk/messages.textile
- content/api/versions/v1.1/rest-sdk/messages.textile
This PR moves makes sure all page titles are consistent in the new `/api` section. Page titles should match the existing equivalents in `/rest` and `/realtime` with a few exceptions.
See [EDX-115](https://ably.atlassian.net/browse/EDX-115) for further info.
Check that all page titles are consistent.
> [EDX-115]: Make page titles consistent in new /api section

- content/general/firehose/kafka-rule.textile
* [Quick Wins](https://ably.atlassian.net/browse/DOC-609)
* [DOC-740 - List supported authentication mechanisms](https://ably.atlassian.net/browse/DOC-740).
> Added kafka auth mechanisms

- content/realtime/messages.textile
Add missing '+' to Node.js getting started snippet.
* [Bugs](https://ably.atlassian.net/browse/DOC-608).
* [DOC-759 - missing + in code](https://ably.atlassian.net/browse/DOC-759).
Check code snippet for Node.js is correct:
* docs/realtime/messages#getting-started
> code typo correction

- .editorconfig
As per the [.editorconfig spec](https://editorconfig-specification.readthedocs.io/#supported-pairs) the Indent Size property is indent_size, not indent-size. 
Check that your editor still parses .editorconfig correctly
> Fix misnamed indent_size property

- content/root/platform-customization.textile
The link on the [Platform Customization](https://ably.com/docs/platform-customization) page for "see our guide" links to the fragment "#custom-environment-setup", I think this is supposed to link to "#setting-up-a-custom-environment"
Check that the fragment on the "our guide" link now works correctly.
* Page to review: docs/platform-customization
> Fix incorrect link in Platform Customization page

- content/client-lib-development-guide/features.textile
Adds spec points for the Batch Operations functions.
* [Jira epic ticket](https://ably.atlassian.net/browse/SDK-1792).
* [Jira ticket](https://ably.atlassian.net/browse/SDK-1810).
* [Page to review](https://docs.ably.io/client-lib-development-guide/features/)
> Batch operations spec points

- content/client-lib-development-guide/features.textile
This property is deprecated in favour of `channelId`, see [internal slack thread](https://ably-real-time.slack.com/archives/CURL4U2FP/p1652783091921479).
> Feature spec: remove ChannelDetails.name

- content/client-lib-development-guide/features.textile
CHD2b was removed in #1428, this additional PR simply addresses the 'gap' in the spec IDs created by that PR.
> Feature spec: move CHD2c to CHD2b

- data/transform/pre-parser/textile-js-workarounds/index.js
- data/transform/pre-parser/textile-js-workarounds/make-implicit-ordered-list-explicit.js
- data/transform/pre-parser/textile-js-workarounds/make-implicit-ordered-list-explicit.test.js
- src/components/blocks/list/Ol.js
- src/components/blocks/list/Ul.js
- src/components/blocks/list/reset-styles.js
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
Implicit ordered lists (e.g.
1. Item one
2. Item two
3. Item three)
Are not recognised as such by textile-js. To look nice they should be:
* [Jira ticket](https://ably.atlassian.net/browse/EDX-57).
Ensure ordered lists are displayed prominently on these pages:
* [Page to review](http://localhost:8000/docs/best-practice-guide#auth)
* [Page to review](http://localhost:8000/docs/asset-tracking/example-apps?lang=swift) - note there is an issue with the h2s immediately in the blangs there, this is fixed separately by branch edx-60-some-bc-langs-not-rendering-correctly
> Edx 57 textile js ordered list workaround

- data/transform/index.js
- data/transform/parser-enhancements/index.js
- data/transform/pre-parser/textile-js-workarounds/index.js
Fixes Gatsby YAML errors (introduced by processing hyphen-led bullet point lists)
Renames 'enhancedParse' function to be more reflective of what it actually does/is for ('processAfterFrontmatterExtracted')
* [Jira ticket](https://ably.atlassian.net/browse/EDX-164).
Check that this page still has a bullet point list with the text:
- For a message event it will be a [Message](http://localhost:8000/api/realtime-sdk/types#message) object
- For a presence event it will be a [PresenceMessage](http://localhost:8000/api/realtime-sdk/types#presence-message) object
- For an error event it will be an [ErrorInfo](http://localhost:8000/api/realtime-sdk/types#error-info) object
* [Page to review](http://localhost:8000/docs/api/sse)
Make sure no errors appear after running.
> Edx 164 gatsby yaml errors

- data/transform/post-parser/blang.js
- data/transform/post-parser/blang.test.js
- data/transform/pre-parser/language/blang.raw.examples.js
- data/transform/pre-parser/language/conversions.js
- data/transform/pre-parser/language/conversions.test.js
- data/transform/pre-parser/shared-utilities/extract-indented.js
Fixes an issue with bc. blocks inside blang blocks not rendering correctly.
Achieves this by adding a newline to LANG_BLOCK token strings.
Also cleans up some linting issues in e.g. extract-indented.js.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-60).
Error was occurring on page:
* [Page to review](http://localhost:8000/docs/realtime/connection) - problem occurred on second set of code blocks.
> EDX-60: Fix bc. blocks inside blang blocks not rendering correctly.

- content/client-lib-development-guide/features.textile
Spotted a small mistake where a deprecated property `name` (see https://github.com/ably/docs/pull/1428)  was mentioned in the description for ChannelDetails. This PR removes reference to `name`
> remove reference to deprecated name property

- content/protocol-adapters/index.textile
- content/sse/index.textile
- layouts/_nav.html.erb
Adds a protocol adapter overview topic at `/protocol-adapters`.
* [EDX-122](https://ably.atlassian.net/browse/EDX-122).
If reviewing locally the overview can be found at:
http://localhost:4000/protocol-adapters/
> Add protocol adapter overview

- content/client-lib-development-guide/features.textile
Renames the `Rest` and `Realtime` classes to `RestClient` and `RealtimeClient` for consistency throughout the spec (where this terminology was already being used in some places) and to match the IDL.
> Rename client classes

- content/client-lib-development-guide/features.textile
This already exists as a user-configurable `ClientOptions` property in several of our SDKs:
- ably-java@`7fc1939`
- ably-js@`48a66d6` (been configurable there since `1b355bf` in 2015)
- ably-ruby@`f5eac15`
- ably-go@`32ed667`
- ably-flutter@`2fe0059`
Furthermore, it seems consistent to allow this timeout to be configured, the same way as the others can be.
> [EDX-156] Add `realtimeRequestTimeout` to `ClientOptions`

- content/client-lib-development-guide/features.textile
The REST `Channel` and Realtime `Channel` are two different classes (as is clear from the IDL, where they already have the names `RestChannel` and `RealtimeChannel`), so they should have different naming in the spec too. Ditto for `Presence`.
Some of the spec – e.g. RSH7 – was also already using this naming.
> Give REST and Realtime channel and presence classes unique names

- content/client-lib-development-guide/features.textile
This addresses the `Params` type that’s mentioned in the IDL as the value for `ChannelOptions.cipher` or `Crypto.getDefaultParams()`’s argument. This type is not actually defined anywhere.
I’ve taken the opportunity to turn this into a concrete `CipherParamOptions` type in the spec, because the current language of “any subset of @CipherParams@ fields…” is not correct since the types of the `key` value do not agree — in `CipherParams` it can only be a binary, but in `CipherParamsOptions` it can be a binary or a string.
I’ve taken the type name from ably/ably-js@48a66d6.
> [EDX-156] Replace the undefined Params type in IDL

- graphql-types.ts
- src/components/Sidebar/SidebarLinkMenu.js
- src/components/Sidebar/check-section-match.test.ts
- src/components/Sidebar/check-section-match.ts
- src/components/Sidebar/styles.js
- src/components/StaticQuerySidebar/left-sidebar.js
Expand the left side menu to the page that is currently active by default.
Also highlights the relevant page.
There is unusual but correct behaviour on visiting http://localhost:8000/docs/realtime/channels/channel-parameters/rewind (see Page to review).
* [Jira ticket](https://ably.atlassian.net/browse/EDX-119).
* [Check default behaviour here](http://localhost:8000/docs/rest/channels)
* [Check nested behaviour here](http://localhost:8000/docs/realtime/channels/channel-parameters/overview)
See unusual (but correct) behaviour here:
* [Unusual but correct behaviour](http://localhost:8000/docs/realtime/channels/channel-parameters/rewind) …
> [EDX-119] Sync left menu with active content

- content/client-lib-development-guide/features.textile
This adds documentation for all the stats-related types, instead of relying on links to the Ruby documentation.
Please review commit-by-commit and see commit messages for motivation and approach.
If anybody would like to suggest descriptions for the things that say `TODO description`, I'd be very grateful. Else I'll leave the TODOs as is to be addressed some other time and will make an issue for it.
> [EDX-175] Document the stats types and add to the IDL

- content/tutorials/demo-ably-tower-defense.textile
- content/tutorials/demo-serverless-websocket-quest.textile
This ticket EDU-824 has two parts, this PR and another on website https://github.com/ably/website/pull/4643
https://ably.atlassian.net/browse/EDU-824
This work add 2 new demos to the docs repository, and an update PR on the website to retrieve those.
These are also listed in this google sheet: https://docs.google.com/spreadsheets/d/1M1Tenb02zZKsVTma6WpSQ3SfW0poIzp9UDo8KnsBPUE/edit#gid=0
1. Serverless Websocket Quest (@marcduiker )
2. Unity - Tower Defence (@tomczoink )
> [EDU-824] Add 2 new demo textile files

- content/realtime/messages.textile
The message interactions SDK currently contains invalid JS that was updated in the readme of ably-js but not here, this PR brings it up to date.
* [Page to review](https://ably-docs-fix-message-i-8z7jzv.herokuapp.com/realtime/messages/#message-interactions)
> Update message interactions example to be consistent with the JS SDK

- content/root/quick-start-guide.textile
The purpose of this PR is to update the Quickstart Guide for both JavaScript and Node.js language options, to use the promises interface. 
I have also created a [repo](https://github.com/ably/quickstart-js) to contain complete working source code, as an aid to developers. The repo is linked to from both the JavaScript and Node.js language versions.
Tickets:
* Epic: [EDU-779](https://ably.atlassian.net/browse/EDU-779)
* [EDU-781](https://ably.atlassian.net/browse/EDU-781)
Review (and test) the Quickstart guide for both JavaScript and Node.js language options:
* [Quickstart guide](https://ably-docs-edu-781-updat-ef7cyq.herokuapp.com/quick-start-guide/)
> [EDU-781] - Update Quickstart code to use promises 

- content/control-api/index.textile
Add a couple of links to Control API reference from intro para as per ticket (this was a request from Gino).
* [EDU-513](https://ably.atlassian.net/browse/EDU-513).
Check two links to API reference in the intro para.
* [Control API overview](https://ably-docs-edu-513-api-r-jovhvc.herokuapp.com/control-api/)
> [EDU-513] - Add links to Control API reference guide

- content/realtime/connection.textile
- content/realtime/versions/v0.8/connection.textile
- content/realtime/versions/v1.0/connection.textile
- content/realtime/versions/v1.1/connection.textile
This PR updates the `/realtime/connection` page (for all versions) to replace occurrences of codeblocks that are nested within `blang` elements. This is to make these easier to handle in a future toolchain.
See [JIRA](https://ably.atlassian.net/browse/EDX-230) for further information.
To review, visit the [realtime/connection](https://ably-docs-edx-230-neste-b4mjmt.herokuapp.com/realtime/connection) page.
> [EDX-230] Replace nested codeblocks within blangs

- content/api/realtime-sdk/types.textile
- content/partials/types/_http_paginated_response.textile
Add missing fields to `HttpPaginatedResponse`. This topic is a partial so updating the type page updates both Realtime and Rest API refs. 
Also fixes: go lang selector was missing from realtime API ref types page.
* [EDU-35](https://ably.atlassian.net/browse/EDU-35).
Check information is present for all languages on this page:
* [HttpPaginatedResponse page](https://ably-docs-edu-35-httppa-gbi6io.herokuapp.com/api/realtime-sdk/types/#http-paginated-response)
> [EDU-35] - Add missing fields to http_paginated_response

- content/tutorials/web-rtc-screen-sharing.textile
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-608) 
* [Jira ticket](https://ably.atlassian.net/browse/EDU-866).
See my notes on the JIRA ticket. This is my first PR in docs BTW, so please be kind 🙏 
> This is going to be harder to fix than originally thought because the chrome extension is no longer available, but the tutorial appears to be predicated on using Temasys libraries. I found a replacement chrome extension [Circuit by Unify](https://chrome.google.com/webstore/detail/circuit-by-unify/mhkbaognlahkdimlfcfhbeihldmjofgg?hl=en)  but I cannot be sure that it’s sufficient to just swap it into Chrome and have the tutorial work as described.
>  
> Given that work to review which tutorials we keep up to date is ongoing, I …
> Fix broken link in WebRTC screen share tutorial 

- content/rest/usage.textile
- content/rest/versions/v0.8/usage.textile
- content/rest/versions/v1.0/usage.textile
- content/rest/versions/v1.1/usage.textile
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-608) - if applicable.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-868).
Replaced broken link with new link into API docs
* [Page to review](https://ably-docs-edu-868-fix-b-zdojju.herokuapp.com/rest/usage/)
> Fix broken link to client options section of API docs

- content/adapters/pusher.md
- content/api/rest-api.textile
- content/api/versions/v0.8/rest-api.textile
- content/api/versions/v1.0/rest-api.textile
- content/api/versions/v1.1/rest-api.textile
- content/core-features/history.textile
- content/core-features/versions/v1.1/history.textile
- content/general/push/activate-subscribe.textile
- content/general/push/publish.textile
- content/general/versions/v1.1/push/activate-subscribe.textile
- content/general/versions/v1.1/push/publish.textile
- content/partials/compare/intros/_security.textile
- content/partials/versions/v0.8/shared/_channel_namespaces.textile
- content/partials/versions/v1.0/shared/_channel_namespaces.textile
- content/partials/versions/v1.1/shared/_channel_namespaces.textile
- content/realtime/channels/channel-parameters/rewind.textile
- content/realtime/history.textile
- content/realtime/versions/v0.8/history.textile
- content/realtime/versions/v1.0/history.textile
- content/realtime/versions/v1.1/channel-params.textile
- content/realtime/versions/v1.1/history.textile
- content/rest/history.textile
- content/rest/versions/v0.8/history.textile
- content/rest/versions/v1.0/history.textile
- content/rest/versions/v1.1/history.textile
- content/root/key-concepts.textile
- content/tutorials/channel-rewind.textile
- content/tutorials/history.textile
- content/tutorials/reactjs-realtime-commenting.textile
- content/tutorials/vue-tictactoe.textile
[Original ticket](https://ably.atlassian.net/browse/EDU-257) requested mention of `persist last message` on the history page. That has been done along with:
* Cleanup of naming in several locations. Persist last message was renamed to state persistence - however, it is referred to as `persist last message` in places such as Control API, Dashboard and in error messages etc. Casuing confusion. Rename to `persist last message` to be consistent with other parts of the product.
* Instead of pointing to FAQs, point to channel rules / namespaces docs in the main docs. 
* [EDU-257](https://ably.atlassian.net/browse/EDU-257).
History page now mentions `persist last message`:
* [History](https://ably-docs-edu-257-persi-dqfbow.herokuapp.com/core-features/history/)
> [EDU-257] - Add notes on persist last message

- content/client-lib-development-guide/features.textile
The spec for this method (RSH7e) already has a description so we only needed to update the IDL.
> Add params argument to PushChannel#listSubscriptions

- content/client-lib-development-guide/features.textile
Already implemented in most SDKs, so this PR just backfills it into the features spec
> Update RealtimePresence.subscribe to support an array of actions

- content/asset-tracking/index.textile
Add a custom resolution policy section to Resolution Policy section of AAT docs.
* Epic: [EDU-634](https://ably.atlassian.net/browse/EDU-634)
* [EDU-901](https://ably.atlassian.net/browse/EDU-901).
Page to review, section custom resolution policy: 
* [AAT SDK Overview](https://ably-docs-edu-901-aat-r-kt2i8p.herokuapp.com/asset-tracking/#resolution-policy)
Note, the formatting doesn't quite look correct, but it does under the website view.
and:
> Custom resolution policy

- content/realtime/messages.textile
Correct typo.
* [EDU-897](https://ably.atlassian.net/browse/EDU-897).
Check unsubscribing from interactions.
* [Realtime - messages](https://ably-docs-edu-897-typo--igsxnq.herokuapp.com/realtime/messages/#message-interactions).
> typo correction

- content/api/realtime-sdk/presence.textile
- content/api/versions/v0.8/realtime-sdk/presence.textile
- content/api/versions/v1.0/realtime-sdk/presence.textile
- content/api/versions/v1.1/realtime-sdk/presence.textile
Fixes the Csharp prototype (data parameter should not be provided on the first prototype version).
* [EDU-113](https://ably.atlassian.net/browse/EDU-113)
Select Csharp programming language:
* [Realtime API](https://ably-docs-edu-113-fix-d-wuhl20.herokuapp.com/api/realtime-sdk/presence/#enter-client)
> [EDU-113] - Fix dotnet function prototype

- gatsby-config.ts
- gatsby-node.ts
- package.json
Custom config of a gatsby sitemap plugin to include only relevant `docs` files/pages
* [Jira ticket](https://ably.atlassian.net/browse/EDX-231).
The main `sitemap.xml` file is generated inside the `public/docs` folder on a build that references the` sitemap-0.xml` file, which, in essence, is the actual sitemap.
> EDX-231: Create sitemaps for docs

- data/createPages/index.js
- data/onCreateNode/index.js
- data/transform/index.js
- gatsby-node.ts
- graphql-types.ts
* [Jira ticket](https://ably.atlassian.net/browse/EDX-21).
1. When the following conditions are met on a .textile file to be processed, an error will be thrown: `        !isVersion &&
process.env.NODE_ENV === 'development' &&
process.env.EDITOR_WARNINGS_OFF !== 'true' &&
!newNodeData.meta.meta_description`
2. When this happens, an error should be logged, and a new Error node should be created in GraphQL
3. During the onCreatePage lifecycle, allError nodes should be queried. If any errors exist, we quietly exit the project.
The reason we do this is because if we exit the process during the onCreateNode section of the lifecycle, each …
> [EDX-21] Avoid building the site if we are missing meta descriptions

- content/general/push/admin.textile
- content/partials/general/push/_push_intro.textile
- content/partials/versions/v1.1/general/push/_push_intro.textile
Links just self-reference their own page, instead of linking out to the API reference page.
* [EDU-131](https://ably.atlassian.net/browse/EDU-131).
In the admin section, links to push admin API should go to the API reference page, rather than to the top of the current page.
* [Admin section of admin page](http://ably-docs-edu-131-fix-p-qa79ye.herokuapp.com/general/push/admin/#admin)
> [EDU-131] - Fix links to point at Push Admin API

- content/api/rest-api.textile
Fix the get device registration JSON block, and add info on `push.error`.
* [EDU-647](https://ably.atlassian.net/browse/EDU-647)
* [REST AI - get device reg](https://ably-docs-edu-647-error-lo5dqw.herokuapp.com/api/rest-api/#get-device-registration)
> [EDU-647] - Fix get device reg info

- content/code-index.textile
- content/index.textile
- content/realtime/authentication.textile
- content/realtime/channels.textile
- content/realtime/channels/channel-parameters/deltas.textile
- content/realtime/channels/channel-parameters/overview.textile
- content/realtime/channels/channel-parameters/rewind.textile
- content/realtime/connection.textile
- content/realtime/encryption.textile
- content/realtime/history.textile
- content/realtime/index.textile
- content/realtime/messages.textile
- content/realtime/push.textile
- content/realtime/statistics.textile
- content/realtime/usage.textile
- content/rest-api/token-request-spec.textile
- content/rest/authentication.textile
- content/rest/channel-status.textile
- content/rest/channels.textile
- content/rest/encryption.textile
- content/rest/history.textile
- content/rest/index.textile
- content/rest/messages.textile
- content/rest/push.textile
- content/rest/statistics.textile
- content/rest/usage.textile
This PR adds a `meta_description` to pages that were previously missing it. It also updates the descriptions for some of the REST conceptual pages that haven't been updated since the API references were separated.
Sections that did not have `meta_description` added are:
* Client library development guide
* Comparison pages
See [JIRA](https://ably.atlassian.net/browse/EDX-217) for further information.
The simplest way to review this PR is using diffs and running the preview app to ensure the site builds.
> [EDX-217]: Add meta_description to pages without it

- content/general/aws-authentication.textile
Add clarification to the AWS authentication docs on how to find API Key and App ID.
Added [new ticket](https://ably.atlassian.net/browse/EDU-987) to create a partial for API Key and App ID.
* [Bugs](https://ably.atlassian.net/browse/EDU-608)
* [EDU-555](https://ably.atlassian.net/browse/EDU-555).
Check content of 4th step under Create a Role on AWS Authentication page:
* [AWS Authentication - Create a Role](https://ably-docs-edu-555-api-k-ktexo1.herokuapp.com/general/aws-authentication/#create-role)
> edu-555 - clarify App ID

- content/root/quick-start-guide.textile
* [EDU-989](https://ably.atlassian.net/browse/EDU-989).
Review for both JavaScript and Node.js languages selected:
* [QSG](https://ably-docs-edu-989-updat-lcmgaz.herokuapp.com/quick-start-guide/)
It should be clear from the note and from the comment in the connect code that the `async` main wrapper is not shown to keep things simple, but they have full code on hand at the link provided.
> [EDU-989] - Make it clear async wrapper not provided in snippets

- content/root/quick-start-guide.textile
Update quickstart guide for version 1.2.0 of the Python SDK.
* [EDU-971](https://ably.atlassian.net/browse/EDU-971).
Select the `Python` language from the language selector, and review the guide:
* [Page to review](http://ably-docs-edu-971-fix-p-lgdeyr.herokuapp.com/quick-start-guide)
> Update quickstart for python

- content/core-features/authentication.textile
- content/realtime/messages.textile
Add content about using JWT authenticated user claims to control what can be sent. The ticket was initially driven by the update and delete use case however the feature is much broader in its ability so these are just mentioned in passing and the content is generalised.
* [DEP-113 - Update and Delete](https://ably.atlassian.net/browse/DEP-113).
Check Messages page for signposting and check Auth and Security page for actual content:
* [Auth and Security to check actual content](http://ably-docs-dep-113-updat-pr6wnc.herokuapp.com/core-features/authentication/#jwt-claims)
* [Messages to check …
> add jwt authenticated claims

- content/realtime/messages.textile
Make sure language selector on message interactions displays signposting on all languages not JS or Node, and doesn't display for JS and Node.
* [Bugs](https://ably.atlassian.net/browse/EDU-608).
* [Message interactions docs links to itself when JavaScript selected](https://ably.atlassian.net/browse/EDU-972).
Check language selector on message interactions display signposting on all languages not JS or Node, and doesn't display for JS and Node.
* [Messages - Message Interactions](https://ably-docs-edu-972-messa-0yngmo.herokuapp.com/realtime/messages/#message-interactions)
> [EDU-972] - Message interactions lang selection

- .githooks/README.md
- .githooks/post-checkout
- .githooks/pre-commit
- README.md
- data/html-parser/index.ts
- data/transform/post-parser/README.md
- data/transform/post-parser/index.js
- data/transform/post-parser/root-level-text-wrapper.test.ts
- data/transform/post-parser/root-level-text-wrapper.ts
- graphql-types.ts
- package-lock.json
- package.json
Wraps root level text elements in `<p>` elements. A simple change, tracking down the best place and way to do this without affecting anything else was what took most time so I've added a line to the postParser folder.
**Unrelated Changes:**
- Removes `husky` githooks package from the repository, as it did not work particularly well.
- Adds optional new .githooks folder that you can activate or deactivate using scripts.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-202).
Run the branch locally, check:
* [Page to review](http://localhost:8000/docs/rest-api?lang=python)
F3 or Cmd+F to find 'HATEOS':
Check that nothing's wrong, see how it …
> [EDX-202] Render unwrapped root level text in p elements

- content/general/push.textile
- content/general/versions/v1.0/push.textile
- content/general/versions/v1.1/push.textile
- content/rest-api/versions/v1.1/beta.textile
- content/rest/batch.textile
- content/rest/versions/v0.8/usage.textile
- content/rest/versions/v1.0/usage.textile
Removes the `api_separator`. See:
* [EDU-1004](https://ably.atlassian.net/browse/EDU-1004)
Easiest to check the diff.
> [EDU-1004] - Remove api_separator

- content/client-lib-development-guide/features.textile
As suggested by Simon in [this comment](https://github.com/ably/ably-js/pull/784#pullrequestreview-721164875).
> Imagine: client lib is in detached after an explicit detach() while in suspended after a failed attach, and then the server finally catches up and sends an ATTACHED; we want to enforce the user's stated preference and send a DETACH rather than just acquiesce and end up in the attached state after the user called detach()
As far as I can tell there's no existing special behaviour defined by the spec when ATTACHED is received in the `detached` state so this doesn't conflict with any existing spec points but it's worth having a second pair of eyes to confirm this?
> Make RTL5K also apply to detached state

- content/tutorials/jwt-authentication.textile
- content/tutorials/presence.textile
- content/tutorials/publish-subscribe.textile
This work is to update the newly-rewritten Publish/Subscribe Messaging App and JWT Authentication tutorials to use the same heading structure as used in the Tracking Connected Clients with Presence tutorial (defined in the [Tutorial Writing Guidelines](https://ably.atlassian.net/wiki/spaces/DEVX/pages/2261123086/Tutorial+Writing+Guidelines)).
Namely:
- Same order, casing, and imperative rather than gerund in the headings
- Remove live demo unless it exactly mirrors the tutorial project (which it does in the case of the JWT auth tutorial)
* [EDU-970](https://ably.atlassian.net/browse/EDU-970).
View the …
> [EDU-970] - Standardize newly written tutorials

- data/transform/index.js
Removing the tutorials pages from the docs site
* [Jira ticket](https://ably.atlassian.net/browse/EDX-235).
All the tutorials pages should be 404
`/tutorials/newsfeed-react.textile tutorials/newsfeed-react`
> [EDX-235] Tutorial page needs to be removed from the docs site

- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/templates/base-template.tsx
Acceptance Criteria:
- When I deliberately visit a query-string based language page variant (e.g. `http://localhost:8000/docs/realtime/usage?lang=javascript`, `http://localhost:8000/docs/realtime/usage?lang=nodejs`), I always land on that page, even if I have a preferredLanguage set.
- When I deliberately visit a query-string based language page variant as above, my preferredLanguage is set to the language of that page variant.
- When I visit a page with no language set (e.g. `http://localhost:8000/docs/realtime/usage`), if my preferredLanguage is set I am redirected to that page.
I've made the following additional change:
- If I visit a page …
> [EDX-300] Preferred language not set correctly

- COPYRIGHT
- LICENSE
The lack of clear indication of copyright has been an oversight for a while in this repository, especially given its open source nature.
See [this Slack thread (internal)](https://ably-real-time.slack.com/archives/C01LR5XFHFX/p1664879153835639) for further context.
> Add `COPYRIGHT` and refine `LICENSE`

- content/general/push/publish.textile
- content/general/versions/v1.1/push/publish.textile
This PR replaces tables formed using `<table>` syntax with textile ones instead. 
Note: this doesn't include the ones in the feature spec as this is currently in the process of being migrated.
See [JIRA](https://ably.atlassian.net/browse/EDX-347) for full details.
Ensure tables are identical to those currently live.
> [EDX-347] Replace HTML tables with textile format

- content/tutorials/reactor-event-azure.textile
- data/transform/StringContentOrderedList.d.ts
- data/transform/retrieve-partials/applyIndent.test.ts
- data/transform/retrieve-partials/applyIndent.ts
- data/transform/retrieve-partials/index.js
Remove bug that means that when a .textile file is used as a partial, definition lists are not parsed correctly by textile.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-295).
The bug mostly appeared on this page:
* [Page to review](http://localhost:8000/docs/api/realtime-sdk/channels?lang=java)
Here's a screenshot of the problem in the current toolchain, right at the bottom you can see:
Members
- key := The key valueType: String - value := The value associated with the keyType: String
It should be rendered as a definition list.
> [EDX-295] Definition list indentation fix

- content/core-features/authentication.textile
I noticed this in passing, when I was reading this documentation and cross-verifying with the Realtime implementation (internal codebase).
The correct key is used elsewhere in the docs, so this was the only location that I could find this incorrect (pluralised) key being used in this codebase.
> Fix incorrect key in JWT authentication example (user claims)

- src/components/Layout/Layout.tsx
- src/components/Sidebar/SidebarHeading.test.tsx
- src/components/Sidebar/SidebarHeading.tsx
- src/components/Sidebar/SidebarLinkMenu.tsx
On mobile container used to have extra space on the left and right.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-373).
Container on mobile screen should be the right width
> [EDX-373] Width of main component and the right side nav don't match the specs on Figma for large screens

- content/api/sse.textile
- content/sse/index.textile
Correct the example consistency for SSE, the variable defined and being referenced didn't match. Replicated changes to another example that worked, but were different, for consistency.
* [Jira epic ticket](https://ably.atlassian.net/browse/EDU-608).
* [Jira ticket](https://ably.atlassian.net/browse/EDU-725).
Check code examples are correct:
* [SSE](https://ably-docs-edu-725-sse-b-wutt7z.herokuapp.com/sse/)
* [API - SSE](https://ably-docs-edu-725-sse-b-wutt7z.herokuapp.com/api/sse/)
> [EDU-725] - correct sse consistency

- content/api/rest-sdk/channels.textile
- content/api/versions/v0.8/rest-sdk/channels.textile
- content/api/versions/v0.8/rest-sdk/messages.textile
- content/api/versions/v1.0/rest-sdk/channels.textile
- content/api/versions/v1.1/rest-sdk/channels.textile
- content/partials/types/_http_paginated_response.textile
- content/partials/types/_paginated_result.textile
- content/partials/versions/v0.8/types/_paginated_result.textile
- content/partials/versions/v1.0/types/_http_paginated_response.textile
- content/partials/versions/v1.0/types/_paginated_result.textile
- content/partials/versions/v1.1/types/_http_paginated_response.textile
- content/partials/versions/v1.1/types/_paginated_result.textile
This PR expands nested span tags found within `type` elements so that they can render correctly in the new toolchain.
Ensure that all types still display correctly in the current toolchain.
> [EDX-298] Expand nested spans within types

- content/root/quick-start-guide.textile
The new toolchain handles simultaneous language blocks slightly differently. This caused a single instance of blangs using default to not render correctly in the quickstart guide. This PR forces the language grouping to "reset" by explicitly calling out javascript in the default block. 
See [JIRA](https://ably.atlassian.net/browse/EDX-369) for further information.
Ensure that the quickstart guide still renders correctly in the current toolchain.
> [EDX-369] Force consecutive blang to terminate properly 

- src/components/PageTitle.tsx
- src/components/blocks/complex-functionality/Button.tsx
These components import global CSS styles and I'm 99% sure they don't need to; it's making us load too much CSS on every page.
Make sure pages load with correct CSS.
> Chore - remove duplicate css imports

- src/components/blocks/external-references/A.tsx
We shouldn't be detecting links that start with '#' and prefixing them with '/docs', and we shouldn't be preventing links that contain '#' from being prefixed with '/docs'.
e.g.
'/api/blah/blah#bleh' => '/docs/api/blah/blah#bleh'
'#bleh' => '#bleh'.
> [BUGFIX] - Fix on page nav detection

- content/api/index.textile
This PR adds links to the auto-generated API references for JavaScript to the API reference overview.
> [EDX-458] Add JavaScript links to API references

- data/transform/pre-parser/textile-js-workarounds/fix-html-tags-with-newlines.ts
- data/transform/pre-parser/textile-js-workarounds/index.ts
Removes extra spaces from img html elements, which allows them to display after textile parsing
* [Jira ticket](https://ably.atlassian.net/browse/EDX-445).
Make sure first image appears on this page:
* [Page to review](http://localhost:8000/docs/general/kafka-connector?lang=ruby)
> [EDX-445] broken image on page

- content/api/rest-api.textile
- content/general/push.textile
- content/general/push/publish.textile
- content/partials/general/push/_push_intro.textile
- writing-style-guide.md
There are several references to web Push Notifications in the docs and that it’s currently experimental. 
These should be removed for now. 
See discussion in Slack for more info: https://ably-real-time.slack.com/archives/CURL4U2FP/p1666172752980979
* [EDU-609](https://ably.atlassian.net/browse/EDU-609)
* [EDU-1155](https://ably.atlassian.net/browse/EDU-1155)
I have removed the required information by commenting the lines out so that they can be easily returned once the feature reaches production.
Verify that web push notification references and set-up information is not present at the following locations:
Main docs:
* [Push Notifications - Overview](https://ably.com/docs/general/push#direct-publishing)
* [Push Notifications - Overview](https://ably.com/docs/general/push#platform-support) …
> [EDU-1155] remove mentions of web push from the push notifications docs

- src/components/blocks/list/Dl/DlWrapper.tsx
Adds `DEFAULT_LANGUAGE` to fix issues where default blocks don't always appear.
> Add DEFAULT_LANGUAGE option for rendering languages correctly

- content/partials/types/_presence_action.textile
- content/partials/versions/v0.8/types/_presence_action.textile
- content/partials/versions/v1.0/types/_presence_action.textile
- content/partials/versions/v1.1/types/_presence_action.textile
The new toolchain requires codeblocks nested within blangs to be terminated at the end of a partial, otherwise the last language runs on into the parent file.
This only occurs in a single partial and this PR fixes it.
Ensure the partial still renders correctly in the existing toolchain.
> [EDX-496] Terminate nested code block at end of partial

- src/components/blocks/list/Dl/index.tsx
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
* [EDX-491](https://ably.atlassian.net/browse/EDX-491?atlOrigin=eyJpIjoiNWJkMmY5ODgxMDA3NGNkYWFiNmJjZTQwNDMwMjRmODQiLCJwIjoiaiJ9)
* /docs/api/realtime-sdk?lang=csharp
> [EDX-491]:  API Ref definition lists should appear in separate lines

- content/api/sse.textile
- src/components/blocks/api-reference/headings/ApiReferenceH5.tsx
- src/components/blocks/block-component-maps/component-map.js
* [EDX-512](https://ably.atlassian.net/browse/EDX-512?atlOrigin=eyJpIjoiN2JlMTVjMGI4YTI3NGI5ODlmN2NhOGFhNDJmNDQyMzMiLCJwIjoiaiJ9)
* the textfile needs new line so the Header "Format Envelope" will be displayed [EDX-571](https://ably.atlassian.net/browse/EDX-571?atlOrigin=eyJpIjoiMzYxNmYxODY0YjdhNGFiMmFlZDNiMDk2MzJiNTdhNWMiLCJwIjoiaiJ9)
* [[Page to review](link)](https://ably.com/docs/api/sse?lang=python#envelope-format)
> [EDX 512] - API H5 should be linkable like old site and Format Envelope should be visible

- content/core-features/authentication.textile
Rendering error with the table correction. Changed the formatting to show correctly then added example for clarification, example in code tags as it contained an @ symbol.
* [Bugs](https://ably.atlassian.net/browse/EDU-608).
* [Token revocation rendering error](https://ably.atlassian.net/browse/EDU-1053).
Check the rendering of the table for token revocation:
* [Auth and security](https://ably-docs-edu-1053-toke-4tj5lf.herokuapp.com/core-features/authentication/#token-revocation)
> [EDU-1053] - correct rendering

- content/api/realtime-sdk/connection.textile
This PR fixes some issues with `/api/realtime-sdk/connections` caused by incorrectly terminated divs and spacing of elements. It also removes additional closing span tags that weren't doing anything.
See [JIRA](https://ably.atlassian.net/browse/EDX-576) for further information.
> [EDX-576] Correct spacing and divs for /realtime-sdk/connections

- content/api/rest-api.textile
This PR removes unnecessary `<a>` tags from around a link that was malformed in the new toolchain.
See [JIRA](https://ably.atlassian.net/browse/EDX-529) for further information.
> [EDX-529] Remove HTML wrapping link

- src/components/Header/TopMainNav/Dropdown/Button/DropdownButton.tsx
- src/components/Header/TopMainNav/TopMainNavUser/TopMainNavLink.tsx
Add hover text color and remove outine when focsused
Currently when clicked it looks like this:
After fix
Add hover text color to the other non-dropdown links as well
* all pages with top navigation
* click the dropdown
* it should same as ably.com
> Top nav menu add style for hover  and remove outline when focus

- config/nginx.conf.erb
A last minute change in #1748 went undetected and unfortunately resulted in a broken nginx configuration. This fixes it by adding the missing `@404` fallback to a `try_files` directive.
> [EDX-444] Incorrect try_files directive broke nginx

- config/nginx.conf.erb
There seems to be an issue with Heroku lately where redirects on trailing slashes suddenly include the PORT number, making the redirects unreachable.
The review apps for #1658 & #1705 exhibited this issue:
~~~
$ curl -I https://ably-docs-edx-496-neste-pziq0w.herokuapp.com/rest
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: nginx
Date: Mon, 07 Nov 2022 10:05:15 GMT
Content-Type: text/html
Content-Length: 162
Location: http://ably-docs-edx-496-neste-pziq0w.herokuapp.com:51026/rest/   # <= THIS SHOULD NOT HAVE A PORT
X-Frame-Options: SAMEORIGIN
Via: 1.1 vegur
~~~
To review this PR you'd need access to Heroku to run the following test:
~~~
$ heroku ps:exec -a <any-docs-review-app>
~~~
Once you're in, you can run the following test:
~~~
$ curl -I -H "X-Forwarded-Proto: https" -H …
> [FIX] Disable `port_in_redirect` in nginx config

- src/components/Sidebar/SidebarHeading.tsx
Currently there are errors in React if you accidentally use a native HTML JSX element with the `activeClassName` prop. This fix expands an existing fix to make sure that the Component rendered is never a native HTML element.
> [Chore] - Fix active classname

- .circleci/config.yml
- .gitignore
- bin/assert-redirect.sh
- bin/assert-success.sh
- config/client-lib-development-guide-redirects.conf
- config/nginx.conf.erb
- config/website-redirects.conf
Now that the new toolchain is available on docs.ably.com as well, we have some old nanoc toolchain artefacts to deal with as well:
* Tutorials should be accessed from ably.com/tutorials
* Client library development guides have moved to sdk.ably.com in #1608
See EDX-614
This also addresses [these comments](https://github.com/ably/docs/pull/1608#issuecomment-1266837897) from @m-hulbert & @QuintinWillison in #1608 
>> Any objections if we get redirects set up with the web team in the future to remove these pages from docs entirely? Do we need to preserve the deep links of the features spec for anything?
> I would love for that to happen and I had …
> [EDX-614] Redirect tutorials and client lib development references

- content/api/realtime-sdk/presence.textile
This PR uses the `<mark>` syntax to ensure nested spans display correctly in the new toolchain.
See [JIRA](https://ably.atlassian.net/browse/EDX-384) for further information.
Ensure the spans still display correctly in the current toolchain.
> [EDX-384] Update syntax for nested spans

- src/components/blocks/typography/P/index.tsx
Observe at:
**Main**
[Example page](https://docs.ably.com/docs/api/realtime-sdk?lang=javascript)
**Branch**
[Example page](http://localhost:8000/docs/api/realtime-sdk?lang=javascript)
> Fix for bad styling on paragraph children of blockquotes

- src/components/blocks/table/Table.module.css
Prevents table component overlapping right sidebar in some cases.
**Main**
[Example page](https://docs.ably.com/docs/asset-tracking?lang=kotlin)
**Branch**
[Example page](http://localhost:8000/docs/asset-tracking?lang=swift)
> Remove min width from table component, prevent sidebar overlap

- src/components/blocks/software/Code/index.tsx
- src/redux/api-key/remote-api-key-data.ts
Temp API key loading doesn't work if the payload from /api/me has an error: it needs to account for that case when it loads, and provide a proper temporary API key.
> Hotfix api keys

- src/templates/base-template.tsx
When a file is index.textile, the slug ends with a slash
Canonicals should never end with a slash, so we have to address this.
> Slashless canonicals even for index files please

- static/robots.txt
We don't want docs.ably.com indexed, we expect most visitors to be accessing the docs through ably.com/docs
This PR introduces a `robots.txt` file that disallows all crawlers.
Ensure the review app has a `/robots.txt` file.
> [CHORE] Add robots.txt to prevent direct indexing

- .circleci/config.yml
Sed replacing the contents of the heroku buildpack so it no longer relies on an out of date SSL cert for an FTP server.
> [BUGFIX]: Heroku buildpack relies on insecure FTP server for PCRE dependency

- src/components/blocks/list/Dl/index.tsx
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
* [Jira ticket](https://ably.atlassian.net/browse/EDX-539).
Check this page:
* [Page to review](https://ably-docs-next-staging.herokuapp.com/docs/api/rest-sdk?lang=php#client-options)
It looks like this live, note the gap between definition lists (may need to click to expand):
Locally it should look like this:
See comments for how this fixes the issue and why.
> [EDX-539] CSS alteration to prevent multiple definition list lines showing alongside each other

- content/realtime/usage.textile
- content/rest/usage.textile
- src/components/blocks/software/Code/index.tsx
Adds syntax highlighting for frameworks dotNet and Flutter, using the highlighting rules for C# and Dart respectively.
* [Jira ticket](https://ably.atlassian.net/browse/EDX-597).
There are a couple of examples of Flutter on this page:
[Flutter example](http://localhost:8000/docs/api/realtime-sdk/connection?lang=flutter)
The 'enums' are now highlighted, contrast with:
There are more examples of DotNet/C# around, check this page:
[CSharp example](http://localhost:8000/docs/api/rest-sdk?lang=csharp#stats-granularity)
There is syntax highlighting on 'public' and 'enum' keywords, contrast with:
> [EDX-597] Add syntax highlighting for frameworks

- .eslintrc.json
- babel.config.js
- content/root/tools.textile
- package-lock.json
- package.json
- src/components/PageTitle.tsx
- tsconfig.json
Since we are using React 18, there is no longer a need to `import React from "react";` at the start of every .jsx/.tsx file. This change is to the configuration to allow babel and typescript to compile correctly without `import React from "react";`.
There is also:
* a minor typo/link correction in `tools.textile`.
* PrismJS (a code highlighting tool that we no longer use) has been uninstalled.
Ensure that docs still builds, make sure PageTitle component isn't broken.
> [CHORE]: Remove need for importing React in every .tsx or .jsx file

- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/components/Select/Select.tsx
EDX-565 - language menu on code elements is too wide on a small screen.
Before:
After:
[EDX-565]: https://ably.atlassian.net/browse/EDX-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDX-565] Fix language menu  being too wide on small screen

- content/api/rest-api.textile
- content/core-features/authentication.textile
core-feature/auth and rest-api -- add warnings for a bug we have 
context: https://ably-real-time.slack.com/archives/C8SPU4589/p1673614895790359?thread_ts=1673356100.438359&cid=C8SPU4589
> Token revocation: add warning that issuedBefore does not work with normal tokens

- content/realtime/messages.textile
Message reactions can only be published with the `publish(Message)` or `publish(Message[])` signatures, not with the `publish(name, data)` signature.
> Fix message interactions signature

- content/general/limits.textile
This PR corrects the message rate value for PAYG packages. It should be `2,400`.
> [EDU-1325] Correct message rate value

- src/pages/docs.tsx
Purpose of this PR is to make the main homepage indexable - currently only the slash-enabled version, https://ably.com/docs/, is indexable because this page is canonicalised to that URL.
* [Jira ticket](https://ably.atlassian.net/browse/WEB-2880).
View the app homepage here:
view-source:https://ably-docs-web-2880-corr-s9t5cq.herokuapp.com/docs
Verify that the canonical is correct, make sure that there is no trailing slash.
> [WEB-2880] Fix canonical to be slashless

- src/components/Sidebar/SidebarLink.tsx
- src/components/blocks/external-references/A.test.tsx
- src/components/blocks/external-references/A.tsx
- src/components/blocks/external-references/AElementHelpers/check-link-is-internal.test.ts
- src/components/blocks/external-references/AElementHelpers/check-link-is-internal.ts
This PR is intended to prevent Gatsby from pre-fetching the page data for the (empty) Control API page, which in turn prevents the website from providing the Control API page when a link to that page is clicked from inside the Gatsby app.
It achieves this by using plain links rather than Gatsby Link elements when we detect that a link is pointing to the Control API page.
Unwanted behaviour:
Gatsby Link hovered => Gatsby pre-fetches page.json for /docs/api/control-api => Gatsby renders page for /docs/api/control-api when you click the Gatsby Link component.
Expected behaviour:
Link hovered => Link clicked => Whatever is returned from the …
> [WEB-2843] Control API links are broken due to Gatsby pre-fetch.

- src/components/PageTitle.tsx
This was a kludgy fix for a temporary issue with Page Titles that is now just redundant and gets in the way, looks really weird because text just gets cut off.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1326).
Run gatsby clean && gatsby develop
Check page http://localhost:8000/docs/realtime/inband-occupancy, resize screen. Ensure that page title doesn't clip or get cut off.
* [Page to review](http://localhost:8000/docs/realtime/inband-occupancy)
> [EDU-1326] Fix - Page Title overflowed if too long

- data/transform/pre-parser/textile-js-workarounds/fix-links.test.ts
- data/transform/pre-parser/textile-js-workarounds/fix-links.ts
> This bug appears on [the Authentication page](https://ably.com/docs/core-features/authentication#jwt-embed-process) (specifically [here](https://github.com/ably/docs/blob/main/content/core-features/authentication.textile?plain=1#L168) in the code), the code inside the codeblock is being erroneously transformed into a link. It seems to be interpreting ```{{"*\":[}}``` as ```{{<a href="[\">*\</a>}}``` despite being inside of a code block.
Note; textile-js does try to interpret content inside ```<pre>``` blocks, and nanoc had a mixture of behaviours when interpreting content inside code blocks; we need our own parser if we're going to reliably …
> [EDU-1319]: Ignore textile 'links' with just punctuation and/or control characters

- src/redux/api-key/remote-api-key-data.ts
Causes subscription to curl requests to be activated on API key retrieval in quickstart script.
To review, in your local variables ensure that you set:
```DUPLICATE_KEY_ISSUE_OVERRIDE=$valueFromWebsiteProdHerokuNode```
Run the website application as usual.
Build and serve the docs app with ```--prefix-paths```, ```gatsby build --prefix-paths && gatsby serve --prefix-paths```
Got to localhost:9000/docs/quickstart-guide and try to run the first curl command on the page. You should see an alert appear.
> [FIX]: Quickstart script activation, fix API key subscriptions on retrieval

- src/components/LanguageButton/LanguageButton.tsx
- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
- src/components/common/language-defaults.ts
* language buttons are displayed in the MenuItemButton first so need to filter the language of rest/realtime when selected
* add sdkInterface when clicking language buttons
* add global function to filter language to remove rest/realtime
* Language Button able to filter language
[EDU-1357](https://ably.atlassian.net/browse/EDU-1357)
While testing I found another bugs
- Selecting languages on other code should also update the realtime/rest code box
- Also weirdly the code changes in the ealtime/rest code box
They are currently in a separate ticket [EDU-1358](https://ably.atlassian.net/browse/EDU-1358)
[EDU-1357]: https://ably.atlassian.net/browse/EDU-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> [EDU-1357] - Fix: Active tab disappears when switching from Rest/Realtime

- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/blocks/software/Pre.tsx
Because languages can have a prefix of `rest` or `realtime`, the language dropdown was not automatically updating to the language selected in the code box any more. 
Fixed this by using the `getFilteredLanguage` method
> fix: Fixes issue where lang dropdown was not updating

- content/channels/index.textile
- content/root/quick-start-guide.textile
- data/createPages/constants.ts
- src/components/LanguageButton/LanguageButton.test.tsx
- src/components/LanguageButton/LanguageButton.tsx
- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.tsx
- src/components/SDKInterfacePanel/SDKInterfacePanel.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.js
- src/components/blocks/wrappers/LocalLanguageAlternatives.test.tsx
- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
- src/components/common/language-defaults.test.ts
- src/components/common/language-defaults.ts
- src/templates/base-template.tsx
- src/utilities/language/cache-visit-preferred-language.ts
[EDU-1359](https://ably.atlassian.net/browse/EDU-1359)
[EDU-1368](https://ably.atlassian.net/browse/EDU-1368)
[EDU-1367](https://ably.atlassian.net/browse/EDU-1367)
- All changes are added on this PR related to Rest/Realtime.
- The team decided that the new Realtime/Rest Tab to be independent rather than part of the pageLoad. So this means we will change the previous changes we have done and apply this new feature.
-  The textile changes will be reverted later
- Removed `sdkInterface` storing in local storage and adding in the URL parameters
- Cleanup from last changes so it will work on all  codebox once language selection changes when pageload
- If rest/realtime present in codebox, it should independently switch
- The language navigation should work accordingly when switching
- When …
> [EDU-1359] - Change the Realtime/Rest Tab to be independent rather than part of the pageLoad

- src/components/Menu/LanguageDropdownSelector/LanguageDropdownSelector.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.js
- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
- src/utilities/language/constants.ts
* [EDU-1370](https://ably.atlassian.net/browse/EDU-1370)
* [EDU-1366](https://ably.atlassian.net/browse/EDU-1366)
**Fixed the following issues**
- When selecting Rest/Realtime it should display infoBox if language is not existed and select default one
- REST/realtime tab should display with only 1 tab and 1 interface
- When local language change the code highlight is gone
**Description of the Changes:**
- Able to display the tabs if the rest or realtime code is 1 only
- changed the condition to minimum of 1 in returning the relevant group and didn't break existing code box
- removed extra splitting in the LocalLangAlternatives component since we are already splitting the language from Pre component
- in the setLocalSelected, when …
> [EDU-1370] - REST/realtime tab should display with only 1 tab and 1 interface & fix infobox issue

- src/components/blocks/wrappers/ConditionalChildrenLanguageDisplay.js
* [EDU-1365](https://ably.atlassian.net/browse/EDU-1365)
In passing realtime and rest data the to `Pre` component `getCleanedSDKInterfaceAltData` function it filters the lanauge and for the case of the string `java` it was returning  `javascript` since we've used the `include` method. Need to change it to comparing actual value so it return the correct data.
* Test it in your local
[EDU-1365]: https://ably.atlassian.net/browse/EDU-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-1365] - Fix Bug: When Java selected it displays javascript code

- src/components/LanguageButton/LanguageButton.test.tsx
- src/components/LanguageButton/LanguageButton.tsx
- src/components/Menu/LanguageNavigation/LanguageNavigation.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/LocalLanguageAlternatives.test.tsx
- src/components/blocks/wrappers/LocalLanguageAlternatives.tsx
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- src/components/common/language-defaults.ts
* [EDU-1377](https://ably.atlassian.net/browse/EDU-1377)
- Removed the `localChange` functionality and component parameters so it always reload whenever they select new language.
- In the `LocalLanguageAlternatives`, removed the `MenuItemButton` component as it wont be used anymore and other event handling function for `localChange`
- Renamed the function from `getFilteredLanguages` to `getTrimmedLanguage` so its more easier to understand the use of the function
**So for the issue if the language is not present in an SDK Interface codebox, changes are:** 
- Added a `checkIfPreHaveLanguageSelected` method, helps us to determine if an array of languages has a `pageSelected` lang present, a condition was also added if it is an SDK Interface, …
> [EDU-1377] - Code blocks should always change global language

- src/components/SDKInterfacePanel/SDKInterfacePanel.test.tsx
- src/components/SDKInterfacePanel/SDKInterfacePanel.tsx
- src/components/blocks/software/Pre.test.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
This PR updates the copy for the REST/realtime selector tooltip, and also updates the message that displays when a code block is displayed that doesn't support the currently selected language.
See [JIRA](https://ably.atlassian.net/browse/EDU-1354) for full details.
> [EDU-1354] Update tooltip and message copy

- src/components/Menu/TopCodeMenu.tsx
[EDU-1385](url)
The API version label is no longer displayed next to the language selector dropdown.
[EDU-1385]: https://ably.atlassian.net/browse/EDU-1385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDU-1385]: Hide API Version label

- content/api/realtime-sdk/connection.textile
- content/api/rest-sdk/messages.textile
- content/rest/messages.textile
Context: https://ably-real-time.slack.com/archives/C8SPU4589/p1680713169502179 -- we underdocument the publish-on-behalf thing.
I went back and forth a bit about whether to explicitly include a sentence like "(Note that this restriction is not enforced for connectionKeys issued to realtime connections using older versions of the realtime protocol)". Ultimately ended up not, it's not very actionable and unnecessarily confuse/complicates it.
Main page to review: rest/messages#publish-on-behalf
> Clarify publish on behalf

- content/core-features/authentication.textile
Fixes the formatting on the token revocation sections around code snippets. Some of the examples were updated to remove the `@` symbol, as textile wasn't liking this.
- `npm run edit`
- Look at the `/docs/core-features/authentication#revocable-tokens` page
> fix formatting on token revocation

- src/components/Footer/FooterTopNav/FooterLogo.tsx
- src/types/ably-ui-core-images/ably-ui-logo-loading.d.ts
The `Logo` component from ably-ui seems doesnt work. 
Since none of the projects is using this component might as well not used it as its unstable
* Check all docs pages and make sure the logo is present
> Bug: Fix Footer logo is missing by replacing ably-ui Logo to img

- content/getting-started/setup.textile
- data/yaml/page-furniture/sidebar.yaml
This PR adds a page covering the setup instructions for SDKs. It combines the existing REST and realtime usage pages and adds more context related to API keys and ClientOptions.
See [JIRA](https://ably.atlassian.net/browse/EDU-1200) for further information.
View `/docs/getting-started/setup` to review this new page.
> [EDU-1200] Add page for SDK setup instructions

- content/api/index.textile
Fixed two small issues on `/docs/api`:
* Missing link to the Java SDK
* JavaScript links weren't being displayed correctly due to textile turning parens into title attributes
Before:
After:
> [FIX] Update generated SDK links

- content/partials/types/_push_channel.textile
This PR fixes a display bug in the push API references on the following 2 pages:
* `api/realtime-sdk/push`
* `api/rest-sdk/push-admin`
It caused a heading to not be parsed correctly and display in textile format.
* [Realtime](https://ably-docs-edu-1398-push-yu03hl.herokuapp.com/docs/api/realtime-sdk/push?lang=android#subscribe-device)
* [REST](https://ably-docs-edu-1398-push-yu03hl.herokuapp.com/docs/api/rest-sdk/push-admin?lang=android#subscribe-device)
> [EDU-1398] Fix push API reference display bug

- app.json
Our nginx templating is written for Ruby <3.2.2 and so we can't use the latest buildpack anymore (which downloads 3.2.2). This is a preventative fix so we can update our templating so a newer version of Ruby is supported.
> Update app.json to use specific buildpack version

- content/general/limits.textile
This PR swaps the descriptions for inbound and outbound message rate limits. They were originally written the wrong way around.
See [JIRA](https://ably.atlassian.net/browse/EDU-1406) for further details.
> [EDU-1406] Correct inbound and outbound message rate descriptions

- src/components/GlobalLoading/GlobalLoading.tsx
When updating via `connectState`, API keys could be set to `undefined` (for example, when the API is not reachable). We want to set them to `{ data: [] }` so they are always compatible with the code paths that use them.
> Default api keys to correct init state

- gatsby-config.ts
This plugin enables a manifest for PWA, native-app like shortcuts on mobile.
However, past including this plugin no work has been done to route correctly both the manifest and the icons included, hence this is broken.
We should remove the plugin for now (so the manifest is not generated) and implement correctly in the future. (as just having this in will log errors in browsers)
> Remove gatsby-plugin-manifest

- content/channels/index.textile
This PR adds documentation for the subscription filters feature (preview). 
It includes code samples for JS. See [this ticket]() for adding instructions on using a channel qualifier for SDKs that don't currently support `getDerived()`. 
See the [channels]() page.
> [EDU-1413] Add subscription filters content

- content/partials/types/_error_info.textile
See https://sdk.ably.com/builds/ably/specification/main/features/#TI4.  This attribute is missing from the docs.
As an aside, @m-hulbert my editor added a linefeed after the last line. According to the [.editorconfig](https://github.com/ably/docs/blob/main/.editorconfig#L6), this should happen automatically on all edits. Is everyone who works on this repo automatically using the standardised editor config?
> Add missing href attribute to ErrorInfo object

- .circleci/config.yml
The heroku buildpack script we're using can't find the version of zlib anymore and needs to be updated to load older versions. This is breaking CI needlessly.
CI for this branch should pass (or at least the nginx build step)
> [FIX] Build nginx with newer zlib version

- content/channels/index.textile
On the /docs/channels page:
- Changed the writing style to active voice.
- Removed 'new line character' and 'whitespace'
[EDU-1428](https://ably.atlassian.net/browse/EDU-1428)
[EDU-1428]: https://ably.atlassian.net/browse/EDU-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1428--Adds example characters to note on restrictions that apply to channel names and namespaces

- content/spaces/avatar.textile
- content/spaces/cursors.textile
- content/spaces/locations.textile
- content/spaces/locking.textile
- content/spaces/setup.textile
- content/spaces/space.textile
A couple of tweaks to the Spaces documentation.
Before:
After:
Looks wrong to my eyes, and if it’s an intentional style choice then it’s not one that’s consistently applied within the Spaces documentation.
> A couple of fixes to Spaces docs

- src/components/Sidebar/Sidebar.tsx
The navigation bar on the left did not have enough spacing below it to display the full list of navigation items. `Limits` and `Platform Customization` weren't being displayed. 
This is what the bottom of the navigation looked like:
This is what it should and will look like when merged:
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1431).
Any of the Channels docs with the navigation on the left.
> [EDU-1431] - Added sufficient padding to bottom of Docs navigation to display the last two items

- content/tutorials/mqtt-snake.textile
The Python tutorial for MQTT Snake requires a Python library called Curses. There have been attempts to get this working on Windows, but no one has been successful. So this is just a note in the tutorial to state the Python version will only be functional on Unix based systems.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-207).
* [Page to review](https://ably.com/tutorials/mqtt-snake#tutorial-step-3)
> Added note to top of Python version of tutorial stating UNIX is supported, not Windows

- content/tutorials/mqtt-snake.textile
The Python tutorial for MQTT Snake requires a Python library called Curses. There have been attempts to get this working on Windows, but no one has been successful. So this is just a note in the tutorial to state the Python version will only be functional on Unix based systems.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-207).
> [EDU-207] add note to mqtt python tutorial stating unix only 2

- content/tutorials/how-to-ably-react-hooks.textile
This PR updates the 'how to use Ably with React Hooks' tutorial now that React hooks are part of the Ably JavaScript SDK rather than a separate package.
> Update tutorial where React hooks package migrated into Ably JavaScript SDK

- content/api/rest-api.textile
The text ABLY_KEY_NAME is not properly replaced with the user's/the demo api key name, so this ensures this usage is in-line with the rest of page's API_KEY_NAME usage.
The text `ABLY_KEY_NAME` is not properly replaced with the user's/the demo api key name, so this ensures this usage is in-line with the rest of page's `API_KEY_NAME` usage.
The text changed from ABLY_KEY_NAME should match the text used for Ably API Key names used throughout the rest of the page, API_KEY_NAME.
> Fix REST doc's usage of ABLY_KEY_NAME -> API_KEY_NAME

- content/channels/messages.textile
This PR:
- Adds note to the `ID` section of the message properties table. 
- Informs user to update the ID if using idempotent publishing.
[EDU-181: Adds note about idempotent publish to message ID description](https://ably.atlassian.net/browse/EDU-181)
> EDU-181: Adds note about idempotent publish to message ID description

- content/partials/versions/v1.1/types/_presence_action.textile
This PR:
- Adds `action numbers` to **ALL** `PresenceAction` code examples (some `PresenceAction` code examples did not have any numbers)
[EDU-208: Add presenceAction numbers for all languages](https://ably.atlassian.net/browse/EDU-208)
> EDU-208: Adds action numbers to all  PresenceAction code examples

- README.md
- gatsby-config.ts
- src/utilities/assets/src-from-docs-site.ts
Gatsby defaults to using port `8000` in development, and we have some places in the code that we inconsistently use port `9000` as a default value. The results are that you get an inconsistent development experience if you don't have any environment variables set up.
By changing our custom values back to port `8000` we get a nice consistent experience where you can just clone the repo and run `npm run development` and get cracking.
This is best done by cloning the repo afresh, installing the dependencies, running `npm run development`, and opening up the site and seeing there are no issues loading images (like the Ably logo)
> [FIX] consistently use port 8000 everywhere in development

- content/spaces/locking.textile
Fixes the key name used in Spaces’ `LockOptions` type, and brings the lock attributes API in line with https://github.com/ably/spaces/pull/214.
> Update lock attributes documentation

- content/protocols/sse.textile
This PR:
- Completely overhauled the doc
- Removed conflicting subjects 
- Removed repetition
- Improved overall clarity 
- Implemented 'active voice'
- Fixed grammar
- Fixed typos
- Confirmed that this document only supports JS as the available language.
☝️ Completing the above task has fulfilled all requirements listed in the attached ticket:
- SSE acronym is undefined.
- The term 'raw HTTP streaming API' is unclear and possibly superfluous.
- Only the JavaScript option in the code sample switcher works; content limitations may be the cause.
- There are wording issues and typos to address.
[EDU-149: SSE documentation needs work](https://ably.atlassian.net/browse/EDU-149)
> EDU-149: Re-writes for clarity

- content/partials/types/_push_admin.textile
- content/partials/versions/v1.1/types/_push_admin.textile
If Java is selected within the Rest API section of the docs, then under the `DeviceRegistrations object` section, there is a broken codeblock. This is due to textile not knowing how to handle a div surrounding this codeblock.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1433).
> Fix issue where codeblock not displaying correctly if surrounded by a div

- data/yaml/page-furniture/spacesSidebar.yaml
This PR updates the Spaces table of contents to move React under the SDK setup page.
> [EDU-1447] Update React placement in Spaces table of contents

- content/spaces/locations.textile
This PR fixes a bug that states a location event is emitted when a member leaves a space. It instead should say that an event is emitted when a member is removed from a space.
See [JIRA](https://ably.atlassian.net/browse/COL-527) for further details.
> [COL-527] Location event emitted on being removed from a space

- data/yaml/page-furniture/sidebar.yaml
- src/components/Layout/Layout.tsx
- src/components/Sidebar/Sidebar.tsx
- src/contexts/SidebarContext.tsx
The main fix here is an update to this part:
```
const context = useContext(SidebarContext);
if (!context) {
throw new Error('useSidebar must be used within a SidebarProvider');
}
return context;
```
I've modified what the `SidebarContext` initial value is, but removed the above, as it's quite normal for it to be false or incomplete. Interestingly, this would run on `build` and immediately fail but never be an issue in dev.
> Fix docs build

- src/components/Homepage/BodySection/Card/SdkCard.tsx
`srcSet` will not get transformed to get the correct `ASSET_PREFIX` and so will never work on the `ably.com` domain. That, and a rogue `}` in the src 😮‍💨 .
> Fix docs home image

- config/tutorials/tutorials.json
- content/tutorials/_live-flight-tracking.textile
- content/tutorials/demo-ably-airtable-starter-kit.textile
- content/tutorials/demo-ably-rock-paper-scissors.textile
- content/tutorials/demo-agile-flush-vue-app.textile
- content/tutorials/demo-decorate-a-tree-2020.textile
- content/tutorials/demo-depict-it.textile
- content/tutorials/demo-fully-featured-scalable-chat-app.textile
- content/tutorials/demo-jamstack-sync-stream-video.textile
- content/tutorials/demo-led-matrix-jumper.textile
- content/tutorials/demo-live-caption-demo.textile
- content/tutorials/demo-multiplayer-games-scalable-networking-framework.textile
- content/tutorials/demo-nextjs-chat-app.textile
- content/tutorials/demo-realtime-midi-player.textile
- content/tutorials/demo-realtime-multiplayer-space-invaders.textile
- content/tutorials/demo-realtime-quiz-framework.textile
- content/tutorials/demo-whiteboard.textile
- content/tutorials/live-bitcoin-pricing.textile
- content/tutorials/tfl-live-tracking-fitbit.textile
This will remove the "API Streamer and Hub" tab on the tutorials page on the website.
* Epic: WEB-3239
* Ticket: WEB-3245
Not much to review this side, once merged and updated in the website we'll have one less tab on `/tutorials`
> [CHORE] Remove API Streamer tutorials category

- content/livesync/index.textile
This PR:
- Writes the 'What is LiveSync' page for the LiveSync alpha release
- Note: the new LiveSync tab in navigation  
[COL-552: What is Livesync page]
> COL-552: Writes the 'What is LiveSync' page

- content/spaces/react.textile
The React Hook for locations was incorrectly listed as `useLocation` rather than `useLocations`.
> [EDU-1462] Update useLocation to useLocations

- content/getting-started/quickstart.textile
This PR:
- Under Connect to Ably -- Updates clientOption in the code example for flutter
[EDU-88: Flutter quickstart guide needs updating](https://ably.atlassian.net/browse/EDU-88)
> EDU-88: Updates 'Connect to Ably' clientOptions for flutter

- content/livesync/connector/index.textile
- content/livesync/models/index.textile
This PR:
- Fixes the links to the 'Google Form hosted' LiveSync feedback form.
[COL-650: Fix feedback form link](https://ably.atlassian.net/browse/COL-650)
> COL-650: Fixes the links to the 'Google Form hosted' LiveSync feedback form 

- data/onCreateNode/create-graphql-schema-customization.ts
- how-tos/pub-sub/how-to.mdx
- jest.config.js
- src/components/Link.tsx
- src/components/Markdown/MarkdownProvider.test.tsx
- src/components/Markdown/MarkdownProvider.tsx
Extracted from #2101, this fixes the issues with rendering links in MDX files when an `assetPrefix` has been set during compilation (like we do). 
The fix is inspired by comments on gatsbyjs/gatsby#21462 
* ACT-163
Visit `/docs/how-to/pub-sub` and ensure the links in "Further reading" work.
* [Pub/Sub How-to](https://ably-docs-act-163-broke-9igs11.herokuapp.com/docs/how-to/pub-sub)
> [ACT-163] Broken links in MDX

- .circleci/config.yml
We are using heroku nginx script to run [install-nginx] job in circleci. It uses the latest version of the zlib installed for this script to run properly.
https://raw.githubusercontent.com/heroku/heroku-buildpack-nginx/main/scripts/build_nginx
```
....
ZLIB_VERSION=${ZLIB_VERSION-1.2.13}
zlib_url=http://zlib.net/zlib-${ZLIB_VERSION}.tar.gz
....
```
Update the zlib version on CircleCI
> chore: update zlib version

- content/storage-history/history.textile
- "since" → "before" (wording was incorrect)
- "received" → "published" ("received" suggests that it’s something that the client received, which it wasn’t because we’re talking about messages they missed)
> Fix wording in `untilAttach` documentation

- content/livesync/connector/index.textile
This PR:
- Makes the corrections suggested on #2109
L7 👇 
> "This system" to me implies that the system does it for you automatically, but that is not the case, the developer has to record the change in the outbox table
> Also, maybe remove "refreshes"?
L31 👇 
> typo on existing
Also the docker compose creates a pg instance for you by default
L100 👇 
> This isn't quite right, only Ably can issue API keys to access Ably. Perhaps just "Ensure your API key has the publish capability ..."
L322
> typo
- Note: the suggestions were made after the PR was merged
[COL-681: Amends integration guidelines for existing systems with LiveSync](https://ably.atlassian.net/browse/COL-681)
> COL-681: Makes various corrections as stated in linked PR

- content/livesync/connector/index.textile
This PR:
- Ensured Postgres is listed under services at the same level as Adbc rather than being nested within Adbc's configuration.
- Fixed indentation issues to match the YAML format correctly.
- Changed the 'network' format for both services from a nested to a list (for consistency).
[COL-675: Fix indentation in docker compose docs](https://ably.atlassian.net/browse/COL-675)
> COL-675: Fixes indentation errors in docker compose example

- content/livesync/models/models.textile
This PR:
- Removes `async` from the merge function code example.
[COL-678: Update docs with the latest merge function changes](https://ably.atlassian.net/browse/COL-678)
> COL-678: Removes async form the merge function code example

- content/api/realtime-sdk/types.textile
- content/api/rest-sdk/types.textile
- content/partials/types/_error_info.textile
This PR:
- Adds `flutter` to the set of languages available in /api/rest-sdk/types
- Reviews the _**now**_ flutter /api/rest-sdk/types?lang=flutter page for the broken language block highlighted the attached ticket
- The review did not identify any language blocks that were broken -- indicating that the issue has been resolved
[EDU-61: Broken language block on rest/types](https://ably.atlassian.net/browse/EDU-61)
> EDU-61: Adds `flutter` to the set of languages available in /api/rest-sdk/types

- content/account/2fa.textile
2FA is now available to all account types, not restricted to PAYG+
> [EDU-1493] 2FA is now available to all account types

- README.md
Updating the README to contain a solution to difficulties experienced when installing `ruby` via `asdf`, due to mismatched `openssl` versions.
Documentation update, no further testing required.
> chore: update README with openssl workaround instructions

- content/livesync/models/index.textile
- content/livesync/models/models.textile
This PR:
- Removes `name` from `modelcClient` options throughout LiveSync docs.
- We don't require both `name` and `channelName` properties.
[COL-686: Remove the reference to `name` property from the docs](https://ably.atlassian.net/browse/COL-686)
> COL-673: Amends Models examples

- content/api/realtime-sdk/channels.textile
- content/api/rest-sdk/channels.textile
- content/channels/index.textile
- https://ably.com/docs/api/realtime-sdk/channels?lang=nodejs#publish
- https://ably.com/docs/api/rest-sdk/channels?lang=nodejs#publish
- https://ably.com/docs/channels#batch-publish
> Publish docs: clarify atomicity guarantees and what it means to group messages into a single publish

- content/livesync/models/index.textile
- content/livesync/models/models.textile
This PR:
- Updates all code references of `sequenceID` and `mutationID` to camelCase -> `sequenceId` and `mutationId`.
[DTP-670: Standardize camelCase naming](https://ably.atlassian.net/browse/DTP-670)
> DTP-670: Amends naming to camel case

- .eslintrc.json
- src/components/Header/SearchBar/SearchBar.tsx
- src/hooks/use-search/use-search.ts
We are not certain all functions in useEffect hooks inside useSearch hook will not change, so in order to prevent any unwanted behaviour (like failing tests because of infinite loop), I've wrapped them all inside useCallback so they will be same by reference.
In console type:
`npm run test`
and check if all tests are passing or Search.spec.tsx is going indefinitely
> [FIX]: use-search useEffect dependencies 

- .circleci/config.yml
- config/client-lib-development-guide-redirects.conf
- config/nginx.conf.erb
- data/createPages/index.js
We had a combination of issues with our nginx config and the changes from setting `pathPrefix` that broke the redirects specified using the `redirect_from` frontmatter.
Our nginx redirects list, generated from the `redirect_from` frontmatter, was missing `/docs` on the destination, like this:
~~~
...
/docs/control-api /account/control-api;
/docs/rest/authentication /auth/;
...
~~~
This made it impossible for nginx to match the directs (the matching happens after the URLs get rewritten). This PR fixes it so the redirects config looks like:
~~~
...
/docs/rest/history /docs/storage-history/history;
/docs/rest/versions/v1.1/history /docs/storage-history/history;
...
~~~
It also fixes issues in the ordering of the directives in the nginx config file that resulted in us serving up the "Gatsby …
> [FIX] Remove pathPrefix from redirects generated by `redirect_from`

- src/hooks/use-site-metadata.test.ts
- src/hooks/use-site-metadata.ts
- src/pages/how-to/pub-sub.tsx
- src/pages/index.tsx
- src/pages/products/channels.tsx
- src/pages/products/livesync.tsx
- src/pages/products/spaces.tsx
- src/pages/sdks/index.tsx
- src/templates/base-template.tsx
While reviewing some site monitoring metrics after merging all the link/image updates I spotted issues with the canonical URLs on several pages.
Using [pup](https://github.com/EricChiang/pup) this is easy to see:
```
$ curl -s https://ably.com/docs/api/rest-sdk/authentication | pup "link[rel=canonical]"
<link data-react-helmet="true" rel="canonical" href="https://ably.com//docs/api/rest-sdk/authentication">
```
This PR unifies hows canonical URLs are generated by having a single utility function that is part of the `useSiteMetadata` hook.
Review a few canonical URLs to ensure no `//` are present
* https://ably-docs-web-3642-cano-bwdlyv.herokuapp.com/docs/api/rest-sdk/authentication
```
$ curl -s https://ably-docs-web-3642-cano-bwdlyv.herokuapp.com/docs/api/rest-sdk/authentication | pup …
```
> [WEB-3642] Canonical URL fixes

- data/yaml/page-furniture/sidebar.yaml
Three links in the nav were broken because they had an extra /docs/ to the path.
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1504).
By clicking any of the three links in the nav below to ensure they don't return a 404.
> Fix broken links in navigation bar, where an extra /docs is added in Ably Accounts and Apps

- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- src/utilities/link-checks.test.ts
- src/utilities/link-checks.ts
A regex meant to prevent links to `/docs/sdk/*` from being considered as local links was too broad and captured links to `/api/rest-sdk` and `/api/realtime-sdk` as well. This fixes it and adds more test coverage.
Verify the following on the review app at [/api/rest-sdk#time](https://ably-docs-fix-api-docs--hnq9ez.herokuapp.com/api/rest-sdk#time)
* https://ably-docs-fix-api-docs--hnq9ez.herokuapp.com/api/rest-sdk#time
> [FIX] API reference docs links edge case

- .circleci/config.yml
Now that we're doing full blown image processing during the build step on CI, we're starting to see an increase in build failures due to running out of memory. This then prevents Heroku from deploying `main` automatically due to false negatives.
This PR bumps the resource class for build from `medium+` to `large`, while dropping the explicit `resource_class` keys from other steps.
It also hands over installation of NPM packages to the circleci/node orb, which should do a better job with caching of dependencies than we can
Look at this build in CI and notice that:
* The yarn caches are actually used and restored
* The `build` step never fails due to running out of memory
> [WEB-3567] Increase CircleCI resource class

- content/root/platform-customization.textile
- data/yaml/page-furniture/apiSidebar.yaml
This PR removes the last use of `/docs/` in local links as these will no longer function correctly with the updates from https://github.com/ably/docs/pull/2145
> [EDU-1506] Remove `/docs` from all links

- config/client-lib-development-guide-redirects.conf
This reverts commit 5f11627ad4d3e4a8bdc9e521cdc749d5e5b86dd5 from #2149 which mistakenly updated the client-lib-development-guide redirects, assuming they were served up on `ably.com/docs`, but this is not the case, they were served up on `docs.ably.com`
Hit `/client-lib-development-guide` on the review app and you'll get redirected to `sdk.ably.com`
* https://ably-docs-fix-client-li-jtovd1.herokuapp.com/client-lib-development-guide
~~~
$ curl -I https://ably-docs-fix-client-li-jtovd1.herokuapp.com/client-lib-development-guide
HTTP/1.1 301 Moved Permanently
...
Location: https://sdk.ably.com/builds/ably/specification/main/
...
~~~
> Revert "fix: client-lib-development-guide redirects need pathPrefix set"

- content/api/index.textile
- content/api/realtime-sdk.textile
- content/api/realtime-sdk/authentication.textile
- content/api/realtime-sdk/channel-metadata.textile
- content/api/realtime-sdk/channels.textile
- content/api/realtime-sdk/connection.textile
- content/api/realtime-sdk/encryption.textile
- content/api/realtime-sdk/history.textile
- content/api/realtime-sdk/messages.textile
- content/api/realtime-sdk/presence.textile
- content/api/realtime-sdk/push-admin.textile
- content/api/realtime-sdk/statistics.textile
- content/api/realtime-sdk/types.textile
- content/api/rest-sdk.textile
- content/api/rest-sdk/authentication.textile
- content/api/rest-sdk/channel-status.textile
- content/api/rest-sdk/channels.textile
- content/api/rest-sdk/encryption.textile
- content/api/rest-sdk/history.textile
- content/api/rest-sdk/messages.textile
- content/api/rest-sdk/presence.textile
- content/api/rest-sdk/push-admin.textile
- content/api/rest-sdk/statistics.textile
- content/api/rest-sdk/types.textile
This PR adds a note to the JavaScript API references that directs developers to the idiomatic API references for v2. This is temporary whilst we transition from manual to auto-generated API refs. 
Ensure that the notice only appears for JavaScript users.
> [EDU-1533] Add note about JavaScript v2 to API references

- src/components/blocks/dividers/Aside.tsx
- src/components/blocks/dividers/dividers.module.css
https://ably.atlassian.net/browse/WEB-3677
Versioning styles `new` and `updated` added to `<aside>` component, according to the [designs on figma](https://www.figma.com/file/hptKqjNIu6G1KXf3IMOWlK/Versioning-Info-UI)
To add the versioning notices on the docs pages:
`new`:
```
<aside data-type='new'>
<p>[text here...]</p>
</aside>
```
`updated`:
```
<aside data-type='updated'>
<p>[text here...]</p>
</aside>
```
> [WEB-3677] Implement UI to support version notices

- data/compare.yaml
Supersedes https://github.com/ably/docs/pull/2179, same applies as in that PR - this just works off of `nanoc-toolchain` instead
> chore: update roundtrip latency copy for Ably

- content/api/rest-api.textile
This PR:
- Improves the "Register a device for receiving push notifications" section of: docs/api/rest-api#push
[EDU-196: EDU-196: Adds device registration instructions](https://ably.atlassian.net/browse/EDU-196)
> EDU-196: Adds device registration instructions

- content/partials/types/_push_device.textile
Broken link introduced in a release 2 days ago, this PR fixes it.
> Fix broken link, textile was including the : in the URL

- .circleci/config.yml
This pull request updates the `install-nginx` build script to fetch the `build_nginx` script from a specific commit, this will make sure that we use a known and stable version of the `build_nginx` script, and not be at the mercy of any update
> [WEB-3834] Fix the heroku buildpack nginx script to a commit

- content/push/device.textile
- content/push/publish.textile
This PR:
- Adds .NET code examples to the required areas of the recently updated Push notification docs.
- Removes the leftover Flutter code example (to be updated in a separate Flutter code example update PR).
[EDU-888: Add dotNet to push notifications](https://ably.atlassian.net/browse/EDU-888)
> EDU-888: Adds dotnet code examples

- content/push/device.textile
- content/push/publish.textile
This PR:
- Adds .Net code that was accidentally dropped when addressing merge conflicts in https://github.com/ably/docs/pull/2188
- Removes unneeded flutter content 
- Removes unneeded/duplicate code examples from the "Activation lifecycle section."
[EDU-1578](https://ably.atlassian.net/browse/EDU-1578)
[EDU-1578]: https://ably.atlassian.net/browse/EDU-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1578: Corrects code examples

- content/push/device.textile
This PR:
- Adds additional steps to doc from the Push FAQ.
- The user must make amendments to the PEM cert to align with the Ably config
[EDU-1579](https://ably.atlassian.net/browse/EDU-1579)
[EDU-1579]: https://ably.atlassian.net/browse/EDU-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1579: Adds extra required steps from FAQ

- content/push/device.textile
This PR
Adds the following sections:
- Install Ably into your app
- Setup your SDK
Improves the wording of the following sections:
- Configure FCM for Android devices
- Configure APNs for iOS devices
Removes the following section:
- Integrate Ably into your app
- -  The information was misleading. It has been put to one side as potential content for an 'advanced user' section
[EDU-1573: Add installation section extend integrate ably section](https://ably.atlassian.net/browse/EDU-1573)
> EDU-1573: Adds installation section

- content/livesync/outbox-nodes-tables.textile
Updates the privileges section in the LiveSync docs to correctly specify the required postgres user permissions.
* https://ably.atlassian.net/browse/DTP-842
Apologies, I am not familiar with this codebase. Please let me know if I need to run additional steps to generate the docs from textile and create a preview. Thanks.
> livesync: update grant privileges code snippet

- content/getting-started/quickstart.textile
This PR adds an optional loop into the Python quickstart that devs can use to stop the process from exiting in case they're running it outside of a framework.
> [EDU-1585] Add a loop to Python quickstart

- content/spaces/cursors.textile
This PR moves the live cursors payload example to the subscribe section. This is to keep it consistent with the other features and because it makes more sense to view the payload as part of a subscription.
> [EDU-1587] Move Live Cursors payload to subscribe section

- content/chat/rooms/typing.textile
This PR updates `currentlyTyping` to correctly be a set, rather than an array.
> [CHAT-398] currentlyTyping is a set not an array

- content/auth/token.textile
- semicolons - no ASI in sample javascript code please!
- calling the callback inside the try/catch is an antipattern
page to review: token auth
really I would like an authcallback that returns a promise, but until that's implemented, the code snippet for doing this as-is was annoying me
> Auth docs: tweak js code sample

- content/push/configure/device.textile
- content/push/configure/web.textile
- content/push/index.textile
- content/push/publish.textile
This PR:
- Fixes various typos and grammar errors throughout the push documentation, ensuring improved readability and accuracy.
[EDU-1606](https://ably.atlassian.net/browse/EDU-1606)
[EDU-1606]: https://ably.atlassian.net/browse/EDU-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1606: Fixes various typos and grammar errors

- content/getting-started/quickstart.textile
- content/getting-started/setup.textile
This PR updates the minimum version listed in the CDN imports to v2.
Resolves #2239.
> [EDU-1639] Update CDN versions to minimum of v2

- src/components/Head.tsx
- src/components/Layout/Layout.tsx
- src/components/common/meta-title.test.ts
- src/components/common/meta-title.ts
- src/pages/sdks/index.tsx
- src/templates/base-template.tsx
- src/templates/template-data.d.ts
Using the `product` frontmatter data or the template's `currentProduct`, we now prefix the page meta title with the page category, i.e `Pub/Sub` , `API References`. For pages without `product` data, we default to `pub_sub`. 
* WEB-3904
Visit the [review app](https://ably-docs-web-3904-add--8ocjfx.herokuapp.com/) and browse through the pages and check that the titles are showing the prefix as expected.
> [WEB-3904]: Prefix meta title with product frontmatter

- src/components/blocks/external-references/AElementHelpers/check-link-is-internal.test.ts
- src/utilities/link-checks.test.ts
- src/utilities/link-checks.ts
Remove `control-api` as being an external link to allow the internal page to render. Fixes current 404's where `api/control-api`is not being redirected/rendered externally.
* WEB-3951
* [Review App](https://ably-docs-fix-control-a-j1bffi.herokuapp.com/)
> [WEB-3951] Mark control-api as internal link

- content/metadata-stats/metadata/subscribe.textile
- content/push/configure/device.textile
- content/push/index.textile
This PR:
- Adds 'push meta channel' info under a new 'error handling' section
- Updates and improves /metadata/subscribe [meta]log content 
[EDU-1561: Add mention of push meta channel](https://ably.atlassian.net/browse/EDU-1561)
> EDU-1561: Adds 'push meta channel' info under a new 'error handling' section

- src/components/Redoc/GoTopButton.tsx
* Moved the `handleVisibleButton` function inside the `useEffect` hook and added cleanup to remove the event listener when the component unmounts. (`src/components/Redoc/GoTopButton.tsx`)
* Introduced a `scrollOffset` constant to replace the hardcoded value in the `handleVisibleButton` function. (`src/components/Redoc/GoTopButton.tsx`)
* Simplified the `handleScrollUp` function by removing the unnecessary `left` parameter from `window.scrollTo`. (`src/components/Redoc/GoTopButton.tsx`)
* Adjusted the order of CSS classes in the `div` element to improve readability. (`src/components/Redoc/GoTopButton.tsx`)
> Refactoring the scroll event handling and simplifying the scroll-to-top functionality

- content/push/configure/device.textile
- content/push/configure/web.textile
- content/push/index.textile
This PR:
- Adds new copy and links to inform the user they can configure **web browsers** using web push -- while on the "configure **devices**" section.
- Adds new copy and links to inform the user they can configure **devices** using FCM and APNs -- while on the "configure **web browsers**" section.
[EDU-1638](https://ably.atlassian.net/browse/EDU-1638)
[EDU-1638]: https://ably.atlassian.net/browse/EDU-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1638: Adds copy and links to inform user of Web Push availability

- content/chat/setup.textile
Related to https://github.com/ably/ably-chat-js/pull/333
Currently, only the UMD variant of Chat works with ably-js, so we need to point to that.
Also expands the example of how to use the CDN-served library.
See Chat Setup page
> chat: point docs to umd Chat bundle

- content/protocols/pubnub.textile
- we no longer stay connected for 5 minutes, only 2
- we have never provided 5-20 minutes. The original docs said: "In Pubnub’s model, message continuity is available for ‘5-20 minutes’ and up to 100 messages". At some point this was changed to "PubNub message continuity is available for 5-20 minutes for up to 100 messages". The former version makes it clear that this is talking about pubnub itself. The latter sounds like it could be talking about the pubnub adapter.
> Pubnub: tweak message continuity wording

- content/getting-started/setup.textile
This PR updates the text to match the code sample prompting users to use v2 of the JS SDK.
> [EDU-1639] Update CDN text to v2 of JS SDK

- content/spaces/cursors.textile
https://ably.atlassian.net/browse/REA-1868
https://github.com/ably/spaces/pull/333
> Change the description of outboundBatchInterval to reflect last Spaces SDK changes

- content/storage-history/storage.textile
This PR fixes a missed reference to storage time being limited to 24-72 hours that was originally updated in https://github.com/ably/docs/pull/2248.
> Fix missed 24-72 hours in storage

- content/channels/options/index.textile
This PR fixes two mistakes with the Python rewind example:
* Erroneous backtick
* Should be using realtime, not REST
> Fix Python rewind example errors

- src/components/Header/SearchBar/InkeepSearchBar.tsx
- src/components/Header/SearchBar/SearchBar.module.css
- src/components/Header/SearchBar/SearchBar.test.tsx
- src/components/Header/SearchBar/SearchBar.tsx
- src/external-scripts/inkeep.ts
If Inkeep is enabled show the Inkeep search widget instead of the existing search. 
___
_Notes_: 
* Current behaviour of adding the search query to the URL query parameter is not added, whilst awaiting for feedback from Inkeep
* No independent feature flag has been added as no there's no current business requirement to be able to turn on/off search independently from Inkeep chat.
* WEB-3920
* [Preview App](https://ably-docs-web-3920-add--75xwwf.herokuapp.com/docs/) can be used to interact with the Inkeep search widget
* [Homepage](https://ably-docs-web-3920-add--75xwwf.herokuapp.com/docs/)
* [Example page with search in header](https://ably-docs-web-3920-add--75xwwf.herokuapp.com/docs/products/channels) 
* Locally, set the `INKEEP_...` variables to enable Inkeep and the search widget
> [WEB-3920] Add Inkeep search widget

- content/chat/rooms/presence.textile
Update the Chat SDK React hooks to include the correct usePresenceParams as outlined here
https://sdk.ably.com/builds/ably/ably-chat-js/main/typedoc/interfaces/chat_react.UsePresenceParams.html#enterWithData
> Change Chat SDK React usePresence hook to use enterWithData / leaveWithData instead of dataToEnterWith

- content/general/webhooks.textile
When creating a new Webhook integration rule, it wasn't obvious that only message and presence events can be sent as raw payload in webhooks. Trying to do the same with occupancy or lifecycle events would generate an error when trying to create the rule. I have added a small section to the docs to make this clearer, in the hopes we will avoid future confusion.
* [REA-2071](https://ably.atlassian.net/browse/REA-2071)
* [Page to review](https://ably.com/docs/general/webhooks?)
[REA-2071]: https://ably.atlassian.net/browse/REA-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> Integrations: Add note around webhook data envelope support

- content/tutorials/jwt-authentication.textile
This PR updates the JWT authentication tutorial:
* There isn't a need to JSON-encode the JWT
* The content-type shouldn't be `application/json`
* Updated minimum ably-js version to v2+
> fix: JWT shouldn't be JSON-encoded and set correct content-type

- data/yaml/page-content/asset-tracking.yaml
- data/yaml/page-content/channels.yaml
- data/yaml/page-content/chat.yaml
- data/yaml/page-content/livesync.yaml
- data/yaml/page-content/spaces.yaml
- src/components/common/meta-title.test.ts
- src/components/common/meta-title.ts
- src/templates/template-data.d.ts
This PR updates the meta title for pages to correctly include 'Ably' in product names.
> Fix: prefix meta titles with 'Ably' for product names

- content/push/configure/web.textile
This PR:
- Updates the Web Push Activation section:
- Adds instructions for activating via CDN as an alternative to a package manager.
- Refines and rephrases the existing instructions for direct activation of web push.
[EDU-1660](https://ably.atlassian.net/browse/EDU-1660)
[EDU-1660]: https://ably.atlassian.net/browse/EDU-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1660: Adds CDN activation copy

- content/chat/rooms/index.textile
- content/chat/rooms/messages.textile
This change fixes two issues with the chat docs:
- Rooms page missing `RoomOptions` values in 1 example
- Messages page passing the message text incorrectly.
- Chat Rooms
- Chat Messages
> Chat fixes

- content/account/control-api.textile
- static/open-specs/control-v1.yaml
This PR updates the schema version for the Control API stats, as well as removes the `self` and `meta` keys from the response.
> [FIX] Control API Stats response copy

- gatsby-config.ts
- gatsby-node.ts
- package.json
- src/components/Header/SearchBar/SearchBar.tsx
- yarn.lock
See WEB-4120
This pull request includes several changes to improve environment variable management and update dependencies. The most important changes include moving the dotenv configuration to `gatsby-config.ts`, updating the `package.json` dependencies, and modifying the behavior of the search bar component.
Environment variable management:
* [`gatsby-config.ts`](diffhunk://#diff-26b5c624a22b9f24d3e683f7ee5b69788ee6b166a655b7423b6a4c5a1ef6f0a1R1-R6): Added dotenv configuration to load environment variables based on the current environment.
* [`gatsby-node.ts`](diffhunk://#diff-f5fdf00d27b2934559500edae0b37a71958a34e4584f097afeb95260144a761fL1 …
> [WEB-4120] Fix shortcut and gasby env loading

- content/channels/index.textile
Several issues:
- when porting this over from faqs, it was put into the namespace section, which doesn't really make sense, the restrictions on channel names apply whether you're doing anything with namespaces or not. It also conflated restrictions for channel names and namespaces, which is wrong -- in particular, wildcards are fine in channel names.
- https://github.com/ably/docs/commit/54364428a5eed8384703b7cb9b33f4e607644866 , which claimed to just change the style to an active voice, apparently decided all whitespace was now banned, not just newlines (???)
- That commit also decided that "most" browsers have trouble with 2k long urls, which is just wrong.
- "wildcards such as `*`" is a very confusing way of phrasing it. The wildcard is `*`, that wording sounds like it's implying that …
> Correct technical errors in restrictions for channel names and namespaces

- content/chat/setup.textile
tiny but important mistake in the chat code examples, see https://github.com/ably/ably-chat-js/pull/414.
> chat: fix `ChatClient` import statement

- content/chat/connect.textile
- content/chat/rooms/history.textile
- content/chat/rooms/index.textile
- content/chat/rooms/messages.textile
- content/chat/rooms/occupancy.textile
- content/chat/rooms/presence.textile
- content/chat/rooms/reactions.textile
- content/chat/rooms/typing.textile
- content/chat/setup.textile
This PR fixes the TypeDoc links in Ably Chat after an update has changed the link format from `chat_js` to `chat-js` and `chat_react` to `chat-react`.
> Fix TypeDoc links after update

- content/account/organizations.textile
- content/account/sso.textile
- data/yaml/page-furniture/sidebar.yaml
This PR:
- Adds Ably Organizations page
- Includes SSO and SCIM setup
- @denissellu left a [comment](https://ably.atlassian.net/wiki/spaces/PLG/pages/3059777557/Docs+draft+for+Orgs+and+SCIM?focusedCommentId=3350134809) on the original doc. I have not been able to weave this into the content due to lack of clarification (my side).   
- "Should we already list the endpoints we support somewhere, api/Users api/Groups?"
[EDU-1667](https://ably.atlassian.net/browse/EDU-1667)
[EDU-1667]: https://ably.atlassian.net/browse/EDU-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Edu 1667 orgs and SCIM page

- jest.config.js
Tests is having issues due to there being multiple instances of React (examples has many).
> Added examples directory to be ignored in tests

- content/chat/rooms/history.textile
Changes the "direction" argument to Chat history requests to "orderBy", with values "newestFirst" and "oldestFirst".
https://github.com/ably/ably-chat-js/pull/420
> chat: update order params in history

- content/chat/rooms/index.textile
Updates the chat docs to reflect the changes to async `rooms.get()`
[CHA-670]
`/chat/rooms`
[CHA-670]: https://ably.atlassian.net/browse/CHA-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chat: update docs for async room get

- content/chat/connect.textile
- content/chat/rooms/index.textile
per CHADR-062, we renamed some types and restructured the room status / connection handlers.
This change makes these effective in the docs.
`/chat/connections`
`/chat/rooms`
> chat: update room status and connection status

- content/chat/rooms/messages.textile
In chat, the object passed to a listener is called the MessageEventPayload, this contains both a type (describes the event, message.created..) and a message (contains the actual chat message).
We should be clear here in the docs too.
* [messages](http://localhost:8000/chat/rooms/messages)
> Chat: Clarify the message listener input.

- content/chat/connect.textile
This was missed somehow - removes the marker and fixes the conflict.
chat/connection is the page
> chat: fix merge conflict marker in connections

- content/auth/token.textile
The example in production was incorrect and causing the following error `signature verification failed`
* [Jira ticket](https://ably.atlassian.net/browse/EDU-1698).
* [Page to review](https://ably-docs-edu-1698-pyth-u9veih.herokuapp.com/docs/auth/token?lang=python#standard)
> [EDU-1698] - Fix Ably JWT generation with Python

- content/chat/setup.textile
- content/livesync/index.textile
- content/livesync/mongodb/index.textile
- content/livesync/postgres/index.textile
- content/pricing/faqs.textile
- content/spaces/index.textile
- content/spaces/space.textile
- data/yaml/page-content/asset-tracking.yaml
- data/yaml/page-content/chat.yaml
- data/yaml/page-content/livesync.yaml
- data/yaml/page-content/spaces.yaml
This PR updates the product statues for Spaces, Chat, LiveSync and Asset Tracking: 
* Removes the beta tag and status notice from Spaces.
* Removes the beta tag from Chat and the notice about signing up for the beta.
* Removes the beta tag from LiveSync, and moves the status notice to the Postgres and MongoDB connectors (alpha and beta respectively).
* Removes the beta tag from Asset Tracking.
> [EDU-1702] Updates all product statuses to remove beta tags

- content/channels/options/encryption.textile
This PR removes the example of setting encryption when obtaining a channel instance using the realtime interface in Go. This was reverted in https://github.com/ably/ably-go/pull/611 and needs to be reimplemented.
> [EDU-1705] Remove realtime encryption sample for Go

- content/chat/rooms/index.textile
- data/yaml/page-content/chat.yaml
This PR fixes two small bugs noticed after the release of Swift and Kotlin:
* The setup link on the chat homepage was incorrect.
* A sentence under `rooms.release()` was incorrectly displaying for Swift and Kotlin.
> [EDU-1706] Chat post-release fixes

- content/chat/rooms/messages.textile
Adds the update/delete comparison docs for Chat, as these were only present in the repo README.
Two sections on Chat/Rooms/Messages
> chat: add update/delete comparison docs

- content/chat/connect.textile
- content/chat/rooms/history.textile
- content/chat/rooms/index.textile
- content/chat/rooms/messages.textile
- content/chat/rooms/occupancy.textile
- content/chat/rooms/presence.textile
- content/chat/rooms/reactions.textile
- content/chat/rooms/typing.textile
- content/chat/setup.textile
- examples/chat-online-status/react/src/app/layout.tsx
- examples/chat-online-status/react/src/app/page.tsx
- examples/chat-room-history/react/src/app/chat/page.tsx
- examples/chat-room-history/react/src/app/layout.tsx
- examples/chat-room-history/react/src/app/page.tsx
- examples/chat-room-messages/react/src/app/layout.tsx
- examples/chat-room-messages/react/src/app/page.tsx
- examples/chat-room-reactions/react/src/app/layout.tsx
- examples/chat-room-reactions/react/src/app/page.tsx
- examples/chat-typing-indicator/react/src/app/layout.tsx
- examples/chat-typing-indicator/react/src/app/page.tsx
Replaces all references to @ably/chat/react with @ably/chat, as part of combining all packages into one, per CHADR-083.
JS PR: https://github.com/ably/ably-chat-js/pull/448
All chat pages - check that any references to `@ably/chat/react` are replaced with `@ably/chat`, and imports copied over.
> chat: combine chat + react packages into one

- data/yaml/page-content/chat.yaml
- src/components/Homepage/BodySection/BodySection.tsx
- src/components/ProductPage/BodySection/BodySection.tsx
This PR includes updates to internal link handling and call-to-action (CTA) links in the `BodySection` components for both the homepage and product pages, now we make sure that we check to see if the links are internal or external links privided in the call to action.
This will fix broken links on the pubsub and asset tracking, and improves on this #2381
> [WEB-4192] Fix broken call to action internal links

- .circleci/config.yml
- app.json
Review apps are currently failing due to a broken addon, and in fairness we don't need this addon by default so I've removed it. I also brought over some other improvements from other Gatsby CI flows
This pull request includes significant changes to the CircleCI configuration and the `app.json` file. The primary focus is on restructuring the build and test processes, particularly concerning the handling of nginx.
* Removed the `build-nginx` command and `install-nginx` job, and replaced them with a new `test-nginx` job. [[1]](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L17-L42) [[2]](diffhunk://#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L56-L61)
* Updated the `build` job to persist the `public` directory to the workspace.
* …
> [WEB-4165] Review apps & CI updates

- package.json
- src/components/Header/Dropdown/Button/DropdownButton.tsx
- src/components/Header/HamburgerMenu/HamburgerDropdown/HamburgerSidebarRenderer/HamburgerSidebarDropdownPopulatedItem/MaybeShowHamburgerSummaryLink.tsx
- src/components/Header/SearchBar/SearchBar.tsx
- src/components/Header/SearchBar/SuggestionBox.tsx
- src/components/Homepage/BodySection/Card/SdkCard.tsx
- src/components/Markdown/CodeBlock.tsx
- src/components/Notification/Notification.tsx
- src/components/ProductPage/BodySection/Card/Links.tsx
- src/components/Redoc/GoTopButton.tsx
- src/components/SDKInterfacePanel/SDKInterfacePanel.tsx
- src/components/SDKsPage/Card/index.tsx
- src/components/Select/Select.tsx
- src/components/Sidebar/ExpandableIndicator.tsx
- src/components/blocks/Html/__snapshots__/Html.test.tsx.snap
- src/components/blocks/dividers/Aside.tsx
- src/components/blocks/software/Code/ApiKeyIndicator.tsx
- src/components/blocks/software/Code/CodeCopyButton.tsx
- src/components/blocks/software/Pre.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/CopyLink.tsx
- src/components/blocks/wrappers/__snapshots__/ConditionalChildrenLanguageDisplay.test.js.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- src/pages/api/control-api.tsx
- yarn.lock
By bumping `ably-ui` to `15.3.1`, we perform a repo-wide GUI icon replacement, bringing in the new hero icons and the naming convention that comes with them. This PR aims to make these substitutions based upon the recommended translations in the design team's Figma docs.
Review env: https://ably-docs-bump-ably-ui--ffsskv.herokuapp.com/
Bot's word:
This pull request includes multiple updates to the project, focusing on upgrading dependencies and updating icon usage across various components. The most important changes are summarized below:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L42-R42): Updated the `@ably/ui` dependency from version `^15.1.0` to `^15.3.1`.
* [`src/components/Header/Dropdown/Button/DropdownButton.tsx`](diffhunk:// …
> [WEB-4185] Bump ably UI to 15.3.1, perform icon name replacement

- content/channels/index.textile
- content/messages/batch.textile
- content/messages/index.textile
This PR adds content for message conflation and how to enable it. It also adds a note stating that server-side batching is mutually exclusive with message conflation on a channel / channel namespace basis.
This PR is related to https://github.com/ably/docs/pull/2404
> [EDU-1661] Add documentation for message conflation

- content/messages/index.textile
This PR moves the information from [this FAQ](https://faqs.ably.com/what-is-the-format-of-the-routingkey-for-an-amqp-or-kinesis-reactor-rule) into the docs. It covers the syntax used for message conflation and routing and partition keys for integrations. 
Note the `#conflation` link will be added in a separate PR related to message conflation.
> [EDU-1687] Add message routing and conflation syntax info

- src/data/nav/pubsub.ts
The metadata overview page (`/metadata-stats/metadata`) was missed out in the migration to the new nav. This adds it back in.
> Add metadata overview into the navigation

- examples/chat-room-messages/page.md
- examples/pub-sub-channel-messages/javascript/README.md
- examples/pub-sub-channel-messages/page.md
- examples/pub-sub-channel-messages/react/README.md
- examples/pub-sub-connection-state/page.md
- examples/pub-sub-history/page.md
- examples/pub-sub-message-encryption/javascript/README.md
- examples/pub-sub-message-encryption/page.md
- examples/pub-sub-presence/page.md
- examples/spaces-avatar-stack/page.md
- examples/spaces-component-locking/page.md
- examples/spaces-live-cursors/page.md
- examples/spaces-member-location/page.md
Fixes incorrect Vite/Next Ably key variable names in READMEs.
Spotted by coderabbit in https://github.com/ably/docs/pull/2437#discussion_r1965121216
> Fix incorrect Vite/Next Ably key variable names in READMEs

- src/external-scripts/inkeep.ts
Bumps Inkeep to `0.3.19` and adds a menu link to Hubspot meeting request.
This pull request to `src/external-scripts/inkeep.ts` includes updates to the Inkeep chat integration and enhancements to the AI chat settings. The most important changes include updating the Inkeep UI Kit version and adding new call-to-action options for users.
Updates to Inkeep chat integration:
* Updated the Inkeep UI Kit version from `0.3.9` to `0.3.19` to ensure compatibility with the latest features and bug fixes.
Enhancements to AI chat settings:
* Added a new call-to-action option "Request a meeting" with a link to book a demo, including settings to pin it to the toolbar and keep the modal open.
* Modified the existing "Chat with support" call-to-action to pin it to the toolbar for easier access.
[Screencast …
> [WEB-4211] Add 'Request a meeting' button to Inkeep chat

- data/createPages/index.ts
- src/components/Layout/Header.tsx
- src/pages/docs/api/control-api.tsx
- src/pages/docs/examples.tsx
- src/pages/docs/how-to/pub-sub.tsx
- src/pages/docs/index.tsx
- src/pages/docs/sdks/index.tsx
- src/templates/base-template.tsx
Docs routing release went alright, nothing bricked it, but the canonical link generator was overlooked, resulting in [broken canonical links](https://app.contentkingapp.com/websites/14-2162789/alerts/17601674/pages?filter=eyJmaWx0ZXIiOnsic3RhdHVzIjpbImNoYW5nZWQiXX0sInNvcnRCeSI6eyJrZXkiOiJyZWxldmFuY2UiLCJkaXJlY3Rpb24iOmZhbHNlfX0%3D) - affecting SEO performance.
This PR fixes this by explicitly adding in explicit section prefixes to the paths passed into the `canonicalUrl` helper.
> [WEB-3950] fix: update canonical link generator to include section prefix

- content/push/configure/device.textile
The server side activation for Android push was actually Kotlin and not Java: https://github.com/ably/docs/issues/2450
This update adds the Java equivalent.
> [EDU-1836] - Updated java example of server side activation for push

- src/components/Layout/RightSidebar.tsx
- src/data/languages/languageData.ts
This PR adds two small fixes identified after the new navigation launched:
* Kotlin was missing as an available language for Pub/Sub causing it to not render correctly
* Updates the link to raise a change request after merging https://github.com/ably/docs/pull/2383
> Small fixes after navigation release

- src/components/Layout/Layout.tsx
- src/components/Layout/LeftSidebar.tsx
- src/components/Layout/utils/nav.ts
- src/components/Redoc/Loader.tsx
- src/components/Redoc/utils.ts
- src/contexts/layout-context.tsx
- src/pages/docs/api/control-api.tsx
This PR fixes a bunch of miscellaneous things:
- the [control api is broken](https://ably.com/docs/api/control-api) as the path to the data YAML isn't right. This PR updates the path to one that exists, but only in a production env
- adds a script to override clicks on menu items in the redoc navigator as it's pretty broken. The script ensures that the targeted menu is opened when a heading is clicked (https://github.com/ably/docs/pull/2393, https://ably.atlassian.net/browse/WEB-4176)
- fixes the colour on the selected header on the LeftSidebar (https://ably.atlassian.net/browse/WEB-4245)
- prevents active page highlighting on both the main links and the API references in the LeftSidebar when the tree indices match
Review link: https://ably-docs-fix-control-v-32pbux.herokuapp.com/
> [WEB-4211, WEB-4176, WEB-4245] Redoc and LeftSidebar fixes

- config/nginx.conf.erb
Getting a CORS issue when pulling the control api YAML from docs.ably.com. This PR opens up access to YAML files as we don't care about who accesses YAMLs we make publicly accessible.
This pull request includes a change to the `config/nginx.conf.erb` file to enhance the handling of specific file types in the Nginx configuration.
* [`config/nginx.conf.erb`](diffhunk://#diff-8536d045800ebd99dc58c8e5d9fab522ded64838c446ba361c1c4c6d8ce3b4d4L92-R92): Updated the `location` block to include both `.json` and `.yaml` file types, allowing for proper handling and setting of headers for these file types.
> [WEB-4211] chore: allow open access to yaml files

- src/components/Layout/Header.tsx
A bug has been raised where the link at the top right of the docs to go to support now links to `/docs/support` which doesn't exist, so a 404 is returned. This will likely have been a side effect to some changes to the navigation of the docs recently released. A screenshot of the link is shown below:
> Fix bug where support link goes to /docs/support

- content/messages/index.textile
Previous description for idempotency was confusing. You don't update a message with an ID, you provide an ID before publishing. We also did not link to any idempotent docs.
> Update Message object attributes

- content/push/configure/device.textile
This PR:
- Adds new instructions to the `/push/configure/device` section.
- Keeps Apple Dev Portal steps generic yet useable.
- Creates subsection for ios configuration
- Token-based auth, and Cerifatte base auth.
- Crates new anchor IDs.
[EDU-1652](https://ably.atlassian.net/browse/EDU-1652)
[EDU-1652]: https://ably.atlassian.net/browse/EDU-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-1652: Adds token auth copy

- content/metadata-stats/metadata/subscribe.textile
This pull request includes a change to the `content/metadata-stats/metadata/subscribe.textile` file to correct the JSON syntax in the example provided.
* [`content/metadata-stats/metadata/subscribe.textile`](diffhunk://#diff-6f6001432a7ceb234debf544e211f40c6dc4e652e18f057fbafaf675e44b3821L39-R39): Corrected JSON syntax by replacing single quotes with double quotes in the example of subscribing to all metachannels.
> [WEB-3484] fix: use character encodings for double quotes in subscribe textile to avoid processing

- src/components/Redoc/Loader.tsx
- src/components/blocks/software/Code/MultilineCodeContent.tsx
Seems like this is enough for redoc's responsive behaviour to kick in.
Also contains an additional fix to specify api keys when truncating code block text contents.
This pull request includes a small change to the `Loader` component in the `src/components/Redoc/Loader.tsx` file. The change updates the `redoc-container` div to include a new CSS class for maximum width.
* [`src/components/Redoc/Loader.tsx`](diffhunk://#diff-67c7665f011e4bbb465e16730aca10a5b05f2a8546e001b913e0f680f9af54feL60-R60): Added `max-w-[100vw]` class to the `redoc-container` div to ensure it does not exceed the viewport width.
> [WEB-4263] fix: redoc responsiveness / code block api key truncation

- content/chat/rooms/moderation/lambda.textile
- src/data/nav/chat.ts
Add AWS Lambda before publish rule documentation.
[CHA-830](https://ably.atlassian.net/browse/CHA-830)
[CHA-830]: https://ably.atlassian.net/browse/CHA-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AWS Lambda before publish rule

- content/account/control-api.textile
- content/metadata-stats/stats.textile
- Clarified the scope of account statistics
- Removed account stats from the REST API - there is no such API, API keys are scoped to apps only. Not sure how this was ever documented.
- Improved clarity around obtaining account IDs:. Using an <aside>. Is this correct?
- Found it odd that in code samples we refer to, for example, {ACCOUNT_ID} then in the docs we refer to that variable as @accountId@. I don't follow the inconsistency. Happy to change code examples to use accountId if preferred, but I don't see any merit in inconsistency in the same page.
- Adjusted headings, specifically differentiating between “Statistics response payload” and “Statistics response”, clarifying the API response structure. I don't think it was clear before what a statistics response payload was vs statistics …
> Update Stats docs

- src/external-scripts/inkeep.ts
There's a bug where the inkeep search bar dies between templates. Never used to be the case, but now it is.
The surrounding inkeep instantiation logic is called on template change, but the search bar does not reinitialise. Perhaps there is a flag stored somewhere that prevents this.
My first approach would be to, within this inkeep logic, check for if `#inkeep-search` has child nodes and then remount from there if not, but the instantiation is async and there is no promise to latch onto, so I'm just going to remount every time. Suboptimal, but seems to do the job and there's no time for anything else.
Initial thread: https://ably-real-time.slack.com/archives/C01LR5XFHFX/p1743429479133079
> [WEB-4296] fix: enforce remounting of inkeep search bar

- src/components/ProductNavigation/ProductNavigation.tsx
- src/components/common/meta-title.test.ts
- src/components/common/meta-title.ts
- src/data/content/homepage.ts
- src/data/index.ts
- src/data/languages/languageData.ts
- src/data/nav/index.ts
- src/data/nav/liveobjects.ts
- src/data/types.ts
- src/templates/template-data.d.ts
Adds navigation for LiveObjects product in `src` folder.
This was added by searching for "livesync" in "src" folder and adding corresponding "liveObjects" sections where necessary.
Currently missing:
> Add LiveObjects product to site navigation

- package.json
- src/styles/global.css
- yarn.lock
WEB-4266 Since docs using the ably-ui `Header` component and imported some old Meganav css files. 
The docs nav still looks good and not been touched :D 
This pull request includes updates to dependencies and style imports. The most important changes are:
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L42-R42): Updated the `@ably/ui` dependency from version `15.8.1` to `16.0.0`.
Style import adjustments:
* [`src/styles/global.css`](diffhunk://#diff-03cc26efc9f06a95cd86aef185af462b72cc9d548a58177f8972837895f2de9eL7-R7): Removed imports for `Meganav` and `Footer` components from `@ably/ui/core` styles.
> Upgrade ably-ui 16.0.0 - new Meganav & Footer

- content/liveobjects/rest-api.textile
- src/data/nav/liveobjects.ts
Add new page in the "API References" part of the product docs which details the REST APIs available for interacting with live objects.
> Live objects: Add REST API docs

- CONTRIBUTING.md
In this PR is a new CONTRIBUTING.md file, inside `/examples`, which contains the guide for contributing to examples within the docs.
> DRAFT: Add contributing guide for examples

- content/livesync/mongodb/index.textile
Remove wording as such from docs
We don't call it beta anywhere else, so remove that wording.
> MongoDB LiveSync connector is not Beta

- examples/spaces-live-cursors/javascript/src/script.ts
- examples/spaces-live-cursors/react/src/components/LiveCursors.tsx
When only 1 tab is open, the users cursor was not rendering, this is because the subscriber doesn't kick in when it's only that user publishing. 
To test this. Go to `/examples`. `yarn install`, Move `.env.example` to `.env.local`, Update `VITE_PUBLIC_ABLY_KEY` with your ABLY API KEY. Run `yarn run spaces-live-cursors-javascript`. Open one tab to `http://localhost:5173`, and move your cursor about.
> Live cursors Javascript example, users cursor not rendering.

- content/chat/rooms/typing.textile
Updating the typing portion of the docs to reflect the move from presence to ephemeral messaging.
For more context, please see [CHADR-093]
> Chat: Update typing indicator API documentation

- content/api/rest-api.textile
- content/push/publish.textile
adds REST API reference and conceptual docs for batch push
see implementation here: https://github.com/ably/realtime/pull/7217
[PUB-1319](https://ably.atlassian.net/browse/PUB-1319)
[PUB-1319]: https://ably.atlassian.net/browse/PUB-1319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add batch push publish docs

- src/external-scripts/inkeep.ts
WEB-4280
[Review App](https://ably-docs-web-4280-inke-sotlbo.herokuapp.com/docs)
This pull request to `src/external-scripts/inkeep.ts` includes several updates to enhance the functionality of the Inkeep integration and improve the user interface. The most important changes include updating the script version, integrating PostHog for feature flagging, adding a new tool for contacting sales, and applying custom styles to the chat interface.
Enhancements to Inkeep integration:
* Updated the Inkeep script to version `0.5.40` and integrated PostHog for feature flagging. [[1]](diffhunk://#diff-da7f7711b6957ca8a9bd500d1c8e3dc0403363f49fe3eff8381e473da6386cdeR2-R17) [[2]](diffhunk://#diff-da7f7711b6957ca8a9bd500d1c8e3dc0403363f49fe3eff8381e473da6386cdeL85-R140)
* Added a new tool for detecting …
> [WEB-4280] Add Inkeep intent configuration

- static/open-specs/control-v1.yaml
This PR adds a link to the OpenSpecs file for the Control API intro it's introductory paragraph.
> [EDU-1884] Add link to Control API schema in rendered reference

- static/open-specs/control-v1.yaml
See WEB-4194 for more details
Add ControlAPI fields to namespaces for conflation, and clean up batching fields
This pull request includes changes to the `static/open-specs/control-v1.yaml` file to update the message batching and conflation configurations. The most important changes involve the removal of the `batchingPolicy` field and the addition of new fields related to message conflation.
Changes to message batching and conflation configurations:
* Removed the `batchingPolicy` field from the configuration. [[1]](diffhunk://#diff-c3f40cc04a5166b4909647b17180a6605d4505faf64b7962cab695ff3ef62039L4876-L4880) [[2]](diffhunk://#diff-c3f40cc04a5166b4909647b17180a6605d4505faf64b7962cab695ff3ef62039L4925-R4934) [[3]](diffhunk://#diff-c3f40cc04a5166b4909647b17180a6605d4505faf64b7962cab695ff3ef620 …
> [WEB-4194] Conflation ControlAPI

- content/push/publish.textile
This PR:
- Adds `ttl` field to payloads for Web Push compatibility.
- Improved code consistency across realtime and REST variants for:
- `deviceId`
- `clientId`
- recipient attributes
https://ably.atlassian.net/browse/EDU-1883
> EDU-1883: Adds new ttl line of code

- src/components/Examples/ExamplesGrid.tsx
It's fine to use the Asset Tracking color for LiveObjects for now, since we don't have any examples for Asset Tracking and aren't likely to build any in the near future.
> Add comment explaining reusing the assetTracking badge color for liveObjects in ExamplesGrid

- content/chat/index.textile
Adds the product to the "about" page so it appears on the tab, as it currently says PubSub.
> chat: add product to about page

- src/external-scripts/hubspot.test.ts
- src/external-scripts/hubspot.ts
When the conversation  meta tag is present, open the hubspot chat with the relevant query parameter.
Use review app to complete journey below. On the last page visit, the chat should popup
[Platform](https://website-main-t4yfv4bfuhczstedk.herokuapp.com/docs/platform)
[Chat Setup](https://website-main-t4yfv4bfuhczstedk.herokuapp.com/docs/chat/setup)
This pull request introduces new functionality to the Hubspot integration by adding the ability to open the chat widget based on a meta tag in the document. The changes include updates to the test cases, global window interface, and the main Hubspot function.
* [`src/external-scripts/hubspot.ts`](diffhunk://#diff-1c934127749e2cd330bf85ba35e376d92f3304b3b09602ec674ff68cc5486d40L25-R47): Added `openFromMetaTag` function to check for a meta tag …
> [WEB-4261] Open Hubspot chat when conversation Meta tag is present

- content/api/realtime-sdk/channels.textile
- content/liveobjects/batch.textile
- content/liveobjects/counter.textile
- content/liveobjects/index.textile
- content/liveobjects/lifecycle.textile
- content/liveobjects/map.textile
- content/liveobjects/quickstart.textile
- content/liveobjects/typing.textile
- src/data/nav/liveobjects.ts
Adds LiveObjects product documentation to `content` section. Final docs structure can be found here: https://ably.atlassian.net/wiki/spaces/LOB/pages/3839623174/LORFC-001+LiveObjects+Product+Docs+structure.
This PR adds documentation for next LiveObjects pages:
Resolves [PUB-773](https://ably.atlassian.net/browse/PUB-773)
Site navigation for LiveObjects is added in https://github.com/ably/docs/pull/2464, but can be moved into this PR if requested.
[PUB-773]: https://ably.atlassian.net/browse/PUB-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PUB-773] LiveObjects product docs

- src/components/LanguageButton/LanguageButton.tsx
- src/components/Layout/LanguageSelector.tsx
- src/components/Layout/LeftSidebar.test.tsx
- src/components/Layout/LeftSidebar.tsx
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- src/contexts/layout-context.tsx
- src/templates/base-template.tsx
Linked to https://ably.atlassian.net/browse/WEB-4327.
If no lang param is supplied, it fell back to the first language defined at the product level in the data, which doesn't always apply as pages within a product can have differing permutations of applicable languages. Instead, it takes from the first language set on the template itself.
Also removes a duplicate setting of the languages context var from a template, and removes some extra baggage from the LayoutContext that we don't need anymore / can be used from existing data.
Review link: https://ably-docs-web-4327-non--2yikws.herokuapp.com/docs/api/realtime-sdk/push
> [WEB-4327] Fix default language setting on non-JS templates

- content/chat/connect.textile
- content/chat/rooms/history.textile
- content/chat/rooms/index.textile
- content/chat/rooms/messages.textile
- content/chat/rooms/occupancy.textile
- content/chat/rooms/presence.textile
- content/chat/rooms/reactions.textile
- content/chat/rooms/typing.textile
- content/chat/setup.textile
- examples/chat-online-status/react/src/App.tsx
- examples/chat-room-history/react/src/App.tsx
- examples/chat-room-history/react/src/Chat.tsx
- examples/chat-room-history/react/src/Home.tsx
- examples/chat-room-messages/react/src/App.tsx
- examples/chat-room-reactions/react/src/App.tsx
- examples/chat-typing-indicator/react/src/App.tsx
- examples/package.json
- updates all chat examples to use the new subpath import for react APIs from the ably-chat-js SDK. see https://github.com/ably/ably-chat-js/pull/525 for the SDK changes.
- bumps chat JS SDK version to 0.6 in anticipation of the release which will include these changes.
- i assume some part of CI will fail because this version does not exist yet - do not merge this until that change is released and CI passes
> ably-chat-js react subpath changes

- content/liveobjects/index.textile
- content/liveobjects/quickstart.textile
The examples for LiveObjects will be added in a separate PR [1] and require a new examples page structure released in production. In order to allow us to release the LiveObjects docs, we remove the references to the example apps for now. Will revert this commit and set the correct links once new examples page structure is released.
[1] https://github.com/ably/docs/pull/2437
> Remove references to example app from LiveObjects docs

- CONTRIBUTING.md
- src/components/blocks/dividers/Aside.tsx
This PR adds a new type of callout for flagging features as experimental.
> [EDU-1925] Add a new callout option for experimental features

- src/external-scripts/inkeep.test.ts
- src/external-scripts/inkeep.ts
Use the device ID from the meta tag as the Inkeep user ID when the user is not logged in.
This pull request enhances the `inkeepChatIdentifyUser` functionality by adding support for identifying users via a `device_id` meta tag when a user UUID is not provided. It also includes corresponding test updates to ensure the new behavior is correctly implemented.
* [`src/external-scripts/inkeep.ts`](diffhunk://#diff-da7f7711b6957ca8a9bd500d1c8e3dc0403363f49fe3eff8381e473da6386cdeL283-R293): Modified `inkeepChatIdentifyUser` to check for a `device_id` meta tag as a fallback when the `user` object is not provided. The `id` is now determined by the user UUID if available, or the `device_id` otherwise.
* `src/external-scripts/inkeep.test.ts`: Added two new test cases to verify the updated behavior: …
> [WEB-4277] Use device ID for Inkeep user

- content/integrations/index.textile
- content/integrations/streaming/datadog.textile
- content/pricing/enterprise.textile
- content/pricing/pro.textile
- content/pricing/standard.textile
- src/data/nav/platform.ts
This PR introduces documentation for the Ably Datadog integration, covering:
- How the integration works.
- Installation and configuration steps.
- The type of data sent to Datadog.
- Availability details (the feature is exclusive to enterprise-grade committed use customers; others should contact sales for upgrade options). 
- Additionally, this documentation includes details on Datadog-Lite trials.
[EDU-576](https://ably.atlassian.net/browse/EDU-576)
[EDU-576]: https://ably.atlassian.net/browse/EDU-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EDU-576: Datadog integration

- content/getting-started/javascript.textile
- src/components/blocks/list/Ol.tsx
- src/components/blocks/list/Ul.tsx
- src/data/nav/pubsub.ts
- src/styles/global.css
This PR adds a new getting started guide for Ably Pub/Sub in JavaScript. 
It includes;
* A new getting started guide for Pub/Sub in JavaScript.
* Adds the guide to the existing 'getting started' section for now. Other items will be moved/removed once there are more guides. 
* Adjusts the padding on `h2`, `ol` and `ul` elements for readability in the getting started guide.
> [EDU-1845] Pub/Sub getting started in JavaScript

- src/components/Examples/ExamplesFilter.tsx
- src/components/Examples/filter-search-examples.ts
- src/data/examples/index.ts
- src/data/examples/types.ts
Removed the use case filters from examples page as they're not currently needed.
Updated product filters by removing the products that have no examples for, asset tracking, liveobjects, livesync.
> Remove use cases filters and update product filters

- content/channels/options/deltas.textile
This PR:
- Makes a quick fix to the broken `<img>` syntax.
- For the page `/docs/channels/options/deltas`.
To save you a few seconds, here is the link to the fix: https://ably-docs-edu-1931-delt-2kfkfn.herokuapp.com/docs/channels/options/deltas 😃 
https://ably.atlassian.net/browse/EDU-1931
> EDU-1931: Fixes broken img syntax

- content/channels/options/index.textile
- content/liveobjects/inband-objects.textile
- src/data/nav/liveobjects.ts
Updates the Pub/Sub channel options docs to describe the new channel parameter for inband objects. Adds a new page to the advanced section of the LiveObjects docs that fully describes the feature.
> liveobjects: add inband objects docs

- content/chat/connect.textile
- content/chat/rooms/index.textile
- content/chat/rooms/occupancy.textile
- content/chat/rooms/presence.textile
- content/chat/rooms/reactions.textile
- content/chat/rooms/typing.textile
- content/chat/setup.textile
[CHA-916](https://ably.atlassian.net/browse/CHA-916) and  [CHA-874](https://ably.atlassian.net/browse/CHA-874)
Chat is moving to a single channel, this includes changes to how features are enabled in the Chat SDK.
- Highlight chat room<>channel relationship.
- Remove feature specific discontinuity handlers.
- Add note on occupancy feature's default state and costs.
- Remove mention of feature enablement.
- Update capability definition.
[CHA-916]: https://ably.atlassian.net/browse/CHA-916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHA-874]: https://ably.atlassian.net/browse/CHA-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chat: Update chat docs for single channel changes

- package.json
- src/components/Layout/Header.test.tsx
- src/components/Layout/Header.tsx
- src/components/Layout/LanguageSelector.tsx
- src/components/Layout/utils/nav.ts
- src/components/SDKInterfacePanel/SDKInterfacePanel.tsx
- src/components/blocks/software/Code/ApiKeyIndicator.tsx
- yarn.lock
Fixes two things from Matt's docs feedback:
- sorts out the styling classes on the nav outer columns, not sure when this regressed but Tailwind wasn't picking up the width classes (https://ably-real-time.slack.com/archives/C01LR5XFHFX/p1746537594249259)
- left nav doesn't respect and maintain product context when navigating from the homepage to a product page (https://ably-real-time.slack.com/archives/C01LR5XFHFX/p1746540944026369)
Also improves responsive behaviour for the header now that we have a TabMenu section up there taking more space.
Review link: https://ably-docs-web-4367-fix--5jgh9r.herokuapp.com/
> [WEB-4367] Fix column dimensions, default menu expansion behaviour

- examples/pub-sub-occupancy/javascript/src/script.ts
- examples/pub-sub-occupancy/react/src/App.tsx
The pub-sub-occupancy examples for both javascript and react were hardcoding the channel name. This PR fixes that.
> Fixed issue where pub-sub-occupancy channel name is hard coded

- package.json
- src/components/Homepage/Changelog.tsx
- yarn.lock
This PR fixes a bug on the changelog description where the parsing failed, so, i'm now just using the default browser parser
> [WEB-4259] Fix Changelog description homepage

- package.json
- src/data/content/homepage.ts
- yarn.lock
This PR:
* Upgrades ably-ui to 16.2.2 to remove the 'coming soon' from LiveObjects
* Re-orders the homepage tiles to reflect the side navigation.
> [EDU-1937] Update homepage tiles for LiveObjects release

- content/pub-sub/advanced.textile
This PR:
- Re-writes idempotent publishing section to improve clarity
- Improves the general narrative of the article.
- Clarifies that `idempotentRestPublishing` is `true` on current APIs for REST and realtime SDKs (except on older libraries with API version < 1.2).
[EDU-1469: Idempotent publishing doesn't describe idempotent realtime publishing](https://ably.atlassian.net/browse/EDU-1469)
> EDU-1469: Re-writes idempotent publishing section to improve clarity

- content/liveobjects/typing.textile
Decided to rename to `AblyObjectsTypes` to avoid using a generic name like `ObjectsTypes` in a global namespace, see [1]
[1] https://github.com/ably/ably-js/pull/2007#discussion_r2054349487
> Rename `ObjectsTypes` to `AblyObjectsTypes`

- src/components/Layout/Layout.tsx
From the MDX work, we set `overflow-x` on the outer container in the layout because it solves a lot of element constraint problems. However, the patchwork quilt of js that is redocly's UI falls apart if you do this.
This PR conditionally sets the overflow property depending on whether you're on the control api or not.
> [WEB-4394] fix: only set overflow-x on layout container when not control api

- content/chat/index.textile
Add a link to the JavaScript/TypeScript getting started guide in the first section of the chat intro.
Add a "What's next" section at the end of the chat intro page.
> Add link to JS getting started in first section of chat intro

- content/api/realtime-sdk.textile
- content/api/realtime-sdk/authentication.textile
- content/api/realtime-sdk/channel-metadata.textile
- content/api/realtime-sdk/channels.textile
- content/api/realtime-sdk/connection.textile
- content/api/realtime-sdk/encryption.textile
- content/api/realtime-sdk/history.textile
- content/api/realtime-sdk/messages.textile
- content/api/realtime-sdk/presence.textile
- content/api/realtime-sdk/push-admin.textile
- content/api/realtime-sdk/push.textile
- content/api/realtime-sdk/types.textile
- content/api/rest-sdk.textile
- content/api/rest-sdk/authentication.textile
- content/api/rest-sdk/channel-status.textile
- content/api/rest-sdk/channels.textile
- content/api/rest-sdk/encryption.textile
- content/api/rest-sdk/history.textile
- content/api/rest-sdk/messages.textile
- content/api/rest-sdk/presence.textile
- content/api/rest-sdk/push-admin.textile
- content/api/rest-sdk/types.textile
- content/api/sse.textile
- data/transform/index.js
- gatsby-config.ts
- src/templates/apiReference.tsx
- src/templates/base-template.tsx
- src/templates/document.tsx
- yarn.lock
In an attempt to speed up the rendering of pages using the `document.tsx` template (textile files) we discovered that the old inline TOC generation could in some cases take north of 500ms to complete and since it isn't used anymore we removed it completely.
The Gatsby packages were all upgraded as well in an effort to resolve a race condition in the image processing, but didn't reliably resolve the issue. 
Some unused types were cleaned up in the process too.
> [WEB-4356] Drop inline TOCs from textile

- content/chat/getting-started/javascript.textile
Fixes a couple of issues with the javascript project setup here:
- Fixes usage of undocumented `tsc` requirement, now this is explicitly installed with NPM and used from the installed package rather than expected to be installed globally.
- Fixes `npm install` before `npm init -y`, both of these commands create `package.json` if it doesn't already exist but generally you're supposed to init the project first.
- General minor technical wording improvements
> Improve getting started project setup instructions

- content/chat/connect.textile
- content/chat/getting-started/javascript.textile
- content/chat/rooms/index.textile
- content/chat/rooms/messages.textile
- content/chat/rooms/occupancy.textile
- content/chat/rooms/presence.textile
- content/chat/rooms/reactions.textile
- content/chat/rooms/typing.textile
- content/chat/setup.textile
- examples/chat-typing-indicator/javascript/README.md
- src/data/languages/languageData.ts
- Contains all the changes relating to single channel migration.
> Chat single channel updates

- content/chat/getting-started/react.textile
- src/data/nav/chat.ts
[CHA-898](https://ably.atlassian.net/browse/CHA-898)
Adding a getting started guide for Chat with React and Vite
- Looks like the formatting on the page for React code blocks is a bit off
[CHA-898]: https://ably.atlassian.net/browse/CHA-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chat getting started react guide

- package.json
- src/components/Layout/LeftSidebar.tsx
- src/data/nav/assettracking.ts
- src/data/nav/chat.ts
- src/data/nav/liveobjects.ts
- src/data/nav/livesync.ts
- src/data/nav/pubsub.ts
- src/data/nav/spaces.ts
- yarn.lock
Updates the product icons in the left-hand nav for product headers in the closed state. They all now use the heavier stroke weight to bring them in line with the Platform icon.
Test would be go to a random product page like [this](https://ably-docs-web-4401-prod-ajcwmk.herokuapp.com/docs/chat/rooms/messages), all of the icons in the left bar should be as thick as each other.
> [WEB-4401] Update nav product idents to heavier-stroked variants

- content/partials/types/_push_admin.textile
This PR makes it clear that the push admin channel subscription enumeration only returns those devices specifically subscribed to receive push notifications.
> Fix: make it clear in push admin that it is a push sub

- static/open-specs/chat.yaml
Bumping the version in the API docs to 3.0.0 to reflect the move to single channel.
> Chat: Bump api version in API docs

- content/liveobjects/quickstart.textile
This fixes the LiveObjects quick start examples:
- decrementing a counter from 5 by 2 results in 3
- align the setting of `love` in the map with the comment
> Fix the LiveObjects quick start examples

- content/account/app/index.textile
- content/auth/index.textile
- content/channels/options/index.textile
- content/connect/index.textile
- content/metadata-stats/metadata/index.textile
- content/presence-occupancy/index.textile
- content/push/index.textile
This PR updates existing page titles to include the topic, and/or 'overview' when referring to a section. This is to avoid duplication of page titles throughout. It does not effect the side navigation.
> [EDU-1974] Ensure page titles aren't duplicated with use of 'overview'

- content/push/publish.textile
Raised an issue in [this repo](https://github.com/ably/docs/issues/2638), there was a Swift code sample for adding extras param to the push notifications section missing.
> Added extras to push docs for Swift

- static/open-specs/chat.yaml
Add HTTP API reference for message reactions.
[CHA-976]
[CHA-976]: https://ably.atlassian.net/browse/CHA-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add chat message reactions HTTP API reference docs

- content/getting-started/kotlin.textile
- src/data/nav/pubsub.ts
Add Kotlin getting started to pubsub
> [ECO-5268] Add Kotlin getting started to pubsub

- src/data/nav/chat.ts
- src/pages/docs/chat/getting-started/kotlin.mdx
- src/pages/docs/chat/getting-started/kotlin.textile
This guide outlines setup and usage of Ably Chat in an Android app built with Jetpack Compose. It covers key features such as realtime messaging, presence, reactions, message history, and resource management.
> Add Jetpack Compose guide for Ably Chat integration.

- content/getting-started/swift.textile
- src/data/nav/pubsub.ts
Adds Swift getting started guide for pub/sub
> [ECO-5267] Swift pub/sub getting started

- package.json
- src/components/GlobalLoading/GlobalLoading.tsx
- src/components/LanguageButton/LanguageButton.test.tsx
- src/components/blocks/Html/__snapshots__/Html.test.tsx.snap
- src/components/blocks/software/__snapshots__/Pre.test.tsx.snap
- src/components/blocks/wrappers/__snapshots__/LocalLanguageAlternatives.test.tsx.snap
- src/external-scripts/inkeep.ts
- yarn.lock
As a result of this optimisation effort: https://github.com/ably/ably-ui/pull/815.
Icon loading is heavy and slow (~2s per load) due to reasons mentioned in that PR, this PR should sort that out. A small nudge towards a more positive user experience (Ably's target user would not expect 6-8 working days for icons to show)
Additionally, includes a fix for the inkeep button being buried under page text in prod.
Review link: https://ably-docs-web-4440-redu-7iuphn.herokuapp.com/docs
Acceptance criteria: icons should all render and they should be fast
> [WEB-4440] Update ably-ui to 17.3.3, remove spritesheets

- src/external-scripts/inkeep.ts
In #2660 I mentioned a layering fix for the Inkeep chat button but I just went off the docs for it. 
Turns out it doesn't actually work, so I got inkeep going locally and got to the bottom of it. Turns out this `css` tag at the start of the custom CSS string was affecting it - don't see a separate reason to keep it there (it's reminiscent of styled components, which is unusual)
> [WEB-4440] fix: remove css tag from inkeep custom styles

- src/data/nav/pubsub.ts
This PR:
- Removes "How-to: Publish and subscribe" from the pub-sub navigation in `src/data/nav/pubsub.ts`.
- But keeps the page available via search (it hasn't been deleted)!
https://ably.atlassian.net/browse/EDU-1989
> Edu 1989 remove how to guide from nav

- content/errors/index.textile
This PR:
Updates the `content/errors/index` doc to correct the formatting of two logging metachannel names:
- Fixed from `Meta[log]` to `[meta]log`
- Fixed from `Meta[log:push]` to `[meta]log:push`
https://github.com/ably/docs/issues/2558
https://ably.atlassian.net/browse/EDU-1990
> EDU-1990: Correct typo in metachannels on errors overview page

- content/platform/deprecate/tls-v1-1.textile
- src/data/nav/platform.ts
Adding deprecation page re: TLS 1.0/1.1 support deprecation. Effective June 2025. See https://changelog.ably.com/deprecation-of-support-for-tls-1-0-and-1-1-304006
> [INF-5819] feat: add deprecation notice for TLS 1.0 and 1.1 support

- content/getting-started/javascript.textile
The Javascript getting started guide needed:
- Sign up to have a link.
- All Next Steps links to have `?lang=javascript` appended to them.
- Code snippet for programmatically publishing a message.
> Added improvements to Javascript getting started guide

- src/pages/docs/chat/setup.mdx
- Remove listing React as a required dependency
- Add `ably` to the npm install list for React + JS
- Call out that you should init clients outside the React component tree to avoid extra connections.
> chat: react setup instructions

- src/components/Markdown/MarkdownProvider.test.tsx
- src/components/Markdown/MarkdownProvider.tsx
- src/components/blocks/external-references/A.test.tsx
- src/components/blocks/external-references/A.tsx
Raised by @m-hulbert.
Links in content in MDX pages need to preserve any active lang params so that we get a consistent language experience between pages.
Review: https://ably-docs-web-4440-pres-2duhlf.herokuapp.com/docs/chat/rooms?lang=react
> [WEB-4460] fix: preserve lang param in content links

- src/pages/docs/chat/rooms/reactions.mdx
Right now we do a JSON structure of a reaction event and a table. This is duplication, so remove the JSON and just have a table.
> chat: remove duplication in the room reaction section

- content/auth/capabilities.textile
This PR:
Updates the example use case in `content/auth/capabilities` a live sports streaming app, replacing the previous outdated "message interactions".
#2558
https://ably.atlassian.net/browse/EDU-1992
> EDU-1992: Adds new use case

- content/getting-started/ruby.textile
- src/data/nav/pubsub.ts
> Add Ruby Getting Started guide

- src/pages/docs/chat/rooms/history.mdx
- src/pages/docs/chat/rooms/message-reactions.mdx
- src/pages/docs/chat/rooms/messages.mdx
- src/pages/docs/chat/rooms/occupancy.mdx
- src/pages/docs/chat/rooms/presence.mdx
- src/pages/docs/chat/rooms/reactions.mdx
Add message reactions for Swift/Kotlin
Also updated docs to reflect last API changes:
- Changed `get` to `history` in message history retrieval to improve clarity.
- Updated reaction and presence examples to incorporate new event type and structure adjustments.
> chat: add message reactions for Swift/Kotlin

- src/pages/docs/chat/rooms/messages.mdx
We're updating chat so that soft-deleted messages don't have data anymore. This change adds detail to that effect.
> chat: add soft delete clarification

- src/pages/docs/chat/rooms/message-reactions.mdx
- adds react code examples for message reactions
- restructures the page so that reaction types and the default type are explained before 'how to actually send a reaction'.
> chat: add react message reactions examples, restructure message reactions page

- examples/package.json
- examples/yarn.lock
- src/data/languages/languageData.ts
- src/pages/docs/chat/rooms/reactions.mdx
Updates the room reactions docs to change `type` -> `name`
> chat: bump docs for room reactions

- .github/workflows/review-app.yml
Noticed while monitoring the use of the `review-app` label, that the deployment section was temperamental at listing the deployments. Bumping the review app action fixes this as the plugin correctly uses `GITHUB_TOKEN` during the review app creation.
The deployment section of this PR is correctly updated. Feel free to remove and re-add the label to test
> [WEB-4311] Use latest action version

- src/components/Layout/MDXWrapper.tsx
- src/components/Layout/mdx/tiles.tsx
The first step to creating a landing page for Pub/Sub and other products getting started guides. This is the component which can be used by Getting started guides, but on other pages throughout the docs. You'll be able to pass the array of objects you wish to render through the riles. 
To access this page, go to `/docs/test` in your browser.
Once the PR is approved, I'll fixup a commit to remove the test page, which is:
```---
title: "Test page"
meta_description: "A page created with the sole purpose of testing a new MDX component"
meta_keywords: "No need"
---
The content below is the new component we're creating:
<Tiles>
{[
{
title: 'Test 1',
description: 'Here is a description for this first option',
image: 'icon-tech-ably',
link: '/docs/',
},
{
title: 'Test 2',
description: 'Here is a …
```
> Add Tile component

- src/pages/docs/getting-started/index.mdx
I forgot to add this to the Getting started guides landing page. So needed to add the PHP tile.
> Added PHP to getting started landing page

- src/pages/docs/getting-started/index.mdx
The structure of the nav for getting started guides for Pub/Sub was recently changed, in this PR https://github.com/ably/docs/pull/2718
The title was not. This PR fixes that.
> Update title of Pub/Sub getting started index page

- content/account/users.textile
We say in the current steps in https://ably.com/docs/account/users#close
- Downgrade your paid [package](https://ably.com/docs/pricing#packages) to Free:
- Navigate to Account then [Billing](https://ably.com/accounts/any/package).
- Click Save billing details to save your changes.
Specifically "click save billing details to save your changes" is unrelated to the downgrade package steps and where in https://ably.com/docs/pricing/free#downgrade we say "click the Downgrade button"
> add link to downgrade steps to close your account section

- src/data/examples/index.ts
- src/pages/docs/chat/index.mdx
- src/pages/docs/chat/rooms/message-reactions.mdx
- static/open-specs/chat.yaml
Updated a few areas where we use "add" instead of "send" for message reactions
> chat: update adding reactions to send

- content/getting-started/ruby.textile
The "Install Ruby" instruction in the Ruby getting started guide didn't have the closing ", so it was breaking the link.
> Fix broken link in Ruby getting started guide

- src/data/nav/pubsub.ts
- src/pages/docs/getting-started/index.mdx
The getting started guides for both Python and Go weren't showing in the navigation or in the overview page. This PR fixes that issue and displays them as expected.
> Added Python and Go to getting started nav

- src/data/nav/platform.ts
- src/pages/docs/platform/architecture/latency.mdx
- src/pages/docs/platform/architecture/performance.mdx
WIP: Add Latency page to the platform architecture documentation. Images will be swapped out for embedded Metabase reports in due course.
- https://ably-metabase.herokuapp.com/dashboard/1346-latencies-cross-region
- https://ably-metabase.herokuapp.com/dashboard/1347-latencies-real-browser
> [INF-5971] Add latency architecture page

- bin/validate-llms.txt.ts
Failed tasks on CI is blocking deployments elsewhere, despite not being required to merge...
This updates our CI task to exclude files we explicitly don't care about from an `llms.txt` point-of-view.
> WEB-4515 Fixing llms.txt validation

- content/api/realtime-sdk.textile
- content/api/rest-sdk.textile
This PR:
- Adds a new Thread safety section to the Rest and Realtime sections.
- This was removed from the Cocoa SDK trim and was not mentioned in the docs.
- https://github.com/ably/ably-cocoa/pull/2052
Jira:
https://ably.atlassian.net/browse/EDU-2010
> EDU-2010: Adds thread safety section

- package.json
- src/components/Layout/RightSidebar.tsx
- yarn.lock
As the title, commits suggest, change the "Open in" link in the right nav sidebar to include Claude (and leave space for other models), and track the clicks so we can get an idea of model sentiment across users.
Review link: https://ably-docs-web-4561-clau-a1tlvf.herokuapp.com/docs/chat/rooms/messages
https://github.com/user-attachments/assets/3b214100-f5c5-4d89-b25b-d8bc0f8b477a
This pull request updates the right sidebar to improve how external links and LLM (Large Language Model) integrations are presented to users. The main changes include splitting LLM links into their own section, adding support for Claude alongside ChatGPT, and enhancing the UI with tooltips and tracking. The update also bumps the `@ably/ui` dependency version.
**External integrations and UI improvements:**
* Split …
> [WEB-4561] Generalise LLM links, add Claude and track clicks

- src/data/nav/chat.ts
- src/data/nav/liveobjects.ts
- src/data/nav/pubsub.ts
- src/data/nav/spaces.ts
- src/pages/docs/liveobjects/quickstart.mdx
Pubsub uses "Getting started" -> "Guides", and Chat uses "Getting started" -> "Quickstarts".
> Update pubsub nav to match chat

- src/components/Layout/MDXWrapper.tsx
- src/components/blocks/software/Code/ApiKeyMenu.tsx
- src/contexts/user-context.ts
- src/redux/api-key/remote-api-key-data.ts
- src/templates/examples.tsx
- src/utilities/update-ably-connection-keys.test.ts
- src/utilities/update-ably-connection-keys.ts
This pull request refactors the handling of API keys in the `examples` page template and removes unused code related to user context and API key retrieval. The changes simplify the codebase by replacing dynamic API key logic with a static environment variable and removing unnecessary imports and functions.
Review app (it's a random website dependabot env, but it points to the right docs - log in as normal): https://website-dependabot-npm--7ueyw3.herokuapp.com/examples
Acceptance: it should work and say it's using the demo key in the Sandpack window footer
* Replaced the dynamic API key retrieval logic using `UserContext` and `getApiKey` with a static demo key sourced from the `GATSBY_VITE_ABLY_KEY` environment variable in `src/templates/examples.tsx`. This is a temporary solution until a …
> [WEB-4489] chore: disable personal keys on examples

- src/pages/docs/liveobjects/batch.mdx
This PR fixes an issue raised in [issue #2764](https://github.com/ably/docs/issues/2764). In LiveObjects batch page, Javascript code block, there's an incorrect naming of variables to `reactions` where it should be `tasks`.
> Incorrect variable name in batch liveobjects codeblock

- package.json
- yarn.lock
Solves the MDX SDK fallback issue via bumping `ably-ui` to 17.6.5.
Example: https://ably-docs-web-4553-code-qop3gn.herokuapp.com/docs/presence-occupancy/presence
> [WEB-4553] Bump ably-ui to 17.6.5

- src/pages/docs/liveobjects/concepts/objects.mdx
- src/pages/docs/liveobjects/index.mdx
- src/pages/docs/liveobjects/map.mdx
- src/pages/docs/liveobjects/rest-api-usage.mdx
- src/pages/docs/liveobjects/storage.mdx
[PUB-1667](https://ably.atlassian.net/browse/PUB-1667)
ably-js support for this added in https://github.com/ably/ably-js/pull/2052
[PUB-1667]: https://ably.atlassian.net/browse/PUB-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PUB-1667] Update LiveObjects docs to reflect support for JSON-serializable objects as LiveMap values

- src/components/Examples/ExamplesRenderer.tsx
The examples renderer uses its own version of Chat rather than what's in package.json. This change updates the version to the latest.
https://ably.atlassian.net/browse/CHA-1132
https://ably.atlassian.net/browse/CHA-1133
> fix: use correct version of ably chat in the examples

- src/pages/docs/metadata-stats/stats.mdx
The copy previously made it sounds like only messages sent were counted, which could be confusing for users who think this is messages sent to Ably, or sent from Ably, but not both.
See somewhat related [Slack message](https://ably-real-time.slack.com/archives/CF7GGBF2N/p1753425019299029) which surfaced this.
> Update stats to reflect sent messages includes recevied

- src/pages/docs/chat/getting-started/javascript.mdx
The Chat JS getting started guide only instructs to install @ably/chat not ably JS SDK too. Which isn't an issue when NPM version is 7. However any versions below will still require ably JS SDK to be installed manually.
> Add ably as a library install when running npm install in chat javascript getting started

- src/pages/docs/auth/revocation.mdx
- src/pages/docs/messages/batch.mdx
- src/pages/docs/presence-occupancy/presence.mdx
- src/pages/docs/push/publish.mdx
This PR fixes all occurrences of the `request()` method where a version parameter was missing after the update to v2. Note that the upgrade to v2 did not include this fix for all SDKs; so this doesn't change any examples for Java, Cocoa, PHP, Flutter or Ruby. 
Originally reported in: https://github.com/ably/docs/pull/2492
> [EDU-2057] Update request method to include version in requests

- src/pages/docs/chat/moderation/index.mdx
Fix the link to Bodyguard's documentation in the chat moderation docs.
> chat: update bodyguard documentation link

- src/pages/docs/chat/rooms/messages.mdx
- static/open-specs/chat.yaml
Documents the upcoming endpoint about fetching a single chat message by serial and the SDK methods to use it.
https://ably.atlassian.net/browse/CHA-1141
> Chat: add get single message

- src/pages/docs/chat/getting-started/javascript.mdx
While running through the Chat JS getting started guide, I found several issues along the way. One was introduced by my usage of env variables for the Ably API key. But the others wouldn't let me proceed until I fixed them. This PR fixes those issues:
- Fixed usage of env variables without the dotenv library. 
- Set package type to module when running `npm init`. 
- Added `@types/node` as a dependency as without this was throwing issues in the imports of the @ably/chat SDK.
> Fixed issues with getting started guide for Chat JS

- src/data/nav/chat.ts
- src/pages/docs/chat/rooms/media.mdx
Add an article showing how to add image (or other files) sharing in Ably Chat. It's a high-level overview, I don't think we should go into more details.
The URL is `/docs/guides/chat/media-sharing`. We previously discussed not to put it as a guide so I'll move it where we think it should be and add a link in the side menu.
> add media sharing document

- static/open-specs/chat.yaml
Chat `Message.reactions` was missing from the Message struct.
https://ably.atlassian.net/browse/CHA-1154
> Add chat message reactions api ref docs

- src/data/nav/pubsub.ts
- src/pages/docs/getting-started/index.mdx
- src/pages/docs/getting-started/javascript.mdx
- src/pages/docs/getting-started/node.mdx
The original JavaScript getting started guide was actually Node.js focused. So this moved the existing guide to node.mdx, then created a new JavaScript getting started guide focused on vanilla JavaScript.
> Create JavaScript and Node.js getting started guides

- content/partials/types/_error_info.textile
- content/partials/types/_paginated_result.textile
This PR: 
This PR addresses issue #2662, fixing unsafe Swift code patterns and adding docs for `ErrorInfo` nesting functionality.
-  `content/partials/types/_paginated_result` (PaginatedResult swift code update)
- `/partials/types/_error_info` (Nested error explanation)
https://ably.atlassian.net/browse/EDU-2013
> EDU-2013: Fix Swift safety and add ErrorInfo nesting examples

- src/pages/docs/liveobjects/counter.mdx
- src/pages/docs/liveobjects/index.mdx
- src/pages/docs/liveobjects/map.mdx
- src/pages/docs/liveobjects/rest-api-usage.mdx
Addresses comments from [1] that were posted after the PR was merged.
[1] https://github.com/ably/docs/pull/2774
> Address comments for LiveObjects pricing docs

- src/pages/docs/chat/getting-started/javascript.mdx
- src/pages/docs/chat/getting-started/react-native.mdx
Two bullet points were incorrectly numbered in two of the Chat getting started guides. This PR fixes them.
> Fix bullet point numbering issue in chat getting started guides

- src/data/nav/chat.ts
- src/pages/docs/chat/getting-started/android.mdx
- src/pages/docs/chat/index.mdx
Now the SDK is available for the JVM at large, we should differentiate getting started guides.
This change renames it to be explicitly Android.
> chat: rename kotlin getting started guide to android

- src/pages/docs/channels/options/deltas.mdx
- Implemented vcdiff encoding for go -> https://github.com/ably/ably-go/pull/690
- Added golang specific code snippet for the same
> Go vcdiff delta codec example snippet

- src/pages/docs/channels/options/deltas.mdx
- Added installation guide for `vcdiff` via pip extras.
- Provided code example for subscribing to channels with delta support in Python.
> Add instructions for installing and using the `vcdiff` decoder in Python

- src/utilities/update-ably-connection-keys.ts
environment is now deprecated (and for some reason isn't working with Sandbox on demo apps).
This change migrates to the new `endpoint` option.
NOTE: The preview apps will need to have their `GATSBY_ABLY_ENVIRONMENT` changed to `nonprod:sandbox`. If set, the main docs site will need to set `main` or leave empty.
> examples: use new ably-js endpoint option

- src/pages/docs/chat/getting-started/android.mdx
- src/pages/docs/chat/getting-started/javascript.mdx
- src/pages/docs/chat/getting-started/jvm.mdx
- src/pages/docs/chat/getting-started/react-native.mdx
- src/pages/docs/chat/getting-started/react-ui-components.mdx
- src/pages/docs/chat/getting-started/react.mdx
- src/pages/docs/chat/getting-started/swift.mdx
- src/pages/docs/getting-started/dotnet.mdx
- src/pages/docs/getting-started/flutter.mdx
- src/pages/docs/getting-started/go.mdx
- src/pages/docs/getting-started/java.mdx
- src/pages/docs/getting-started/javascript.mdx
- src/pages/docs/getting-started/kotlin.mdx
- src/pages/docs/getting-started/laravel.mdx
- src/pages/docs/getting-started/node.mdx
- src/pages/docs/getting-started/objective-c.mdx
- src/pages/docs/getting-started/php.mdx
- src/pages/docs/getting-started/python.mdx
- src/pages/docs/getting-started/react-native.mdx
- src/pages/docs/getting-started/react.mdx
- src/pages/docs/getting-started/ruby.mdx
- src/pages/docs/getting-started/swift.mdx
This PR updates the Ably CLI descriptions across all getting started guides to give context as to why it would be useful to sue the CLI while following the guide.
> [EDU-2090] - Add description to cli section of getting started guides

- content/api/realtime-sdk/connection.textile
> Fix ClientOptions link

- content/api/rest-api.textile
- content/api/sse.textile
- content/api/token-request-spec.textile
- content/partials/general/events/_non_enveloped_events.textile
- content/partials/shared/_channel_enumeration.textile
- content/partials/shared/_channel_metadata.textile
- content/partials/types/_push_channel.textile
- src/pages/docs/chat/moderation/direct/hive-dashboard.mdx
- src/pages/docs/liveobjects/concepts/operations.mdx
- src/pages/docs/liveobjects/rest-api-usage.mdx
- src/pages/docs/messages/batch.mdx
- src/pages/docs/metadata-stats/metadata/rest.mdx
- src/pages/docs/platform/errors/codes.mdx
- src/pages/docs/platform/integrations/inbound/webhooks.mdx
- src/pages/docs/platform/integrations/streaming/index.mdx
- src/pages/docs/platform/integrations/webhooks/index.mdx
- src/pages/docs/presence-occupancy/presence.mdx
- src/pages/docs/protocols/mqtt.mdx
- src/pages/docs/protocols/pubnub.mdx
- src/pages/docs/protocols/pusher.mdx
- src/pages/docs/protocols/sse.mdx
This PR updates the listed endpoints from `ably.io` to the new formats;
* `realtime.ably.io` and `rest.ably.io` consolidated to `main.realtime.ably.net`
* `mqtt.ably.io` to `main.mqtt.ably.net`
* `pusher.ably.io` and `realtime-pusher.ably.io` to `main.pusher.ably.net`
* `pubnub.ably.io` to `main.pubnub.ably.net`
> [EDU-2104] Update endpoints from `ably.io` to `ably.net`
